# Māori Data Sovereignty principles

[''**Data sovereignty** is the idea that data are subject to the laws and governance structures within the nation it is collected''](https://en.wikipedia.org/wiki/Data_sovereignty)

 > "Māori Data Sovereignty has emerged as a critical policy issue as Aotearoa
New Zealand develops world-leading linked administrative data resources." `r tufte::quote_footer('--- Andrew Sporle, Maui Hudson, Kiri West. Chapter 5, Indigenous Data Sovereignty and Policy')`


[Te Tiriti o Waitangi/Treaty of Waitangi](https://nzhistory.govt.nz/politics/treaty/read-the-Treaty/differences-between-the-texts) obliges the Government to actively protect [taonga](https://maoridictionary.co.nz/search?keywords=taonga), consult with Māori in respect of taonga, give effect to the principle of partnership and recognize Māori rangatiratanga over taonga. Factors that relate to how communities might recognize the taonga nature of any dataset include

 + provenance of the data: does the dataset come from a significant Māori source?
 + opportunity for the data: could the dataset support Māori aspirations for their people or their whenua (land)?
 + utility of the data: does the dataset have multiple uses?
 
## Learning objectives

+ **Define** data sovereignty and **explain** this in relation to a researcher's obligation when collecting, displaying, and analysing data
+ **Define** and **discuss** Māori Data Sovereignty principles

## Māori Data Sovereignty principles

> "For Indigenous peoples, historical encounters with statistics have been fraught, and none more so than when involving official data produced as part of colonial attempts at statecraft." `r tufte::quote_footer('--- Lovett, R., Lee, V., Kukutai, T., Cormack, D., Rainie, S.C. and Walker, J., 2019. Good data practices for Indigenous data sovereignty and governance. Good data, pp.26-36.')`
 
 > "Māori Data Sovereignty has emerged as a critical policy issue as Aotearoa
New Zealand develops world-leading linked administrative data resources." `r tufte::quote_footer('--- Andrew Sporle, Maui Hudson, Kiri West. Chapter 5, Indigenous Data Sovereignty and Policy')`


## Māori Data Sovereignty principles


> “Māori data refers to data produced by Māori or that is about Māori and the environments we have relationships with."  `r tufte::quote_footer('--- Te Mana Raraunga Charter')`


> Data is a “potential taonga, something precious that needs to be maintained, in relation to its utility” `r tufte::quote_footer('--- Dr W. Edwards, TMR website')`


**Māori Data Sovereignty principles** to inform the recognition of Māori rights and interests in data, and the ethical use of data to enhance Māori well-being:


  **Rangatiratanga**, authority

 +  Māori have an inherent right to exercise control over Māori data and Māori data ecosystems. This right includes, but is not limited to, the creation, collection, access, analysis, interpretation, management, security, dissemination, use and reuse of Māori data.
 + Decisions about the physical and virtual storage of Māori data shall enhance control for current and future generations. Whenever possible, Māori data shall be stored in Aotearoa New Zealand.
 + Māori have the right to data that is relevant and empowers sustainable self-determination and effective self-governance


 **Whakapapa**, relationships

  + All data has a whakapapa (genealogy). Accurate metadata should, at minimum, provide information about the provenance of the data, the purpose(s) for its collection, the context of its collection, and the parties involved.
  + The ability to disaggregate Māori data increases its relevance for Māori communities and iwi. Māori data shall be collected and coded using categories that prioritise Māori needs and aspirations.
  +  Current decision-making over data can have long-term consequences, good and bad, for future generations of Māori. A key goal of Māori data governance should be to protect against future harm.

 **Whanaungatanga**, obligations

  + Individuals’ rights (including privacy rights), risks and benefits in relation to data need to be balanced with those of the groups of which they are a part. In some contexts, collective Māori rights will prevail over those of individuals.
  + Individuals and organisations responsible for the creation, collection, analysis, management, access, security or dissemination of Māori data are accountable to the communities, groups and individuals from whom the data derive

**Kotahitanga**, collective benefit

  + Data ecosystems shall be designed and function in ways that enable Māori to derive individual and collective benefit.
  + Build capacity. Māori Data Sovereignty requires the development of a Māori workforce to enable the creation, collection, management, security, governance and application of data.
  + Connections between Māori and other Indigenous peoples shall be supported to enable the sharing of strategies, resources and ideas in relation to data, and the attainment of common goals.
  
 **Manaakitanga**, reciprocity

 +  The collection, use and interpretation of data shall uphold the dignity of Māori communities, groups and individuals. Data analysis that stigmatises or blames Māori can result in collective and individual harm and should be actively avoided.
 + Free, prior and informed consent shall underpin the collection and use of all data from or about Māori. Less defined types of consent shall be balanced by stronger governance arrangements.

 **Kaitiakitanga**, guardianship

  +  Māori data shall be stored and transferred in such a way that it enables and reinforces the capacity of Māori to exercise kaitiakitanga over Māori data.
  + Ethics. Tikanga, kawa (protocols) and mātauranga (knowledge) shall underpin the protection, access and use of Māori data.
  + Māori shall decide which Māori
data shall be controlled (tapu) or open (noa) access.



## Resources

+ [Why data sovereignty matters](https://www.onenet.co.nz/our-resources/why-data-sovereignty-matters/)
+ [Indigenous Data Sovereignty and Policy](https://library.oapen.org/handle/20.500.12657/42782)
+ [Principles of Māori Data Sovereignty](https://cdn.auckland.ac.nz/assets/psych/about/our-research/documents/TMR%2BM%C4%81ori%2BData%2BSovereignty%2BPrinciples%2BOct%2B2018.pdf)
+ [Good data practices for Indigenous data sovereignty and governance.](https://researchcommons.waikato.ac.nz/bitstream/handle/10289/12919/data%20practices.pdf?sequence=5&isAllowed=y)
