# Module 2 {-}

**Learning objectives**

+ **List** the aims, **write out** the appropriate null and alternative hypothesis using statistical notation for a permutation (*randomization*) test
+ **Write** `R` code to carry out a permutation test
+ **List** the aims, **write out** the appropriate null and alternative hypothesis using statistical notation for a bootstrap procedure 
+ **Write** `R` code to carry out bootstapping
+ **Carry out** and **interpret** tests for the existence of relationships between explanatory variables and the response in a linear model
+ **Write** R code to fit a linear model with a single continuous explanatory variable
+ **Write** R code to fit a linear model with a continuous explanatory variable and a factor explanatory variable
**Interpret** estimated effects with reference to confidence intervals from linear regression models. Specifically the interpretation of
   + the intercept
   + the effect of a factor
   + the effect of a one-unit increase in a numeric variable
   + the effect of an x-unit increase in a numeric variable
+ **Make** a point prediction of the response for a new observation
+ **Write** R code to fit a linear model with interaction terms in the explanatory variables
+ **Interpret** estimated effects with reference to confidence intervals from linear regression models. Specifically the interpretation of
    + main effects in a model with an interaction
    + the effect of one variable when others are included in the model


**Other resources**

+ [Exploring interactions with continuous predictors in regression models](https://interactions.jacob-long.com/articles/interactions.html)
+ [The ASA Statement on p-Values: Context, Process, and Purpose](https://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108)

