<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>13 Dimension reduction | bluebook BIOSCI738</title>
  <meta name="description" content="13 Dimension reduction | bluebook BIOSCI738" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="13 Dimension reduction | bluebook BIOSCI738" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="13 Dimension reduction | bluebook BIOSCI738" />
  
  
  

<meta name="author" content="Charlotte Jones-Todd" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multivariate-data-methods.html"/>

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="src/my-style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#course-overview"><i class="fa fa-check"></i><b>0.1</b> Course Overview</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#key-topics"><i class="fa fa-check"></i><b>0.2</b> Key Topics</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html"><i class="fa fa-check"></i><b>1</b> <code>R</code>, <code>RStudio</code>, and <code>git</code></a><ul>
<li class="chapter" data-level="1.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="1.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#intro-to-r-rstudio"><i class="fa fa-check"></i><b>1.2</b> Intro to <code>R</code> &amp; <code>RStudio</code></a><ul>
<li class="chapter" data-level="1.2.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#why"><i class="fa fa-check"></i><b>1.2.1</b> Why?</a></li>
<li class="chapter" data-level="1.2.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>1.2.2</b> Installing R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting started</a><ul>
<li class="chapter" data-level="1.3.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#r-errors"><i class="fa fa-check"></i><b>1.3.1</b> R errors 😱</a></li>
<li class="chapter" data-level="1.3.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#r-scripts-a-.r-file"><i class="fa fa-check"></i><b>1.3.2</b> R <em>Script</em>s (a <code>.r</code> file)</a></li>
<li class="chapter" data-level="1.3.3" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#writing-comments"><i class="fa fa-check"></i><b>1.3.3</b> Writing <em>Comments</em></a></li>
<li class="chapter" data-level="1.3.4" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#change-the-rstudio-appearance-up-to-your-taste"><i class="fa fa-check"></i><b>1.3.4</b> Change the <code>RStudio</code> appearance up to your taste</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#reproducible-research"><i class="fa fa-check"></i><b>1.4</b> Reproducible research</a><ul>
<li class="chapter" data-level="1.4.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#good-practice"><i class="fa fa-check"></i><b>1.4.1</b> Good practice</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#version-control-with-git-and-github"><i class="fa fa-check"></i><b>1.5</b> Version control with <code>git</code> and GitHub</a><ul>
<li class="chapter" data-level="1.5.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#setup-tldr"><i class="fa fa-check"></i><b>1.5.1</b> Setup TL;DR</a></li>
<li class="chapter" data-level="1.5.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#cloning-a-repository-from-github-using-rstudio"><i class="fa fa-check"></i><b>1.5.2</b> Cloning a repository from <code>GitHub</code> using <code>RStudio</code></a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>1.6</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="1.6.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#starting-out-with-tidyverse"><i class="fa fa-check"></i><b>1.6.1</b> Starting out with <code>tidyverse</code></a></li>
<li class="chapter" data-level="1.6.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#reading-in-data-from-a-.csv-file"><i class="fa fa-check"></i><b>1.6.2</b> Reading in data from a <code>.csv</code> file</a></li>
<li class="chapter" data-level="1.6.3" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#explore-your-data"><i class="fa fa-check"></i><b>1.6.3</b> Explore your data</a></li>
<li class="chapter" data-level="1.6.4" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#explore-your-data-1"><i class="fa fa-check"></i><b>1.6.4</b> Explore your data</a></li>
<li class="chapter" data-level="1.6.5" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#the-pipe-operator"><i class="fa fa-check"></i><b>1.6.5</b> The pipe operator <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#other-resources"><i class="fa fa-check"></i><b>1.7</b> Other resources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html"><i class="fa fa-check"></i><b>2</b> Māori Data Sovereignty principles</a><ul>
<li class="chapter" data-level="2.1" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.1</b> Learning objectives</a></li>
<li class="chapter" data-level="2.2" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#māori-data-sovereignty-principles-1"><i class="fa fa-check"></i><b>2.2</b> Māori Data Sovereignty principles</a></li>
<li class="chapter" data-level="2.3" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#māori-data-sovereignty-principles-2"><i class="fa fa-check"></i><b>2.3</b> Māori Data Sovereignty principles</a></li>
<li class="chapter" data-level="2.4" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#resources"><i class="fa fa-check"></i><b>2.4</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html"><i class="fa fa-check"></i><b>3</b> Data wrangling and vizualisation</a><ul>
<li class="chapter" data-level="3.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.1</b> Learning objectives</a></li>
<li class="chapter" data-level="3.2" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#common-dataframe-manipulations-in-the-tidyverse"><i class="fa fa-check"></i><b>3.2</b> Common dataframe manipulations in the <code>tidyverse</code></a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#using-dplyr-and-tidyr"><i class="fa fa-check"></i><b>3.2.1</b> Using <code>dplyr</code> and <code>tidyr</code></a></li>
<li class="chapter" data-level="3.2.2" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#introuducing-the-palmer-penguins"><i class="fa fa-check"></i><b>3.2.2</b> Introuducing the <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081">Palmer penguins</a></a></li>
<li class="chapter" data-level="3.2.3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#common-dataframe-manipulations-in-the-tidyverse-using-dplyr-and-tidyr"><i class="fa fa-check"></i><b>3.2.3</b> Common dataframe manipulations in the <code>tidyverse</code>, using <code>dplyr</code> and <code>tidyr</code></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#data-viz"><i class="fa fa-check"></i><b>3.3</b> Data Viz</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#exploratory-and-explanatory-plots"><i class="fa fa-check"></i><b>3.3.1</b> Exploratory and explanatory plots</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#ten-simple-rules-for-better-figures"><i class="fa fa-check"></i><b>3.4</b> Ten Simple Rules for Better Figures</a></li>
<li class="chapter" data-level="3.5" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#ggplot2"><i class="fa fa-check"></i><b>3.5</b> <code>ggplot2</code></a><ul>
<li class="chapter" data-level="3.5.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#ggplot2-layers"><i class="fa fa-check"></i><b>3.5.1</b> <code>ggplot2</code> layers</a></li>
<li class="chapter" data-level="3.5.2" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#examples"><i class="fa fa-check"></i><b>3.5.2</b> Examples</a></li>
<li class="chapter" data-level="3.5.3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#the-good-the-bad-and-the-ugly..."><i class="fa fa-check"></i><b>3.5.3</b> The Good, the Bad, and the Ugly...</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#resources-1"><i class="fa fa-check"></i><b>3.6</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html"><i class="fa fa-check"></i><b>4</b> Introduction to the design and analysis of experiments</a><ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#key-phrases"><i class="fa fa-check"></i><b>4.2</b> Key phrases</a></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#three-key-principles"><i class="fa fa-check"></i><b>4.3</b> Three key principles:</a><ul>
<li class="chapter" data-level="4.3.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#replication"><i class="fa fa-check"></i><b>4.3.1</b> <strong>Replication</strong></a></li>
<li class="chapter" data-level="4.3.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#randomization"><i class="fa fa-check"></i><b>4.3.2</b> <strong>Randomization</strong></a></li>
<li class="chapter" data-level="4.3.3" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#blocking"><i class="fa fa-check"></i><b>4.3.3</b> <strong>Blocking</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#one-way-analysis-of-variance-anova"><i class="fa fa-check"></i><b>4.4</b> One-Way <strong>An</strong>alysis <strong>o</strong>f <strong>Va</strong>riance (ANOVA)</a><ul>
<li class="chapter" data-level="4.4.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#between-group-ss-ssb"><i class="fa fa-check"></i><b>4.4.1</b> Between group SS (SSB)</a></li>
<li class="chapter" data-level="4.4.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#within-group-ss-ssw"><i class="fa fa-check"></i><b>4.4.2</b> Within group SS (SSW)</a></li>
<li class="chapter" data-level="4.4.3" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#f-statistic"><i class="fa fa-check"></i><b>4.4.3</b> F-statistic</a></li>
<li class="chapter" data-level="4.4.4" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#degrees-of-freedom-df"><i class="fa fa-check"></i><b>4.4.4</b> Degrees of freedom (DF)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#p-values"><i class="fa fa-check"></i><b>4.5</b> 😱 p-values 😱</a></li>
<li class="chapter" data-level="4.6" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#terminology-and-issues"><i class="fa fa-check"></i><b>4.6</b> Terminology and issues</a></li>
<li class="chapter" data-level="4.7" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#resources-2"><i class="fa fa-check"></i><b>4.7</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="a-completely-randomomised-design.html"><a href="a-completely-randomomised-design.html"><i class="fa fa-check"></i><b>5</b> A completely randomomised design</a><ul>
<li class="chapter" data-level="5.1" data-path="a-completely-randomomised-design.html"><a href="a-completely-randomomised-design.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="a-completely-randomomised-design.html"><a href="a-completely-randomomised-design.html#analysis-of-a-completely-randomised-design-in-r-aov-and-lm"><i class="fa fa-check"></i><b>5.2</b> Analysis of a Completely Randomised Design in <code>R</code>: <code>aov()</code> and <code>lm()</code></a><ul>
<li class="chapter" data-level="5.2.1" data-path="a-completely-randomomised-design.html"><a href="a-completely-randomomised-design.html#aov"><i class="fa fa-check"></i><b>5.2.1</b> <code>aov()</code></a></li>
<li class="chapter" data-level="5.2.2" data-path="a-completely-randomomised-design.html"><a href="a-completely-randomomised-design.html#lm"><i class="fa fa-check"></i><b>5.2.2</b> <code>lm()</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i><b>6</b> Multiple comparisons</a><ul>
<li class="chapter" data-level="6.1" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#learning-objectives-5"><i class="fa fa-check"></i><b>6.1</b> Learning objectives</a></li>
<li class="chapter" data-level="6.2" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#adjustments-for-multiple-testing"><i class="fa fa-check"></i><b>6.2</b> Adjustments for multiple testing</a><ul>
<li class="chapter" data-level="6.2.1" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#classification-of-multiple-hypothesis-tests"><i class="fa fa-check"></i><b>6.2.1</b> Classification of multiple hypothesis tests</a></li>
<li class="chapter" data-level="6.2.2" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#using-the-predictmeans-package"><i class="fa fa-check"></i><b>6.2.2</b> Using the <code>predictmeans</code> package</a></li>
<li class="chapter" data-level="6.2.3" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#multiple-comparison-procedures"><i class="fa fa-check"></i><b>6.2.3</b> Multiple comparison procedures</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="factorial-experiments.html"><a href="factorial-experiments.html"><i class="fa fa-check"></i><b>7</b> Factorial experiments</a><ul>
<li class="chapter" data-level="7.1" data-path="factorial-experiments.html"><a href="factorial-experiments.html#learning-objectives-6"><i class="fa fa-check"></i><b>7.1</b> Learning objectives</a></li>
<li class="chapter" data-level="7.2" data-path="factorial-experiments.html"><a href="factorial-experiments.html#factorial-design-as-a-crd"><i class="fa fa-check"></i><b>7.2</b> Factorial design (as a CRD)</a><ul>
<li class="chapter" data-level="7.2.1" data-path="factorial-experiments.html"><a href="factorial-experiments.html#equal-replications-balanced-design"><i class="fa fa-check"></i><b>7.2.1</b> Equal replications (balanced design)</a></li>
<li class="chapter" data-level="7.2.2" data-path="factorial-experiments.html"><a href="factorial-experiments.html#unqual-replications-unbalanced-design"><i class="fa fa-check"></i><b>7.2.2</b> Unqual replications (unbalanced design)</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="factorial-experiments.html"><a href="factorial-experiments.html#tldr-model-formula-syntax-in-r"><i class="fa fa-check"></i><b>7.3</b> TL;DR, Model formula syntax in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="blocking-incorporating-into-design-and-analysis-of.html"><a href="blocking-incorporating-into-design-and-analysis-of.html"><i class="fa fa-check"></i><b>8</b> Blocking: incorporating into design and analysis of</a><ul>
<li class="chapter" data-level="8.1" data-path="blocking-incorporating-into-design-and-analysis-of.html"><a href="blocking-incorporating-into-design-and-analysis-of.html#learning-objectives-7"><i class="fa fa-check"></i><b>8.1</b> Learning objectives</a></li>
<li class="chapter" data-level="8.2" data-path="blocking-incorporating-into-design-and-analysis-of.html"><a href="blocking-incorporating-into-design-and-analysis-of.html#blocking-1"><i class="fa fa-check"></i><b>8.2</b> Blocking</a></li>
<li class="chapter" data-level="8.3" data-path="blocking-incorporating-into-design-and-analysis-of.html"><a href="blocking-incorporating-into-design-and-analysis-of.html#a-randomised-controlled-block-design-rcbd"><i class="fa fa-check"></i><b>8.3</b> A Randomised Controlled Block Design (RCBD)</a></li>
<li class="chapter" data-level="8.4" data-path="blocking-incorporating-into-design-and-analysis-of.html"><a href="blocking-incorporating-into-design-and-analysis-of.html#fixed-or-random"><i class="fa fa-check"></i><b>8.4</b> Fixed or Random???</a><ul>
<li class="chapter" data-level="8.4.1" data-path="blocking-incorporating-into-design-and-analysis-of.html"><a href="blocking-incorporating-into-design-and-analysis-of.html#ignoring-an-effect"><i class="fa fa-check"></i><b>8.4.1</b> Ignoring an effect</a></li>
<li class="chapter" data-level="8.4.2" data-path="blocking-incorporating-into-design-and-analysis-of.html"><a href="blocking-incorporating-into-design-and-analysis-of.html#analysis-using-lmer-from-lme4"><i class="fa fa-check"></i><b>8.4.2</b> Analysis using <code>lmer()</code> from <code>lme4</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html"><i class="fa fa-check"></i><b>9</b> Split-plot and repeated measures designs</a><ul>
<li class="chapter" data-level="9.1" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#learning-objectives-8"><i class="fa fa-check"></i><b>9.1</b> Learning objectives</a></li>
<li class="chapter" data-level="9.2" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#analysis-of-a-split-plot-design"><i class="fa fa-check"></i><b>9.2</b> Analysis of a split-plot design</a><ul>
<li class="chapter" data-level="9.2.1" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#using-aov"><i class="fa fa-check"></i><b>9.2.1</b> Using <code>aov()</code></a></li>
<li class="chapter" data-level="9.2.2" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#using-lmer-from-lmetest-and-lmer4-and-predictmeans"><i class="fa fa-check"></i><b>9.2.2</b> Using <code>lmer()</code> (from <code>lmeTest</code> and <code>lmer4</code>) and <code>predictmeans()</code></a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#analysis-of-a-repeated-measures-design"><i class="fa fa-check"></i><b>9.3</b> Analysis of a repeated measures design</a><ul>
<li class="chapter" data-level="9.3.1" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#the-data"><i class="fa fa-check"></i><b>9.3.1</b> The data</a></li>
<li class="chapter" data-level="9.3.2" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#visualise"><i class="fa fa-check"></i><b>9.3.2</b> Visualise</a></li>
<li class="chapter" data-level="9.3.3" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#using-aov-1"><i class="fa fa-check"></i><b>9.3.3</b> Using <code>aov()</code></a></li>
<li class="chapter" data-level="9.3.4" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#using-lmer-from-lmertest-and-lme4-and-predictmeans"><i class="fa fa-check"></i><b>9.3.4</b> Using <code>lmer()</code> (from <code>lmerTest</code> and <code>lme4</code>) and <code>predictmeans()</code></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="split-plot-and-repeated-measures-designs.html"><a href="split-plot-and-repeated-measures-designs.html#repeated-measures-designs-as-split-plots-in-time"><i class="fa fa-check"></i><b>9.4</b> Repeated measures designs as <em>split-plots in time</em></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="statistical-inference.html"><a href="statistical-inference.html"><i class="fa fa-check"></i><b>10</b> Statistical Inference</a><ul>
<li class="chapter" data-level="10.1" data-path="statistical-inference.html"><a href="statistical-inference.html#learning-objectives-9"><i class="fa fa-check"></i><b>10.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="10.2" data-path="statistical-inference.html"><a href="statistical-inference.html#regression"><i class="fa fa-check"></i><b>10.2</b> Regression</a><ul>
<li class="chapter" data-level="10.2.1" data-path="statistical-inference.html"><a href="statistical-inference.html#some-mathematical-notation"><i class="fa fa-check"></i><b>10.2.1</b> Some mathematical notation</a></li>
<li class="chapter" data-level="10.2.2" data-path="statistical-inference.html"><a href="statistical-inference.html#modeling-bill-depth"><i class="fa fa-check"></i><b>10.2.2</b> Modeling Bill Depth</a></li>
<li class="chapter" data-level="10.2.3" data-path="statistical-inference.html"><a href="statistical-inference.html#single-continuous-variable"><i class="fa fa-check"></i><b>10.2.3</b> Single continuous variable</a></li>
<li class="chapter" data-level="10.2.4" data-path="statistical-inference.html"><a href="statistical-inference.html#factor-and-a-continous-variable"><i class="fa fa-check"></i><b>10.2.4</b> Factor and a continous variable</a></li>
<li class="chapter" data-level="10.2.5" data-path="statistical-inference.html"><a href="statistical-inference.html#interactions"><i class="fa fa-check"></i><b>10.2.5</b> Interactions</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="statistical-inference.html"><a href="statistical-inference.html#model-comparison-selection-and-checking-again"><i class="fa fa-check"></i><b>10.3</b> Model, comparison, selection, and checking (again)</a><ul>
<li class="chapter" data-level="10.3.1" data-path="statistical-inference.html"><a href="statistical-inference.html#model-comparison-and-selection"><i class="fa fa-check"></i><b>10.3.1</b> Model comparison and selection</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="statistical-inference.html"><a href="statistical-inference.html#point-predictions-and-confidence-intervals"><i class="fa fa-check"></i><b>10.4</b> Point predictions and confidence intervals</a><ul>
<li class="chapter" data-level="10.4.1" data-path="statistical-inference.html"><a href="statistical-inference.html#confidence-intervals-for-parameters"><i class="fa fa-check"></i><b>10.4.1</b> Confidence intervals for parameters</a></li>
<li class="chapter" data-level="10.4.2" data-path="statistical-inference.html"><a href="statistical-inference.html#point-prediction"><i class="fa fa-check"></i><b>10.4.2</b> Point prediction</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="statistical-inference.html"><a href="statistical-inference.html#tldr-lm"><i class="fa fa-check"></i><b>10.5</b> TL;DR <code>lm()</code></a><ul>
<li class="chapter" data-level="10.5.1" data-path="statistical-inference.html"><a href="statistical-inference.html#model-formula-syntax"><i class="fa fa-check"></i><b>10.5.1</b> <strong>Model formula</strong> syntax</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="statistical-inference.html"><a href="statistical-inference.html#other-resources-optional-but-recommended"><i class="fa fa-check"></i><b>10.6</b> Other resources: optional but recommended</a></li>
<li class="chapter" data-level="10.7" data-path="statistical-inference.html"><a href="statistical-inference.html#beyond-linear-models-to-generalised-linear-models-glms-not-examinable"><i class="fa fa-check"></i><b>10.7</b> Beyond Linear Models to Generalised Linear Models (GLMs) (<em>not examinable</em>)</a><ul>
<li class="chapter" data-level="10.7.1" data-path="statistical-inference.html"><a href="statistical-inference.html#counting-animals..."><i class="fa fa-check"></i><b>10.7.1</b> Counting animals...</a></li>
<li class="chapter" data-level="10.7.2" data-path="statistical-inference.html"><a href="statistical-inference.html#other-modelling-approaches-not-examinable"><i class="fa fa-check"></i><b>10.7.2</b> Other modelling approaches (not examinable)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="resampling-procedures.html"><a href="resampling-procedures.html"><i class="fa fa-check"></i><b>11</b> Resampling Procedures</a><ul>
<li class="chapter" data-level="11.1" data-path="resampling-procedures.html"><a href="resampling-procedures.html#learning-objectives-10"><i class="fa fa-check"></i><b>11.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="11.2" data-path="resampling-procedures.html"><a href="resampling-procedures.html#resampling"><i class="fa fa-check"></i><b>11.2</b> Resampling</a><ul>
<li class="chapter" data-level="11.2.1" data-path="resampling-procedures.html"><a href="resampling-procedures.html#significance-tests"><i class="fa fa-check"></i><b>11.2.1</b> Significance tests</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="resampling-procedures.html"><a href="resampling-procedures.html#significance-testing-using-permutation-randomisation-tests"><i class="fa fa-check"></i><b>11.3</b> Significance testing using permutation (<em>randomisation</em>) tests</a><ul>
<li class="chapter" data-level="11.3.1" data-path="resampling-procedures.html"><a href="resampling-procedures.html#permutation-test-on-two-independent-samples"><i class="fa fa-check"></i><b>11.3.1</b> Permutation Test on Two Independent Samples</a></li>
<li class="chapter" data-level="11.3.2" data-path="resampling-procedures.html"><a href="resampling-procedures.html#p-values-from-permutation-tests"><i class="fa fa-check"></i><b>11.3.2</b> P-values from permutation tests</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="resampling-procedures.html"><a href="resampling-procedures.html#the-bootstrap"><i class="fa fa-check"></i><b>11.4</b> The bootstrap</a><ul>
<li class="chapter" data-level="11.4.1" data-path="resampling-procedures.html"><a href="resampling-procedures.html#example-constructing-bootstrap-confidence-intervals"><i class="fa fa-check"></i><b>11.4.1</b> Example: constructing bootstrap confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="resampling-procedures.html"><a href="resampling-procedures.html#differences-between-permutation-test-and-bootstrap-test"><i class="fa fa-check"></i><b>11.5</b> Differences between permutation test and bootstrap test</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html"><i class="fa fa-check"></i><b>12</b> Multivariate Data Methods</a><ul>
<li class="chapter" data-level="12.1" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#learning-objectives-11"><i class="fa fa-check"></i><b>12.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="12.2" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#clustering"><i class="fa fa-check"></i><b>12.2</b> Clustering</a><ul>
<li class="chapter" data-level="12.2.1" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#clustering-algorithms"><i class="fa fa-check"></i><b>12.2.1</b> Clustering algorithms</a></li>
<li class="chapter" data-level="12.2.2" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#with-ants"><i class="fa fa-check"></i><b>12.2.2</b> With ants</a></li>
<li class="chapter" data-level="12.2.3" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#k-means-using-the-palmerpenguins-data"><i class="fa fa-check"></i><b>12.2.3</b> k-means using the <code>palmerpenguins</code> data</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#tldr-k-means-clustering"><i class="fa fa-check"></i><b>12.3</b> TL;DR k-means clustering</a></li>
<li class="chapter" data-level="12.4" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#other-resources-optional-but-recommended-1"><i class="fa fa-check"></i><b>12.4</b> Other resources: optional but recommended</a><ul>
<li class="chapter" data-level="12.4.1" data-path="multivariate-data-methods.html"><a href="multivariate-data-methods.html#multidimensional-scaling-in-r-not-examinable"><i class="fa fa-check"></i><b>12.4.1</b> Multidimensional Scaling in <code>R</code> (<em>not examinable</em>)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="dimension-reduction.html"><a href="dimension-reduction.html"><i class="fa fa-check"></i><b>13</b> Dimension reduction</a><ul>
<li class="chapter" data-level="13.1" data-path="dimension-reduction.html"><a href="dimension-reduction.html#learning-objectives-12"><i class="fa fa-check"></i><b>13.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="13.2" data-path="dimension-reduction.html"><a href="dimension-reduction.html#dimension-reduction-1"><i class="fa fa-check"></i><b>13.2</b> Dimension reduction</a></li>
<li class="chapter" data-level="13.3" data-path="dimension-reduction.html"><a href="dimension-reduction.html#pca-in-r"><i class="fa fa-check"></i><b>13.3</b> PCA in <code>R</code></a><ul>
<li class="chapter" data-level="13.3.1" data-path="dimension-reduction.html"><a href="dimension-reduction.html#using-the-palmerpenguins-data"><i class="fa fa-check"></i><b>13.3.1</b> Using the <code>palmerpenguins</code> data</a></li>
<li class="chapter" data-level="13.3.2" data-path="dimension-reduction.html"><a href="dimension-reduction.html#athletes"><i class="fa fa-check"></i><b>13.3.2</b> Athletes</a></li>
<li class="chapter" data-level="13.3.3" data-path="dimension-reduction.html"><a href="dimension-reduction.html#ants-from-previous-chapter"><i class="fa fa-check"></i><b>13.3.3</b> Ants (from previous chapter)</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="dimension-reduction.html"><a href="dimension-reduction.html#reality-check-reducing-noise..."><i class="fa fa-check"></i><b>13.4</b> Reality check: reducing noise...</a></li>
<li class="chapter" data-level="13.5" data-path="dimension-reduction.html"><a href="dimension-reduction.html#other-resources-optional-but-recommended-2"><i class="fa fa-check"></i><b>13.5</b> Other resources: optional but recommended</a><ul>
<li class="chapter" data-level="13.5.1" data-path="dimension-reduction.html"><a href="dimension-reduction.html#multidimensional-scaling-in-r"><i class="fa fa-check"></i><b>13.5.1</b> Multidimensional Scaling in <code>R</code></a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><em>bluebook</em> BIOSCI738</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="dimension-reduction" class="section level1">
<h1><span class="header-section-number">13</span> Dimension reduction</h1>
<div id="learning-objectives-12" class="section level2">
<h2><span class="header-section-number">13.1</span> Learning Objectives</h2>
<ul>
<li>Explain the aims and motivation behind Principal Component Analysis (PCA) and its relevance in biology</li>
<li>Write <code>R</code> code to carry out PCA</li>
<li>Interpret principal component scores and describe a subject with a high or low score</li>
<li>Interpret <code>R</code> output from PCA</li>
<li>Interpret and communicate, to both a statistical and non-statistical audience, dimaension reduction techniques</li>
</ul>
</div>
<div id="dimension-reduction-1" class="section level2">
<h2><span class="header-section-number">13.2</span> Dimension reduction</h2>
<p>Reduction of dimensions is needed when there are far too many features in a dataset, making it hard to distinguish between the important ones that are relevant to the output and the redundant or not-so important ones. Reducing the dimensions of data is called <strong>dimensionality reduction.</strong></p>
<p>So the aim is to <strong>find the best low-dimensional representation of the variation</strong> in a multivariate (lots and lots of variables) data set, but how do we do this?</p>
<p>One way is termed Principal Component Analysis (PCA). PCA is a <strong>feature extraction</strong> method that <strong>reduces the dimensionality of the data</strong> (number of variables) by creating new uncorrelated variables while minimizing loss of information on the original variables.</p>
<p><strong>Think of a baguette.</strong> The baguette pictured here represents two data dimensions: 1) the length of the bread and 2) the height of the bread (we'll ignore depth of bread for now). Think of the baguette as your data; when we carry out PCA we're rotating our original axes (<em>x- and y-coordinates</em>) to capture as much of the variation in our data as possible. This results in <strong>new</strong> uncorrelated variables that each explain a % of variation in our data; the procedure is designed so that the first new variable (PC1) explains the most, the second (PC2) the second most and so on.</p>
<div class="figure">
<img src="https://raw.githubusercontent.com/cmjt/statbiscuits/master/figs_n_gifs/pca.gif" />

</div>
<p>Now rather than a baguette think of data; the baguette above represent the <em>shape</em> of the scatter between the two variables plotted below. The rotating grey axes represent the PCA procedure, essentially searching for the <em>best</em> rotation of the original axes to represent the variation in the data as best it can. Mathematically the Euclidean distance (e.g., the distance between points <span class="math inline">\(p\)</span> and <span class="math inline">\(q\)</span> in Euclidean space, <span class="math inline">\(\sqrt{(p-q)^2}\)</span>) between the points and the rotating axes is being minimized (i.e., the shortest possible across all points), see the blue lines. Once this distance is minimized across all points we &quot;settle&quot; on our new axes (the black tiled axes).</p>
<div class="figure">
<img src="https://raw.githubusercontent.com/cmjt/statbiscuits/master/figs_n_gifs/perp.gif" />

</div>
<p>Luckily we can do this all in <code>R</code>!</p>
</div>
<div id="pca-in-r" class="section level2">
<h2><span class="header-section-number">13.3</span> PCA in <code>R</code></h2>
<div id="using-the-palmerpenguins-data" class="section level3">
<h3><span class="header-section-number">13.3.1</span> Using the <code>palmerpenguins</code> data</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## getting rid of NAs
penguins_nafree &lt;-<span class="st"> </span>penguins <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">drop_na</span>()</code></pre></div>
<p>When carrying out PCA we're only interested in numeric variables, so let's just plot those. We can use the piping operator <code>%&gt;%</code> to do this with out creating a new data frame</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(GGally)
penguins_nafree <span class="op">%&gt;%</span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(species, <span class="kw">where</span>(is.numeric)) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">ggpairs</span>(<span class="kw">aes</span>(<span class="dt">color =</span> species),
        <span class="dt">columns =</span> <span class="kw">c</span>(<span class="st">&quot;flipper_length_mm&quot;</span>, <span class="st">&quot;body_mass_g&quot;</span>, 
                     <span class="st">&quot;bill_length_mm&quot;</span>, <span class="st">&quot;bill_depth_mm&quot;</span>)) </code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-115-1.png" width="672" /></p>
<p><strong>Using <code>prcomp()</code></strong></p>
<p>There are three basic types of information we obtain from Principal Component Analysis:</p>
<ul>
<li><p><strong>PC scores:</strong> the coordinates of our samples on the new PC axis: the new uncorrelated variables (stored in <code>pca$x</code>)</p></li>
<li><p><strong>Eigenvalues:</strong> (see above) represent the variance explained by each PC; we can use these to calculate the proportion of variance in the original data that each axis explains</p></li>
<li><p><strong>Variable loadings</strong> (eigenvectors): these reflect the weight that each variable has on a particular PC and can be thought of as the correlation between the PC and the original variable</p></li>
</ul>
<p>Before we carry out PCA we <strong>should</strong> scale out data. <strong>WHY?</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pca &lt;-<span class="st"> </span>penguins_nafree <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric), <span class="op">-</span>year) <span class="op">%&gt;%</span><span class="st"> </span>## year makes no sense here so we remove it and keep the other numeric variables
<span class="st">  </span><span class="kw">scale</span>() <span class="op">%&gt;%</span><span class="st"> </span>## scale the variables
<span class="st">  </span><span class="kw">prcomp</span>()
## print out a summary
<span class="kw">summary</span>(pca)</code></pre></div>
<pre><code>## Importance of components:
##                           PC1    PC2     PC3     PC4
## Standard deviation     1.6569 0.8821 0.60716 0.32846
## Proportion of Variance 0.6863 0.1945 0.09216 0.02697
## Cumulative Proportion  0.6863 0.8809 0.97303 1.00000</code></pre>
<p>This output tells us that we obtain 4 principal components, which are called <code>PC1</code> <code>PC2</code>, <code>PC3</code>, and <code>PC4</code> (this is as expected because we used the 4 original numeric variables!). Each of these <code>PC</code>s explains a percentage of the total variation (<code>Proportion of Variance</code>) in the dataset:</p>
<ul>
<li><code>PC1</code> explains <span class="math inline">\(\sim\)</span> 68% of the total variance, which means that just over half of the information in the dataset (5 variables) can be encapsulated by just that one Principal Component.</li>
<li><code>PC2</code> explains <span class="math inline">\(\sim\)</span> 19% of the variance.</li>
<li><code>PC3</code> explains <span class="math inline">\(\sim\)</span> 9% of the variance.</li>
<li><code>PC4</code> explains <span class="math inline">\(\sim\)</span> 2% of the variance.</li>
</ul>
<p>From the <code>Cumulative Proportion</code> row we see that by knowing the position of a sample in relation to just <code>PC1</code> and <code>PC2</code> we can get a pretty accurate view on where it stands in relation to other samples, as just <code>PC1</code> and <code>PC2</code> explain 88% of the variance.</p>
<p>The <strong>loadings</strong> (<em>relationship</em>) between the initial variables and the principal components are stored in <code>pca$rotation</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pca<span class="op">$</span>rotation</code></pre></div>
<pre><code>##                          PC1         PC2        PC3        PC4
## bill_length_mm     0.4537532 -0.60019490 -0.6424951  0.1451695
## bill_depth_mm     -0.3990472 -0.79616951  0.4258004 -0.1599044
## flipper_length_mm  0.5768250 -0.00578817  0.2360952 -0.7819837
## body_mass_g        0.5496747 -0.07646366  0.5917374  0.5846861</code></pre>
<p>Here we can see that <code>bill_length_mm</code> has a strong positive relationship with <code>PC1</code>, whereas <code>bill_depth_mm</code> has a strong negative relationship. Both <code>fliper_length_mm</code> and <code>body_mass_g</code> also have a strong positive relationship with <code>PC1</code>.</p>
<p>Plotting this we get</p>
<p><img src="_main_files/figure-html/unnamed-chunk-118-1.png" width="672" /></p>
<p>The new variables (PCs) are stored in <code>pca$x</code>, lets plot some of them alongside the loadings using a <em>biplot</em>. For <code>PC1</code> vs <code>PC2</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(factoextra) ## install this package first
<span class="kw">fviz_pca_biplot</span>(pca, <span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span> (<span class="dt">alpha =</span> <span class="fl">0.2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-119-1.png" width="672" /></p>
<p>Now for <code>PC2</code> vs <code>PC3</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fviz_pca_biplot</span>(pca, <span class="dt">axes =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">3</span>),<span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span> (<span class="dt">alpha =</span> <span class="fl">0.2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-120-1.png" width="672" /></p>
<p><strong>But how many PCs (new variables) do we keep?</strong> The whole point of this exercise is to <strong>reduce</strong> the number of variables we need to explain the variation in our data. So how many of these new variables (PCs) do we keep?</p>
<p>To assess this we can use the information printed above alongside a <em>screeplot</em>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fviz_screeplot</span>(pca)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-121-1.png" width="672" /></p>
<p><strong>Principal components from the original variables</strong></p>
<p>Recall that the principal components are a linear combination of the (statndardised) variables. So for PC1</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">loadings1 &lt;-<span class="st"> </span>pca<span class="op">$</span>rotation[,<span class="dv">1</span>]
loadings1</code></pre></div>
<pre><code>##    bill_length_mm     bill_depth_mm flipper_length_mm       body_mass_g 
##         0.4537532        -0.3990472         0.5768250         0.5496747</code></pre>
<p>Therefore, the first Principle Component will be <span class="math inline">\(0.454\times Z1 -0.399 \times Z2 + 0.5768 \times Z3 + 0.5497 \times Z3\)</span> where <span class="math inline">\(Z1\)</span>, <span class="math inline">\(Z2\)</span>, <span class="math inline">\(Z3\)</span>. and <span class="math inline">\(Z4\)</span> are the scaled numerical variables form the penguins dataset (i.e., bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g). To compute this we use <code>R</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">scaled_vars &lt;-<span class="st"> </span>penguins_nafree <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric), <span class="op">-</span>year) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">scale</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">as_tibble</span>()
## By &quot;Hand&quot;
by_hand &lt;-<span class="st"> </span>loadings1[<span class="dv">1</span>]<span class="op">*</span>scaled_vars<span class="op">$</span><span class="st">&quot;bill_length_mm&quot;</span> <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>loadings1[<span class="dv">2</span>]<span class="op">*</span>scaled_vars<span class="op">$</span><span class="st">&quot;bill_depth_mm&quot;</span> <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>loadings1[<span class="dv">3</span>]<span class="op">*</span>scaled_vars<span class="op">$</span><span class="st">&quot;flipper_length_mm&quot;</span> <span class="op">+</span><span class="st"> </span>
<span class="st">  </span>loadings1[<span class="dv">4</span>]<span class="op">*</span>scaled_vars<span class="op">$</span><span class="st">&quot;body_mass_g&quot;</span>
## From PCA
pc1 &lt;-<span class="st"> </span>pca<span class="op">$</span>x[,<span class="dv">1</span>]
<span class="kw">plot</span>(by_hand,pc1)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-123-1.png" width="672" /></p>
</div>
<div id="athletes" class="section level3">
<h3><span class="header-section-number">13.3.2</span> Athletes</h3>
<p>You'll find the <code>athletes.csv</code> file on CANVAS.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">athletes &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;athletes.csv&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">athletes</code></pre></div>
<pre><code>## # A tibble: 33 x 10
##     m100  long weight highj  m400  m110  disc  pole javel m1500
##    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  11.2  7.43   15.5  2.27  48.9  15.1  49.3   4.7  61.3  269.
##  2  10.9  7.45   15.0  1.97  47.7  14.5  44.4   5.1  61.8  273.
##  3  11.2  7.44   14.2  1.97  48.3  14.8  43.7   5.2  64.2  263.
##  4  10.6  7.38   15.0  2.03  49.1  14.7  44.8   4.9  64.0  285.
##  5  11.0  7.43   12.9  1.97  47.4  14.4  41.2   5.2  57.5  257.
##  6  10.8  7.72   13.6  2.12  48.3  14.2  43.1   4.9  52.2  274.
##  7  11.2  7.05   14.1  2.06  49.3  14.4  41.7   5.7  61.6  291.
##  8  11.0  6.95   15.3  2     48.2  14.4  41.3   4.8  63    266.
##  9  11.2  7.12   14.5  2.03  49.2  14.7  42.4   4.9  66.5  270.
## 10  11.2  7.28   15.2  1.97  48.6  14.8  48.0   5.2  59.5  292.
## # … with 23 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">athletes <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggpairs</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-126-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corrplot<span class="op">::</span><span class="kw">corrplot</span>(<span class="kw">cor</span>(athletes), <span class="dt">method =</span> <span class="st">&quot;ellipse&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;upper&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-126-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pca &lt;-<span class="st"> </span>athletes <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">scale</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">prcomp</span>()
<span class="kw">summary</span>(pca)</code></pre></div>
<pre><code>## Importance of components:
##                           PC1    PC2     PC3    PC4     PC5     PC6     PC7
## Standard deviation     1.8488 1.6144 0.97123 0.9370 0.74607 0.70088 0.65620
## Proportion of Variance 0.3418 0.2606 0.09433 0.0878 0.05566 0.04912 0.04306
## Cumulative Proportion  0.3418 0.6025 0.69679 0.7846 0.84026 0.88938 0.93244
##                            PC8     PC9    PC10
## Standard deviation     0.55389 0.51667 0.31915
## Proportion of Variance 0.03068 0.02669 0.01019
## Cumulative Proportion  0.96312 0.98981 1.00000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## standard deviations of newly rotated variables
pca<span class="op">$</span>sdev</code></pre></div>
<pre><code>##  [1] 1.8488478 1.6144328 0.9712345 0.9370279 0.7460742 0.7008762 0.6561975
##  [8] 0.5538936 0.5166715 0.3191460</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## p = 10 variables
<span class="kw">sum</span>(pca<span class="op">$</span>sdev<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 10</code></pre>
<p><strong>screeplot</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## screeplot of sdev^2
<span class="kw">fviz_screeplot</span>(pca, <span class="dt">choice =</span> <span class="st">&quot;eigenvalue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-128-1.png" width="672" /></p>
<p><strong>biplots</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fviz_pca_biplot</span>(pca,<span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span> (<span class="dt">alpha =</span> <span class="fl">0.2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-129-1.png" width="672" /></p>
<ul>
<li>discus, shot, &amp; javelin more strongly correlated with one another</li>
<li>running events more strongly correlated to one another</li>
<li>could think of PC1 as a <em>fieldness</em> variable (i.e., strong +ve loadings from field events and -ve loadings from track events)</li>
</ul>
<p><strong>Finding correlation</strong> between a PC and the original variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pca<span class="op">$</span>rotation <span class="op">%*%</span><span class="st"> </span><span class="kw">diag</span>(pca<span class="op">$</span>sdev)</code></pre></div>
<pre><code>##              [,1]        [,2]        [,3]        [,4]         [,5]        [,6]
## m100   -0.7689031  0.24024073 -0.25977801  0.08276995 -0.329999387  0.02152557
## long    0.7285412 -0.24552536 -0.16408953  0.22886871  0.275237129 -0.06572987
## weight  0.4975355  0.78063857  0.09569838  0.10097671 -0.007277715  0.16121594
## highj   0.3924767  0.04504025 -0.83039242 -0.36351428 -0.001399867  0.05224598
## m400   -0.6579077  0.56853834 -0.18404546 -0.07550062  0.109647051 -0.22913668
## m110   -0.8014415  0.11231318 -0.12253105  0.35821666 -0.066253470  0.14752835
## disc    0.3250132  0.81260004  0.04477360 -0.02397295  0.014442957  0.43097750
## pole    0.7101094  0.24149011  0.13293514 -0.13489967 -0.534743786 -0.24373698
## javel   0.3326883  0.60049956 -0.18679561  0.56265307  0.071311293 -0.30659402
## m1500  -0.3145678  0.67962013  0.21615050 -0.45506038  0.253495250 -0.21049009
##               [,7]         [,8]         [,9]       [,10]
## m100    0.16693567 -0.367626287  0.056004765 -0.03494024
## long    0.49249877 -0.078245304 -0.023838755 -0.01780972
## weight -0.07261722 -0.040160366 -0.218281354 -0.20767995
## highj  -0.08866817  0.086094934  0.052734102 -0.03810980
## m400    0.09274620  0.081333350 -0.336230314  0.10749282
## m110    0.17883327  0.353939993  0.107074242 -0.08288795
## disc    0.09447447 -0.005206846  0.086408421  0.17058453
## pole    0.17931681  0.153358210  0.009126707  0.02103035
## javel  -0.22436043 -0.032413502  0.158202825  0.04178638
## m1500   0.12262390 -0.004048987  0.236058037 -0.07759028</code></pre>
</div>
<div id="ants-from-previous-chapter" class="section level3">
<h3><span class="header-section-number">13.3.3</span> Ants (from previous chapter)</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ants &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;pitfalls.csv&quot;</span>)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## choose numeric variables only and transform
ants_numeric &lt;-<span class="st"> </span>ants <span class="op">%&gt;%</span>
<span class="st">  </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">where</span>(is.numeric), <span class="op">-</span>Month) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(
  <span class="dt">Nyl =</span> <span class="kw">log</span>(Nyl <span class="op">+</span><span class="st"> </span><span class="dv">1</span>),
  <span class="dt">Phe =</span> <span class="kw">log</span>(Phe <span class="op">+</span><span class="st"> </span><span class="dv">1</span>),
  <span class="dt">Tet =</span> <span class="kw">log</span>(Tet <span class="op">+</span><span class="st"> </span><span class="dv">1</span>),
  <span class="dt">Pac =</span> <span class="kw">log</span>(Pac <span class="op">+</span><span class="st"> </span><span class="dv">1</span>))


corrplot<span class="op">::</span><span class="kw">corrplot</span>(<span class="kw">cor</span>(ants_numeric), <span class="dt">method =</span> <span class="st">&quot;ellipse&quot;</span>,<span class="dt">type =</span> <span class="st">&quot;upper&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-133-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pca &lt;-<span class="st"> </span>ants_numeric <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">scale</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">prcomp</span>()
<span class="kw">summary</span>(pca)</code></pre></div>
<pre><code>## Importance of components:
##                           PC1    PC2    PC3     PC4
## Standard deviation     1.5517 0.8361 0.7611 0.56041
## Proportion of Variance 0.6019 0.1747 0.1448 0.07852
## Cumulative Proportion  0.6019 0.7767 0.9215 1.00000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## screeplot of sdev^2
<span class="kw">fviz_screeplot</span>(pca, <span class="dt">choice =</span> <span class="st">&quot;eigenvalue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-134-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## reduced space plot (biplot)
<span class="kw">fviz_pca_biplot</span>(pca,<span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span> (<span class="dt">alpha =</span> <span class="fl">0.2</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-134-2.png" width="672" /></p>
<ul>
<li><code>Phe</code> and <code>Nyl</code> strongly positively correlated</li>
<li>PC2 has a large contribution from <code>Tet</code></li>
</ul>
<p><strong>Additional information</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fviz_pca_biplot</span>(pca,<span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>,<span class="dt">alpha =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> ants<span class="op">$</span>Location)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">color =</span> <span class="st">&quot;Location&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-135-1.png" width="672" /></p>
<ul>
<li>Central different from North and West?</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fviz_pca_biplot</span>(pca,<span class="dt">geom =</span> <span class="st">&quot;point&quot;</span>,<span class="dt">alpha =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">      </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">color =</span> ants<span class="op">$</span>Habitat)) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">color =</span> <span class="st">&quot;Habitat&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-136-1.png" width="672" /></p>
<ul>
<li>Grass and Scrub intermediate?</li>
</ul>
</div>
</div>
<div id="reality-check-reducing-noise..." class="section level2">
<h2><span class="header-section-number">13.4</span> Reality check: reducing noise...</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1234</span>) ## just for reproduciblity
noise &lt;-<span class="st"> </span><span class="kw">as_tibble</span>(<span class="kw">replicate</span>(<span class="dv">10</span>,<span class="kw">rnorm</span>(<span class="dv">200</span>, <span class="dt">mean =</span> <span class="dv">50</span>, <span class="dt">sd =</span> <span class="dv">10</span>)))
noise</code></pre></div>
<pre><code>## # A tibble: 200 x 10
##       V1    V2    V3    V4    V5    V6    V7    V8    V9   V10
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  37.9  54.9  37.7  53.1  39.8  37.9  36.0  29.9  47.5  44.7
##  2  52.8  57.0  50.4  56.1  36.1  53.0  73.8  34.4  37.8  45.0
##  3  60.8  51.9  45.8  33.1  49.5  34.6  58.7  69.6  49.3  38.5
##  4  26.5  57.0  41.0  57.8  68.1  56.4  34.6  48.2  63.6  51.3
##  5  54.3  53.1  54.2  50.1  49.0  57.0  61.3  63.6  45.4  54.7
##  6  55.1  57.6  51.5  48.2  57.8  30.9  60.4  66.5  50.7  48.1
##  7  44.3  68.4  64.6  61.1  39.0  59.4  55.9  51.2  57.8  33.8
##  8  44.5  61.1  38.8  64.8  47.8  47.8  54.0  50.0  34.1  46.0
##  9  44.4  50.3  44.8  38.5  55.7  43.3  51.4  52.0  36.3  54.1
## 10  41.1  38.9  49.3  60.1  46.5  54.5  56.2  56.8  40.7  42.8
## # … with 190 more rows</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">corrplot<span class="op">::</span><span class="kw">corrplot</span>(<span class="kw">cor</span>(noise), <span class="dt">method =</span> <span class="st">&quot;ellipse&quot;</span>,<span class="dt">type =</span> <span class="st">&quot;upper&quot;</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-137-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pca &lt;-<span class="st"> </span>noise <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">scale</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">prcomp</span>()
<span class="kw">summary</span>(pca)</code></pre></div>
<pre><code>## Importance of components:
##                           PC1    PC2    PC3    PC4    PC5     PC6     PC7
## Standard deviation     1.1890 1.1331 1.0936 1.0281 1.0075 0.96654 0.94742
## Proportion of Variance 0.1414 0.1284 0.1196 0.1057 0.1015 0.09342 0.08976
## Cumulative Proportion  0.1414 0.2698 0.3894 0.4951 0.5966 0.68998 0.77974
##                            PC8     PC9    PC10
## Standard deviation     0.90017 0.85665 0.81141
## Proportion of Variance 0.08103 0.07339 0.06584
## Cumulative Proportion  0.86078 0.93416 1.00000</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">fviz_screeplot</span>(pca, <span class="dt">choice =</span> <span class="st">&quot;eigenvalue&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-139-1.png" width="672" /></p>
</div>
<div id="other-resources-optional-but-recommended-2" class="section level2">
<h2><span class="header-section-number">13.5</span> Other resources: optional but recommended</h2>
<ul>
<li><p><a href="https://cmjt.github.io/statbiscuits/clusterducks.html">ClusterDucks</a></p></li>
<li><p><a href="https://little-book-of-r-for-multivariate-analysis.readthedocs.io/en/latest/index.html">Little book for Multivariate Analysis</a></p></li>
<li><p><a href="https://juba.github.io/explor/">'explor' is an R package to allow interactive exploration of multivariate analysis results</a></p></li>
<li><p><a href="https://towardsdatascience.com/the-mathematics-behind-principal-component-analysis-fff2d7f4b643">The Mathematics Behind Principal Component Analysis (6 min read)</a></p></li>
</ul>
<div id="multidimensional-scaling-in-r" class="section level3">
<h3><span class="header-section-number">13.5.1</span> Multidimensional Scaling in <code>R</code></h3>
<p>Multidimensional scaling (MDS) is actually the more general technique of dimension reduction. PCA is a special case of MDS!</p>
<p>To carry out MDS in <code>R</code></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ggfortify)
## Plotting Multidimensional Scaling (for interest)
## stats::cmdscale performs Classical MDS
<span class="kw">data</span>(<span class="st">&quot;eurodist&quot;</span>) ## road distances (in km) between 21 cities in Europe.
<span class="kw">autoplot</span>(eurodist)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-140-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Plotting Classical (Metric) Multidimensional Scaling
<span class="kw">autoplot</span>(<span class="kw">cmdscale</span>(eurodist, <span class="dt">eig =</span> <span class="ot">TRUE</span>))</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-140-2.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">autoplot</span>(<span class="kw">cmdscale</span>(eurodist, <span class="dt">eig =</span> <span class="ot">TRUE</span>), <span class="dt">label =</span> <span class="ot">TRUE</span>, <span class="dt">shape =</span> <span class="ot">FALSE</span>,
         <span class="dt">label.size =</span> <span class="dv">3</span>)</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-140-3.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Plotting Non-metric Multidimensional Scaling
## MASS::isoMDS and MASS::sammon perform Non-metric MDS
<span class="kw">library</span>(MASS)
<span class="kw">autoplot</span>(<span class="kw">sammon</span>(eurodist))</code></pre></div>
<pre><code>## Initial stress        : 0.01705
## stress after  10 iters: 0.00951, magic = 0.500
## stress after  20 iters: 0.00941, magic = 0.500</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-140-4.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">autoplot</span>(<span class="kw">sammon</span>(eurodist), <span class="dt">shape =</span> <span class="ot">FALSE</span>, <span class="dt">label =</span> <span class="ot">TRUE</span>,<span class="dt">label.size =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>## Initial stress        : 0.01705
## stress after  10 iters: 0.00951, magic = 0.500
## stress after  20 iters: 0.00941, magic = 0.500</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-140-5.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Have a go at interpreting these plots based on the geography of the cities :-)</code></pre></div>

</div>
</div>
</div>






            </section>

          </div>
        </div>
      </div>
<a href="multivariate-data-methods.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
