<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Introduction to the design and analysis of experiments | bluebook BIOSCI738</title>
  <meta name="description" content="4 Introduction to the design and analysis of experiments | bluebook BIOSCI738" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Introduction to the design and analysis of experiments | bluebook BIOSCI738" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Introduction to the design and analysis of experiments | bluebook BIOSCI738" />
  
  
  

<meta name="author" content="Charlotte Jones-Todd" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-wrangling-and-vizualisation.html"/>
<link rel="next" href="multiple-comparisons-and-more-designs.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="src/my-style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#course-overview"><i class="fa fa-check"></i><b>0.1</b> Course Overview</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#key-topics"><i class="fa fa-check"></i><b>0.2</b> Key Topics</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html"><i class="fa fa-check"></i><b>1</b> <code>R</code>, <code>RStudio</code>, and <code>git</code></a><ul>
<li class="chapter" data-level="1.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#learning-objectives"><i class="fa fa-check"></i><b>1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="1.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#intro-to-r-rstudio"><i class="fa fa-check"></i><b>1.2</b> Intro to <code>R</code> &amp; <code>RStudio</code></a><ul>
<li class="chapter" data-level="1.2.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#why"><i class="fa fa-check"></i><b>1.2.1</b> Why?</a></li>
<li class="chapter" data-level="1.2.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>1.2.2</b> Installing R and RStudio</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#getting-started"><i class="fa fa-check"></i><b>1.3</b> Getting started</a><ul>
<li class="chapter" data-level="1.3.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#r-errors"><i class="fa fa-check"></i><b>1.3.1</b> R errors 😱</a></li>
<li class="chapter" data-level="1.3.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#r-scripts-a-.r-file"><i class="fa fa-check"></i><b>1.3.2</b> R <em>Script</em>s (a <code>.r</code> file)</a></li>
<li class="chapter" data-level="1.3.3" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#writing-comments"><i class="fa fa-check"></i><b>1.3.3</b> Writing <em>Comments</em></a></li>
<li class="chapter" data-level="1.3.4" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#change-the-rstudio-appearance-up-to-your-taste"><i class="fa fa-check"></i><b>1.3.4</b> Change the <code>RStudio</code> appearance up to your taste</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#reproducible-research"><i class="fa fa-check"></i><b>1.4</b> Reproducible research</a><ul>
<li class="chapter" data-level="1.4.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#good-practice"><i class="fa fa-check"></i><b>1.4.1</b> Good practice</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#version-control-with-git-and-github"><i class="fa fa-check"></i><b>1.5</b> Version control with <code>git</code> and GitHub</a><ul>
<li class="chapter" data-level="1.5.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#setup-tldr"><i class="fa fa-check"></i><b>1.5.1</b> Setup TL;DR</a></li>
<li class="chapter" data-level="1.5.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#cloning-a-repository-from-github-using-rstudio"><i class="fa fa-check"></i><b>1.5.2</b> Cloning a repository from <code>GitHub</code> using <code>RStudio</code></a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>1.6</b> Exploratory Data Analysis</a><ul>
<li class="chapter" data-level="1.6.1" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#starting-out-with-tidyverse"><i class="fa fa-check"></i><b>1.6.1</b> Starting out with <code>tidyverse</code></a></li>
<li class="chapter" data-level="1.6.2" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#reading-in-data-from-a-.csv-file"><i class="fa fa-check"></i><b>1.6.2</b> Reading in data from a <code>.csv</code> file</a></li>
<li class="chapter" data-level="1.6.3" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#explore-your-data"><i class="fa fa-check"></i><b>1.6.3</b> Explore your data</a></li>
<li class="chapter" data-level="1.6.4" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#the-pipe-operator"><i class="fa fa-check"></i><b>1.6.4</b> The pipe operator <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="r-rstudio-and-git.html"><a href="r-rstudio-and-git.html#other-resources"><i class="fa fa-check"></i><b>1.7</b> Other resources</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html"><i class="fa fa-check"></i><b>2</b> Māori Data Sovereignty principles</a><ul>
<li class="chapter" data-level="2.1" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#learning-objectives-1"><i class="fa fa-check"></i><b>2.1</b> Learning objectives</a></li>
<li class="chapter" data-level="2.2" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#māori-data-sovereignty-principles-1"><i class="fa fa-check"></i><b>2.2</b> Māori Data Sovereignty principles</a></li>
<li class="chapter" data-level="2.3" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#māori-data-sovereignty-principles-2"><i class="fa fa-check"></i><b>2.3</b> Māori Data Sovereignty principles</a></li>
<li class="chapter" data-level="2.4" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html#resources"><i class="fa fa-check"></i><b>2.4</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html"><i class="fa fa-check"></i><b>3</b> Data wrangling and vizualisation</a><ul>
<li class="chapter" data-level="3.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#learning-objectives-2"><i class="fa fa-check"></i><b>3.1</b> Learning objectives</a></li>
<li class="chapter" data-level="3.2" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#common-dataframe-manipulations-in-the-tidyverse"><i class="fa fa-check"></i><b>3.2</b> Common dataframe manipulations in the <code>tidyverse</code></a><ul>
<li class="chapter" data-level="3.2.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#using-dplyr-and-tidyr"><i class="fa fa-check"></i><b>3.2.1</b> Using <code>dplyr</code> and <code>tidyr</code></a></li>
<li class="chapter" data-level="3.2.2" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#introuducing-the-palmer-penguins"><i class="fa fa-check"></i><b>3.2.2</b> Introuducing the <span>Palmer penguins</span></a></li>
<li class="chapter" data-level="3.2.3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#common-dataframe-manipulations-in-the-tidyverse-using-dplyr-and-tidyr"><i class="fa fa-check"></i><b>3.2.3</b> Common dataframe manipulations in the <code>tidyverse</code>, using <code>dplyr</code> and <code>tidyr</code></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#data-viz"><i class="fa fa-check"></i><b>3.3</b> Data Viz</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#exploratory-and-explanatory-plots"><i class="fa fa-check"></i><b>3.3.1</b> Exploratory and explanatory plots</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#ten-simple-rules-for-better-figures"><i class="fa fa-check"></i><b>3.4</b> Ten Simple Rules for Better Figures</a></li>
<li class="chapter" data-level="3.5" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#ggplot2"><i class="fa fa-check"></i><b>3.5</b> <code>ggplot2</code></a><ul>
<li class="chapter" data-level="3.5.1" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#ggplot2-layers"><i class="fa fa-check"></i><b>3.5.1</b> <code>ggplot2</code> layers</a></li>
<li class="chapter" data-level="3.5.2" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#examples"><i class="fa fa-check"></i><b>3.5.2</b> Examples</a></li>
<li class="chapter" data-level="3.5.3" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#the-good-the-bad-and-the-ugly"><i class="fa fa-check"></i><b>3.5.3</b> The Good, the Bad, and the Ugly…</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="data-wrangling-and-vizualisation.html"><a href="data-wrangling-and-vizualisation.html#resources-1"><i class="fa fa-check"></i><b>3.6</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html"><i class="fa fa-check"></i><b>4</b> Introduction to the design and analysis of experiments</a><ul>
<li class="chapter" data-level="4.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#learning-objectives-3"><i class="fa fa-check"></i><b>4.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#key-phrases"><i class="fa fa-check"></i><b>4.2</b> Key phrases</a></li>
<li class="chapter" data-level="4.3" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#three-key-principles"><i class="fa fa-check"></i><b>4.3</b> Three key principles:</a><ul>
<li class="chapter" data-level="4.3.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#replication"><i class="fa fa-check"></i><b>4.3.1</b> <strong>Replication</strong></a></li>
<li class="chapter" data-level="4.3.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#randomization"><i class="fa fa-check"></i><b>4.3.2</b> <strong>Randomization</strong></a></li>
<li class="chapter" data-level="4.3.3" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#blocking"><i class="fa fa-check"></i><b>4.3.3</b> <strong>Blocking</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#one-way-analysis-of-variance-anova"><i class="fa fa-check"></i><b>4.4</b> One-Way <strong>An</strong>alysis <strong>o</strong>f <strong>Va</strong>riance (ANOVA)</a><ul>
<li class="chapter" data-level="4.4.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#between-group-ss-ssb"><i class="fa fa-check"></i><b>4.4.1</b> Between group SS (SSB)</a></li>
<li class="chapter" data-level="4.4.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#within-group-ss-ssw"><i class="fa fa-check"></i><b>4.4.2</b> Within group SS (SSW)</a></li>
<li class="chapter" data-level="4.4.3" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#f-statistic"><i class="fa fa-check"></i><b>4.4.3</b> F-statistic</a></li>
<li class="chapter" data-level="4.4.4" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#degrees-of-freedom-df"><i class="fa fa-check"></i><b>4.4.4</b> Degrees of freedom (DF)</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#analysis-of-a-completely-randomised-design-in-r-aov-and-lm"><i class="fa fa-check"></i><b>4.5</b> Analysis of a Completely Randomised Design in <code>R</code>: <code>aov()</code> and <code>lm()</code></a><ul>
<li class="chapter" data-level="4.5.1" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#aov"><i class="fa fa-check"></i><b>4.5.1</b> <code>aov()</code></a></li>
<li class="chapter" data-level="4.5.2" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#lm"><i class="fa fa-check"></i><b>4.5.2</b> <code>lm()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#p-values"><i class="fa fa-check"></i><b>4.6</b> 😱 p-values 😱</a></li>
<li class="chapter" data-level="4.7" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#terminology-and-issues"><i class="fa fa-check"></i><b>4.7</b> Terminology and issues</a></li>
<li class="chapter" data-level="4.8" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#resources-2"><i class="fa fa-check"></i><b>4.8</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html"><i class="fa fa-check"></i><b>5</b> Multiple comparisons and more designs</a><ul>
<li class="chapter" data-level="5.1" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#learning-objectives-4"><i class="fa fa-check"></i><b>5.1</b> Learning objectives</a></li>
<li class="chapter" data-level="5.2" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#adjustments-for-multiple-testing"><i class="fa fa-check"></i><b>5.2</b> Adjustments for multiple testing</a><ul>
<li class="chapter" data-level="5.2.1" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#classification-of-multiple-hypothesis-tests"><i class="fa fa-check"></i><b>5.2.1</b> Classification of multiple hypothesis tests</a></li>
<li class="chapter" data-level="5.2.2" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#using-the-predictmeans-package"><i class="fa fa-check"></i><b>5.2.2</b> Using the <code>predictmeans</code> package</a></li>
<li class="chapter" data-level="5.2.3" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#multiple-comparison-procedures"><i class="fa fa-check"></i><b>5.2.3</b> Multiple comparison procedures</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#a-randomised-controlled-block-design-rcbd-in-r"><i class="fa fa-check"></i><b>5.3</b> A Randomised Controlled Block Design (RCBD) in <code>R</code></a></li>
<li class="chapter" data-level="5.4" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#factorial-experiments"><i class="fa fa-check"></i><b>5.4</b> Factorial experiments</a><ul>
<li class="chapter" data-level="5.4.1" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#equal-replications-balanced-design"><i class="fa fa-check"></i><b>5.4.1</b> Equal replications (balanced design)</a></li>
<li class="chapter" data-level="5.4.2" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#unqual-replications-unbalanced-design"><i class="fa fa-check"></i><b>5.4.2</b> Unqual replications (unbalanced design)</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="multiple-comparisons-and-more-designs.html"><a href="multiple-comparisons-and-more-designs.html#tldr-model-formula-syntax-in-r"><i class="fa fa-check"></i><b>5.5</b> TL;DR, Model formula syntax in <code>R</code></a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"><em>bluebook</em> BIOSCI738</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-the-design-and-analysis-of-experiments" class="section level1">
<h1><span class="header-section-number">4</span> Introduction to the design and analysis of experiments</h1>
<div id="learning-objectives-3" class="section level2">
<h2><span class="header-section-number">4.1</span> Learning Objectives</h2>
<ul>
<li><strong>Identify</strong> the following
<ul>
<li>experimental unit</li>
<li>observational units</li>
</ul></li>
<li><strong>List</strong> and <strong>describe</strong> the three main principals of experimental design
<ul>
<li>Randomization</li>
<li>Replication</li>
<li>Blocking</li>
</ul></li>
<li><strong>Calculate</strong> Sums of Squares (between and within groups) given the observations</li>
<li><strong>Define</strong> and <strong>state</strong> the appropriate degrees of freedom in a one-way ANOVA scenario</li>
<li><strong>Calculate</strong> the F-statistics given the appropriate Sums of Squares and degrees of freedom</li>
<li><strong>Interpret</strong> and <strong>discuss</strong> a given <em>p-value</em> in the context of a stated hypothesis test</li>
<li><strong>Explain</strong> between group and within group variation</li>
<li><strong>Describe</strong> a Completely Randomised (experimental) Design</li>
<li><strong>Carry</strong> out linear regression in <code>R</code> with one categorical explanatory variable (one-way ANOVA) and <strong>draw</strong> the appropriate inference</li>
<li><strong>Communicate</strong> statistical concepts and experimental outcomes clearly using language appropriate for both a <strong>scientific</strong> and <strong>non-scientific</strong> audience</li>
</ul>
</div>
<div id="key-phrases" class="section level2">
<h2><span class="header-section-number">4.2</span> Key phrases</h2>
<p><strong>Experimental unit</strong> Smallest portion of experimental material which is <em>independently</em> perturbed</p>
<p><strong>Treatment</strong> The experimental condition <em>independently</em> applied to an experimental unit</p>
<p><strong>Observational unit</strong> The smallest unit on which a response is measured. If one measurement is made on each rat: <strong>Observational unit</strong> = <strong>Experimental unit</strong>. If Multiple measurements are made on each rat: Each experimental unit has &gt;1 observational unit (<em>pseudo-</em> or <em>technical replication</em>).</p>
</div>
<div id="three-key-principles" class="section level2">
<h2><span class="header-section-number">4.3</span> Three key principles:</h2>
<div id="replication" class="section level3">
<h3><span class="header-section-number">4.3.1</span> <strong>Replication</strong></h3>
<ul>
<li><strong>Biological replication:</strong> each treatment is <em>independently</em> applied to each of several humans, animals or plants
<ul>
<li>To generalize results to population</li>
</ul></li>
<li><strong>Technical replication:</strong> two or more samples from the same biological source which are <em>independently</em> processed
<ul>
<li>Advantageous if processing steps introduce a lot of variation</li>
<li>Increases the precision with which comparisons of relative abundances between treatments are made</li>
</ul></li>
<li><strong>Pseudo-replication:</strong> one sample from the same biological source, divided into two or more aliquots which are <strong>independently</strong> measured
<ul>
<li>Advantageous for noisy measuring instruments</li>
<li>Increases the <strong>precision</strong> with which comparisons of relative abundances between treatments are made</li>
</ul></li>
</ul>
</div>
<div id="randomization" class="section level3">
<h3><span class="header-section-number">4.3.2</span> <strong>Randomization</strong></h3>
<ul>
<li><p><strong>Protects against bias</strong></p></li>
<li><p>Plan the experiment in such a way that the variations caused by extraneous factors can all be combined under the general heading of “chance”.</p></li>
<li>Ensures that each treatment has the same probability of getting good (or bad) units and thus
avoids systematic bias</li>
<li>random allocation can cancel out population bias; it ensures that any other possible causes for the experimental results are split equally between groups</li>
<li><p>typically statistical analysis assumes that observations are <strong>independent</strong>. This is almost never strictly true in practice but randomisation means that our estimates will behave as if they were based on independent observations</p></li>
</ul>
</div>
<div id="blocking" class="section level3">
<h3><span class="header-section-number">4.3.3</span> <strong>Blocking</strong></h3>
<ul>
<li><p>Blocking helps <strong>control variability</strong> by making treatment groups more alike. Experimental units are divided into subsets (called blocks) so that units within the same block are more similar than units from different subsets or blocks.</p></li>
<li><p>Blocking is a technique for dealing with <em>nuisance factors</em>. A <em>nuisance factor</em> is a factor that has some effect on the response, but is of no interest (e.g., age class).</p></li>
</ul>
</div>
</div>
<div id="one-way-analysis-of-variance-anova" class="section level2">
<h2><span class="header-section-number">4.4</span> One-Way <strong>An</strong>alysis <strong>o</strong>f <strong>Va</strong>riance (ANOVA)</h2>
<div id="between-group-ss-ssb" class="section level3">
<h3><span class="header-section-number">4.4.1</span> Between group SS (SSB)</h3>
<p><strong>The idea</strong>: Assess <strong>distances</strong> between treatment (<em>surgical condition</em>) means relative to our uncertainty about the actual (<em>true</em>) treatment means.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p><strong>add up the differences:</strong> -1.192 + -0.703 + 1.895 = 0. <strong>This is always the case!</strong></p>
<p><strong>So adding up the differences:</strong> -1.192 + -0.703 + 1.895 = 0. <strong>Not a great way to measure distances!</strong></p>
<p><strong>Sums of Squares?</strong></p>
<p>-1.192^2 + -0.703^2 + 1.895^2</p>
<p><strong>add up the squared differences?</strong> but… there are 4 observations in each group (treatment)</p>
<p>4<span class="math inline">\(\times\)</span>(-1.192)^2 + 4<span class="math inline">\(\times\)</span>(-0.703)^2 + 4<span class="math inline">\(\times\)</span>(1.895)^2</p>
<p>This is the <strong>Between Groups Sums of Squares</strong> or the <strong>Between group SS (SSB)</strong></p>
<p>So the Between group SS (SSB) = 22.02635</p>
<p><strong>Adding up the differences:</strong> -1.192 + -0.703 + 1.895 = 0. <strong>This is always the case</strong> and that itself gives us information…</p>
<p><strong>We only need to know two of the values to work out the third!</strong></p>
<p>So we have only 2 bits of <strong>unique</strong> information; <strong>SSB degrees of freedom</strong> = 2</p>
</div>
<div id="within-group-ss-ssw" class="section level3">
<h3><span class="header-section-number">4.4.2</span> Within group SS (SSW)</h3>
<p>The <strong>Within group SS (SSW)</strong> arises from the same idea:</p>
<p>To assess distances between treatment (surgical condition) means <strong>relative</strong> to our uncertainty about the actual (true) treatment means.</p>
<p>Procedure:</p>
<ul>
<li>Observation - Treatment mean</li>
<li>Square the difference</li>
<li>Add them up!</li>
</ul>
<p><strong>Within group SS (SSW)</strong> <em>unexplained variance</em></p>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="f-statistic" class="section level3">
<h3><span class="header-section-number">4.4.3</span> F-statistic</h3>
<p>Recall the Between group SS (<strong>SSB</strong>) = 22.02635</p>
<p>So mean <strong>SSB</strong> = 22.02635 / 2</p>
<p>The within group SS (<strong>SSW</strong>) = 6.059075</p>
<p>Here we have 3<span class="math inline">\(\times\)</span> 3 bits of <em>unique</em> information: within groups <strong>degrees of freedom</strong> is 9.</p>
<p>So mean <strong>SSW</strong> = 6.059/9</p>
<p>Consider the ratio <span class="math inline">\({\frac{{\text{variation due to treatments}}}{{\text{unexplained variance}}}} = {\frac{{\text{ mean between-group variability}}}{{\text{mean within-group variability}}}}\)</span> <span class="math inline">\(=\frac{\text{mean SSB}}{\text{mean SSW}}\)</span> <span class="math inline">\(=\frac{\text{MSB}}{\text{MSW}}\)</span> = <span class="math inline">\(=\frac{\text{experimental variance}}{\text{error variance}}\)</span> 16.3586975</p>
<p>This is the <strong>F-statistic!</strong></p>
</div>
<div id="degrees-of-freedom-df" class="section level3">
<h3><span class="header-section-number">4.4.4</span> Degrees of freedom (DF)</h3>
<p>Essentially <em>statistical currency</em> (i.e., <strong>unique</strong> bits of information). So in the example above we have 3 treatment groups and if we know the mean of two we know the third (i.e., 2 <em>unique</em> bits of info) so SSB df = 2. Now, for SSW df. We have 12 observations (4 in each group); we know the treatment means so if we have three of those observed values in each group we know the fourth: 12 - 3 = 9 (i.e., number of observations - number of df lost due to knowing the cell means).</p>
</div>
</div>
<div id="analysis-of-a-completely-randomised-design-in-r-aov-and-lm" class="section level2">
<h2><span class="header-section-number">4.5</span> Analysis of a Completely Randomised Design in <code>R</code>: <code>aov()</code> and <code>lm()</code></h2>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb53-2" title="2">rats &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;crd_rats_data.csv&quot;</span>)</a></code></pre></div>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1">rats <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb54-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(Surgery) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb54-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">avg =</span> <span class="kw">mean</span>(logAUC))</a></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   Surgery   avg
##   &lt;fct&gt;   &lt;dbl&gt;
## 1 C        8.46
## 2 P        8.95
## 3 S       11.5</code></pre>
<div id="aov" class="section level3">
<h3><span class="header-section-number">4.5.1</span> <code>aov()</code></h3>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1">rats_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(logAUC <span class="op">~</span><span class="st"> </span>Surgery, <span class="dt">data =</span> rats)</a>
<a class="sourceLine" id="cb56-2" title="2"><span class="kw">summary</span>(rats_aov)</a></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## Surgery      2 22.026  11.013   16.36 0.00101 **
## Residuals    9  6.059   0.673                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Inference</strong></p>
<p>Hypothesis: We test the Null hypothesis, <span class="math inline">\(H_0\)</span>, population (<code>Surgery</code>) means are the same on average verses the alternative hypothesis, <span class="math inline">\(H_1\)</span>, that <strong>at least one</strong> differs from the others!</p>
<p>Probability of getting an <strong>F-statistic</strong> at least as extreme as the one we observe (think of the area under the tails of the curve below) <strong>p-value</strong> Pr(&gt;F)= 0.001 tells us we have sufficient evidence to reject <span class="math inline">\(H_0\)</span> at the 1% level of significance</p>
<p><img src="_main_files/figure-html/f-1.png" width="672" /></p>
</div>
<div id="lm" class="section level3">
<h3><span class="header-section-number">4.5.2</span> <code>lm()</code></h3>
<p><code>lm()</code></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1">rats_lm &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Surgery, <span class="dt">data =</span> rats)</a></code></pre></div>
<p><strong>Inference</strong></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1"><span class="kw">summary</span>(rats_lm)<span class="op">$</span>coef</a></code></pre></div>
<pre><code>##             Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)   8.4600  0.4102531 20.6214144 6.930903e-09
## SurgeryP      0.4900  0.5801856  0.8445574 4.202408e-01
## SurgeryS      3.0875  0.5801856  5.3215734 4.799872e-04</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Which pairs of means are different?</p>
<ul>
<li>Pair-wise comparisons of means
<ul>
<li>Use two-sample t-tests</li>
<li>We need to calculate our <strong>observed</strong> t-value where
<span class="math inline">\(\text{t-value} = \frac{\text{Sample Difference}_{ij} - \text{Difference assuming } H_0 \text{ is true}_{ij}}{\text{SE of } \text{Sample Difference}_{ij}}\)</span>
where
<span class="math inline">\(\text{Sample Difference}_{ij}\)</span> = Difference between pair of sample means</li>
</ul></li>
<li>Compute the p-value for observed t-value</li>
</ul>
<p>(Intercept) = <span class="math inline">\(\text{mean}_C\)</span> = 8.46</p>
<p>SE of (Intercept) = SE of <span class="math inline">\(\text{mean}_C\)</span> = SEM = 0.4102531</p>
<p><span class="math inline">\(\text{Surgery}_P\)</span> = <span class="math inline">\(\text{mean}_P\)</span> – <span class="math inline">\(\text{mean}_C\)</span> = 0.49</p>
<p>SE of <span class="math inline">\(\text{Surgery}_P\)</span> = SE of (<span class="math inline">\(\text{mean}_P\)</span> - <span class="math inline">\(\text{mean}_C\)</span> ) = SED = 0.5801856</p>
<p><strong>Hypotheses being tested</strong></p>
<ul>
<li>The t value and Pr (&gt;|t|) are the t - and p-value for testing the null hypotheses:
<ul>
<li>Mean abundance is zero for C population</li>
<li>No difference between the population means of P and C</li>
<li>No difference between the population means of S and C</li>
</ul></li>
</ul>
<p>We’re interested in 2 and 3, but not necessarily 1!</p>
<p>Two-sample t -tests for pairwise comparisons of means</p>
<ul>
<li>SurgeryP : t value = Estimate ÷ Std.Error = 0.8446; Pr (&gt;|t|) = 0.4202</li>
</ul>
<p><strong>F-test:</strong></p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1"><span class="kw">anova</span>(rats_lm)</a></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##           Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
## Surgery    2 22.0263 11.0132  16.359 0.001006 **
## Residuals  9  6.0591  0.6732                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>The same as <code>aov()</code></strong> in fact <code>aov()</code> is calling <code>lm()</code> in the background.</p>
</div>
</div>
<div id="p-values" class="section level2">
<h2><span class="header-section-number">4.6</span> 😱 p-values 😱</h2>
<p><strong><a href="https://www.tandfonline.com/doi/full/10.1080/00031305.2016.1154108">The ASA Statement on p-Values: Context, Process, and Purpose</a></strong></p>
<blockquote>
“Good statistical practice, as an essential component of good scientific practice, emphasizes principles of good study design and conduct, a variety of numerical and graphical summaries of data, understanding of the phenomenon under study, interpretation of results in context, complete reporting and proper logical and quantitative understanding of what data summaries mean. No single index should substitute for scientific reasoning.”
<footer>
— ASA Statement on p-Values
</footer>
</blockquote>
<p><strong>What is a p-Value?</strong></p>
<p>Informally, a p-value is the probability under a specified statistical model that a statistical summary of the data (e.g., the sample mean difference between two compared groups) would be equal to or more extreme than its observed value</p>
<ul>
<li><p><strong>p-values</strong> can indicate how incompatible the data are with a specified statistical model</p></li>
<li><p>p-values <strong>do not</strong> measure the probability that the studied hypothesis is true, or the probability that the data were produced by random chance alone</p></li>
<li><p>Scientific conclusions and business or policy decisions <strong>should not</strong> be based only on whether a p-value passes a specific threshold</p></li>
<li><p>Proper inference requires <strong>full</strong> reporting and transparency</p></li>
<li><p>A p-value, or statistical significance, does <strong>not</strong> measure the size of an effect or the importance of a result</p></li>
<li><p>By itself, a p-value does <strong>not</strong> provide a good measure of evidence regarding a model or hypothesis</p></li>
</ul>
</div>
<div id="terminology-and-issues" class="section level2">
<h2><span class="header-section-number">4.7</span> Terminology and issues</h2>
<p><strong>Type I</strong> error (false positive): declare a difference (i.e., reject <span class="math inline">\(H_0\)</span>) when there is no difference (i.e. <span class="math inline">\(H_0\)</span> is true). Risk of the Type I error is determined by the <em>level of significance</em> (which we set!) (i.e., <span class="math inline">\(\alpha =\text{ P(Type I error)} = \text{P(false positive)}\)</span>.</p>
<p><img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/master/other-stats-artwork/type_1_errors.png" /></p>
<p><strong>Type II</strong> error (false negative): difference not declared (i.e., <span class="math inline">\(H_0\)</span> not rejected) when there is a difference (i.e., <span class="math inline">\(H_0\)</span> is false). Let <span class="math inline">\(\beta =\)</span> P(do not reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_0\)</span> is false); so, <span class="math inline">\(1-\beta\)</span> = P(reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_0\)</span> is false) = P(a true positive), which is the statistical <strong>power</strong> of the test.</p>
<p><img src="https://raw.githubusercontent.com/allisonhorst/stats-illustrations/master/other-stats-artwork/type_2_errors.png" /></p>
<p><strong>Each</strong> time we carry out a hypothesis test the probability we get a false positive result (type I error) is given by <span class="math inline">\(\alpha\)</span> (the <em>level of significance</em> we choose).</p>
<p>When we have <strong>multiple comparisons</strong> to make we should then control the <strong>Type I</strong> error rate across the entire <em>family</em> of tests under consideration, i.e., control the Family-Wise Error Rate (FWER); this ensures that the risk of making at least one <strong>Type I</strong> error among the family of comparisons in the experiment is <span class="math inline">\(\alpha\)</span>.</p>
<table>
<thead>
<tr class="header">
<th>State of Nature</th>
<th>Don’t reject <span class="math inline">\(H_0\)</span></th>
<th>reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> is true</td>
<td>✅</td>
<td>Type I error</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_0\)</span> is false</td>
<td>Type II error</td>
<td>✅</td>
</tr>
</tbody>
</table>
<div id="diagnostic-plots" class="section level4">
<h4><span class="header-section-number">4.7.0.1</span> Diagnostic plots</h4>
<p>Carrying out any linear regression we have some <strong>key assumptions</strong></p>
<ul>
<li><strong>Independence</strong></li>
<li>There is a <strong>linear relationship</strong> between the response and the explanatory variables</li>
<li>The residuals have <strong>constant variance</strong></li>
<li>The <strong>residuals</strong> are normally distributed</li>
</ul>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb63-1" title="1">gglm<span class="op">::</span><span class="kw">gglm</span>(rats_lm) <span class="co"># Plot the four main diagnostic plots</span></a></code></pre></div>
<p><img src="_main_files/figure-html/qqnorm-1.png" width="672" /></p>
<p><strong>Residuals vs Fitted</strong> plot</p>
<p>You are basically looking for no pattern or structure in your residuals (e.g., a “starry” night). You definitely don’t want to see is the scatter increasing around the zero line (dashed line) as the fitted values get bigger (e.g., think of a trumpet, a wedge of cheese, or even a slice of pizza) which would indicate unequal variances (heteroscedacity).</p>
<p><strong>Normal quantile-quantile (QQ)</strong> plot</p>
<p>This plot shows the sorted residuals versus expected order statistics from a standard normal distribution. Samples should be close to a line; points moving away from 45 degree line at the tails suggest the data are from a skewed distribution.</p>
<p><strong>Scale-Location</strong> plot (<span class="math inline">\(\sqrt{\text{|standardized residuals vs Fitted|}}\)</span>)</p>
<p>Another way to check the homoskedasticity (constant-variance) assumption. We want the line to be roughly horizontal. If this is the case then the average magnitude of the standardized residuals isn’t changing much as a function of the fitted values. We’d also like the spread around the line not to vary much with the fitted values; then the variability of magnitudes doesn’t vary much as a function of the fitted values.</p>
<p><strong>Residuals vs Leverage</strong> plot (standardized residuals vs Leverage)</p>
<p>This can help detect outliers in a linear regression model. For linear regression model leverage measures how sensitive a fitted value is to a change in the true response. We’re looking at how the spread of standardized residuals changes as the leverage. This can also be used to detect heteroskedasticity and non-linearity: the spread of standardized residuals shouldn’t change as a function of leverage. In addition, points with high leverage may be influential: that is, deleting them would change the model a lot.</p>
</div>
</div>
<div id="resources-2" class="section level2">
<h2><span class="header-section-number">4.8</span> Resources</h2>
<p><img src="https://pbs.twimg.com/media/EeMWb7QWsAIGftR?format=jpg&amp;name=small" /></p>
<p><strong>Looking forward</strong></p>
<table>
<colgroup>
<col width="44%" />
<col width="37%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th>Traditional name</th>
<th align="center">Model formula</th>
<th align="right">R code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple regression</td>
<td align="center"><span class="math inline">\(Y \sim X_{continuous}\)</span></td>
<td align="right"><code>lm(Y ~ X)</code></td>
</tr>
<tr class="even">
<td>One-way ANOVA</td>
<td align="center"><span class="math inline">\(Y \sim X_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X)</code></td>
</tr>
<tr class="odd">
<td>Two-way ANOVA</td>
<td align="center"><span class="math inline">\(Y \sim X1_{categorical} + X2_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X1 + X2)</code></td>
</tr>
<tr class="even">
<td>ANCOVA</td>
<td align="center"><span class="math inline">\(Y \sim X1_{continuous} + X2_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X1 + X2)</code></td>
</tr>
<tr class="odd">
<td>Multiple regression</td>
<td align="center"><span class="math inline">\(Y \sim X1_{continuous} + X2_{continuous}\)</span></td>
<td align="right"><code>lm(Y ~ X1 + X2)</code></td>
</tr>
<tr class="even">
<td>Factorial ANOVA</td>
<td align="center"><span class="math inline">\(Y \sim X1_{categorical} * X2_{categorical}\)</span></td>
<td align="right"><code>lm(Y ~ X1 * X2)</code> or <code>lm(Y ~ X1 + X2 + X1:X2)</code></td>
</tr>
</tbody>
</table>
<p><a href="https://catalogue.library.auckland.ac.nz/primo-explore/fulldisplay?docid=uoa_alma21237737730002091&amp;search_scope=Combined_Local&amp;tab=books&amp;vid=NEWUI&amp;context=L">Glass, David J. Experimental Design for Biologists. Second ed. 2014. Print.</a></p>
<p><a href="https://catalogue.library.auckland.ac.nz/primo-explore/fulldisplay?docid=uoa_alma21237737830002091&amp;search_scope=Combined_Local&amp;tab=books&amp;vid=NEWUI&amp;context=L">Welham, S. J. Statistical Methods in Biology : Design and Analysis of Experiments and Regression. 2015. Print.</a></p>
<p><a href="https://catalogue.library.auckland.ac.nz/primo-explore/fulldisplay?docid=uoa_alma21198532990002091&amp;context=L&amp;vid=NEWUI&amp;lang=en_US&amp;search_scope=Combined_Local&amp;adaptor=Local%20Search%20Engine&amp;isFrbr=true&amp;tab=books&amp;query=any,contains,The_Design_of_Experiments&amp;sortby=date&amp;facet=frbrgroupid,include,627497507&amp;offset=0">Fisher, Ronald Aylmer. The Design of Experiments. 8th ed. Edinburgh: Oliver &amp; Boyd, 1966. Print. O &amp; B Paperbacks.</a></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-wrangling-and-vizualisation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-comparisons-and-more-designs.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
