<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Linear mixed-effect models (LMMs) | Advanced Biological Data Analysis</title>
  <meta name="description" content="Linear mixed-effect models (LMMs) | Advanced Biological Data Analysis" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Linear mixed-effect models (LMMs) | Advanced Biological Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Linear mixed-effect models (LMMs) | Advanced Biological Data Analysis" />
  
  
  

<meta name="author" content="University of Auckland" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="multiple-comparisons.html"/>
<link rel="next" href="module-4.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Nau mai, haere mai. Welcome to BIOSCI 738</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html"><i class="fa fa-check"></i>Useful information to set you up for your semester</a><ul>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#course-outline"><i class="fa fa-check"></i>Course outline</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#learning-outcomes"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#course-summary"><i class="fa fa-check"></i>Course summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-1.html"><a href="module-1.html"><i class="fa fa-check"></i>Module 1</a><ul>
<li><a href="r-and-rstudio.html#r-and-rstudio"><code>R</code> and <code>RStudio</code></a><ul>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html"><i class="fa fa-check"></i>Installing R and RStudio</a></li>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#getting-started"><i class="fa fa-check"></i>Getting started</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html"><i class="fa fa-check"></i>Reproducible research</a><ul>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html#project-oriented-workflow-good-practice"><i class="fa fa-check"></i>Project-oriented workflow: good practice</a></li>
<li><a href="reproducible-research.html#version-control-with-git-and-github">Version control with <code>git</code> and GitHub</a></li>
</ul></li>
<li><a href="your-data-and-r.html#your-data-and-r">Your data and <code>R</code></a><ul>
<li><a href="your-data-and-r.html#reading-in-data-from-a-.csv-file">Reading in data from a <code>.csv</code> file</a></li>
<li class="chapter" data-level="" data-path="your-data-and-r.html"><a href="your-data-and-r.html"><i class="fa fa-check"></i>Explore your data</a></li>
<li><a href="your-data-and-r.html#the-pipe-operator">The pipe operator <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i>Data wrangling</a><ul>
<li><a href="data-wrangling.html#introuducing-the-palmer-penguins">Introuducing the <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081">Palmer penguins</a></a></li>
<li><a href="data-wrangling.html#common-dataframe-manipulations-in-the-tidyverse-using-dplyr-and-tidyr">Common dataframe manipulations in the <code>tidyverse</code>, using <code>dplyr</code> and <code>tidyr</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html"><i class="fa fa-check"></i>Data visualiation (data viz)</a><ul>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#exploratory-plots"><i class="fa fa-check"></i>Exploratory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#explanatory-plots"><i class="fa fa-check"></i>Explanatory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#ten-simple-rules-for-better-figures"><i class="fa fa-check"></i>Ten Simple Rules for Better Figures</a></li>
<li><a href="data-visualiation-data-viz.html#ggplot2"><code>ggplot2</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html"><i class="fa fa-check"></i>Māori Data Sovereignty principles</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-2.html"><a href="module-2.html"><i class="fa fa-check"></i>Module 2</a><ul>
<li class="chapter" data-level="" data-path="key-satistical-concepts.html"><a href="key-satistical-concepts.html"><i class="fa fa-check"></i>Key satistical concepts</a></li>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html"><i class="fa fa-check"></i>Bootstrap resampling</a><ul>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html#example-constructing-bootstrap-confidence-intervals"><i class="fa fa-check"></i>Example: constructing bootstrap confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html"><i class="fa fa-check"></i>Permutation and randomisation tests</a><ul>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html#a-permutation-test-jackal-mandible-lengths"><i class="fa fa-check"></i>A permutation test: Jackal mandible lengths</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resampling-procedures-the-differences.html"><a href="resampling-procedures-the-differences.html"><i class="fa fa-check"></i>Resampling procedures, the differences</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html"><i class="fa fa-check"></i>Hypothesis testing: key terms</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#p-values"><i class="fa fa-check"></i>😱 p-values 😱</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i>Type I and Type II errors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html"><i class="fa fa-check"></i>Parametric hypothesis tests</a><ul>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-sample-t-test"><i class="fa fa-check"></i>One-Sample t-test</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#differences-between-two-means"><i class="fa fa-check"></i>Differences between two means</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-way-analysis-of-variance-anova"><i class="fa fa-check"></i>One-Way Analysis of Variance (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i>Linear regression</a><ul>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#some-mathematical-notation"><i class="fa fa-check"></i>Some mathematical notation</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#modeling-bill-depth"><i class="fa fa-check"></i>Modeling Bill Depth</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#single-continuous-variable"><i class="fa fa-check"></i>Single continuous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#one-factor-and-a-continous-variable"><i class="fa fa-check"></i>One factor and a continous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li><a href="model-formula-syntax-in-r.html#model-formula-syntax-in-r">Model formula syntax in <code>R</code></a><ul>
<li class="chapter" data-level="" data-path="model-formula-syntax-in-r.html"><a href="model-formula-syntax-in-r.html"><i class="fa fa-check"></i>Other possible models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html"><i class="fa fa-check"></i>Model diagnostics for a linear model</a><ul>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#marginal-predictions"><i class="fa fa-check"></i>Marginal predictions</a></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#model-selection"><i class="fa fa-check"></i>Model selection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html"><i class="fa fa-check"></i>Inference for a linear model</a><ul>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#point-prediction"><i class="fa fa-check"></i>Point prediction</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#confidence-intervals-for-parameters"><i class="fa fa-check"></i>Confidence intervals for parameters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-3.html"><a href="module-3.html"><i class="fa fa-check"></i>Module 3</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html"><i class="fa fa-check"></i>Introduction to the design and analysis of experiments</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#key-phrases"><i class="fa fa-check"></i>Key phrases</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#the-three-key-principles"><i class="fa fa-check"></i>The three key principles:</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#replication"><i class="fa fa-check"></i>Replication</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#randomization"><i class="fa fa-check"></i>Randomization</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#blocking"><i class="fa fa-check"></i>Blocking</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#setting-up-an-experiment"><i class="fa fa-check"></i>Setting up an experiment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html"><i class="fa fa-check"></i>Some basic experimental designs</a><ul>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#completely-randomised-design-crd"><i class="fa fa-check"></i>Completely randomised design (CRD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#randomised-complete-block-design-rcbd"><i class="fa fa-check"></i>Randomised complete block design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#factorial-design"><i class="fa fa-check"></i>Factorial design</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html"><i class="fa fa-check"></i>Modelling experimental data</a><ul>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-completely-randomised-design-crd-as-a-linear-model"><i class="fa fa-check"></i>A completely randomised design (CRD) as a linear model</a></li>
<li><a href="modelling-experimental-data.html#analysis-of-a-crd-in-r">Analysis of a CRD in <code>R</code></a></li>
<li><a href="modelling-experimental-data.html#using-lm">Using <code>lm()</code></a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-factorial-experiment-as-a-crd"><i class="fa fa-check"></i>A Factorial experiment (as a CRD)</a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#unqual-replications-unbalanced-design"><i class="fa fa-check"></i>Unqual replications (unbalanced design)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i>Multiple comparisons</a><ul>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#classification-of-multiple-hypothesis-tests"><i class="fa fa-check"></i>Classification of multiple hypothesis tests</a></li>
<li><a href="multiple-comparisons.html#multiple-comparison-procedures-using-predictmeans">Multiple comparison procedures using <code>predictmeans</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html"><i class="fa fa-check"></i>Linear mixed-effect models (LMMs)</a><ul>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-randomised-controlled-block-design-rcbd"><i class="fa fa-check"></i>A Randomised Controlled Block Design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-split-plot-design"><i class="fa fa-check"></i>A Split-plot design</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-repeated-measures-design-time-points-as-factors"><i class="fa fa-check"></i>A repeated measures design (time points as factors)</a></li>
<li><a href="linear-mixed-effect-models-lmms.html#animal-as-a-random-effect-in-linear-regression"><code>Animal</code> as a random effect in linear regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-4.html"><a href="module-4.html"><i class="fa fa-check"></i>Module 4</a><ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html"><i class="fa fa-check"></i>Least Squares Estimation</a><ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#some-basic-matrix-algebra"><i class="fa fa-check"></i>Some basic matrix algebra</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#linear-least-squares"><i class="fa fa-check"></i>Linear least squares</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#matrix-representation-of-a-crd"><i class="fa fa-check"></i>Matrix representation of a CRD</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#a-numeric-example"><i class="fa fa-check"></i>A numeric example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html"><i class="fa fa-check"></i>Maximum likelkihood estimation</a><ul>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#differeniation-rules"><i class="fa fa-check"></i>Differeniation rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#logarithn-rules"><i class="fa fa-check"></i>Logarithn rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-binomial-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Binomial distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-crd"><i class="fa fa-check"></i>Maximum likelihood estimation for a CRD</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximising-the-log-likelihood"><i class="fa fa-check"></i>Maximising the log-likelihood</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-poisson-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Poisson distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-continuous-random-variable"><i class="fa fa-check"></i>Maximum likelihood estimation for a continuous random variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html"><i class="fa fa-check"></i>Introduction to Bayesian statistics</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#conditional-probability"><i class="fa fa-check"></i>Conditional probability</a></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#bayes-rule"><i class="fa fa-check"></i>Bayes' rule</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-5.html"><a href="module-5.html"><i class="fa fa-check"></i>Module 5</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-generalised-linear-models-glms.html"><a href="introduction-to-generalised-linear-models-glms.html"><i class="fa fa-check"></i>Introduction to generalised linear models (GLMs)</a></li>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i>Poisson regression</a><ul>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html#an-example-bird-abundance"><i class="fa fa-check"></i>An example: bird abundance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i>Logistic regression</a><ul>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html#an-example-lobsters"><i class="fa fa-check"></i>An example: lobsters</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a-summary-of-glms.html"><a href="a-summary-of-glms.html"><i class="fa fa-check"></i>A summary of GLMs</a></li>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html"><i class="fa fa-check"></i>Generalised linear mixed-effects models (GLMMMs)</a><ul>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html#fitting-a-glmm"><i class="fa fa-check"></i>Fitting a GLMM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-6.html"><a href="module-6.html"><i class="fa fa-check"></i>Module 6</a><ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i>Clustering</a><ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#divisive-partitioning-methods."><i class="fa fa-check"></i>Divisive (partitioning) methods.</a></li>
<li><a href="clustering.html#k-means-an-example-using-the-palmerpenguins-data">K-means: an example using the <code>palmerpenguins</code> data</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-agglomerative-clustering."><i class="fa fa-check"></i>Hierarchical agglomerative clustering.</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-clustering-an-example"><i class="fa fa-check"></i>Hierarchical clustering: an example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html"><i class="fa fa-check"></i>Principal Component Analysis (PCA)</a><ul>
<li><a href="principal-component-analysis-pca.html#examples-in-r">Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html"><i class="fa fa-check"></i>Multidimensional Scaling (MDS)</a><ul>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#metric-scaling"><i class="fa fa-check"></i>Metric Scaling</a></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#correspondence-analysis-ca"><i class="fa fa-check"></i>Correspondence Analysis (CA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="non-metric-multidimensional-scaling.html"><a href="non-metric-multidimensional-scaling.html"><i class="fa fa-check"></i>Non-metric Multidimensional Scaling</a><ul>
<li><a href="non-metric-multidimensional-scaling.html#examples-in-r-2">Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html"><i class="fa fa-check"></i>Linear Discriminant Analysis (LDA)</a><ul>
<li><a href="linear-discriminant-analysis-lda.html#example-in-r">Example in <code>R</code></a></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Biological Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="linear-mixed-effect-models-lmms" class="section level2">
<h2>Linear mixed-effect models (LMMs)</h2>
<p><strong>Recall:</strong> Blocking helps control variability by making treatment groups more alike. Experimental units are divided into subsets (called blocks) so that units within the same block are more similar than units from different subsets or blocks. Blocking is a technique for dealing with nuisance factors. A nuisance factor is a factor that has some effect on the response, but is of no interest (e.g., age class).</p>
<p><strong>Fixed effects</strong> are terms (parameters) in a statistical model which are fixed, or non-random, quantities (e.g., <em>treatment</em> group's mean response). For the same <em>treatment</em>, we expect this quantity to be the same from experiment to experiment.</p>
<p><strong>Random effects</strong> are terms (parameters) in a statistical model which are considered as random quantities or variables (e.g., block id). Specifically, terms whose levels are a representative sample from a population, and where the variance of the population is of interest should be allocated as random. Setting a block as a random effect allows us to infer variation between blocks as well as the variation between experimental units within blocks.</p>
<p><strong>Key idea:</strong> Partition known sources of variation which are unimportant to key scientific question(s) to improve precision of comparisons between treatment means.</p>
<div id="a-randomised-controlled-block-design-rcbd" class="section level3">
<h3>A Randomised Controlled Block Design (RCBD)</h3>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Run
</th>
<th style="text-align:left;">
Surgery
</th>
<th style="text-align:right;">
Rat
</th>
<th style="text-align:right;">
logAUC8
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.24
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
8.81
</td>
</tr>
<tr>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
10.75
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
3.89
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
8.62
</td>
</tr>
<tr>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
10.24
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
8.42
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
9.93
</td>
</tr>
<tr>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
11.68
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
8.77
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
10.86
</td>
</tr>
<tr>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
13.05
</td>
</tr>
</tbody>
</table>
<div id="run-as-a-fixed-effect" class="section level4">
<h4><code>Run</code> as a fixed effect</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC8 <span class="op">~</span><span class="st"> </span>Run <span class="op">+</span><span class="st"> </span>Surgery, <span class="dt">data =</span> rcbd)
<span class="kw">summary</span>(lm)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = logAUC8 ~ Run + Surgery, data = rcbd)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.7517 -0.3683 -0.0900  0.4508  1.5817 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   7.6583     0.8506   9.004 0.000105 ***
## Run2         -2.0167     0.9822  -2.053 0.085854 .  
## Run3          0.4100     0.9822   0.417 0.690882    
## Run4          1.2933     0.9822   1.317 0.235963    
## SurgeryP      1.9750     0.8506   2.322 0.059293 .  
## SurgeryS      3.8500     0.8506   4.526 0.003991 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.203 on 6 degrees of freedom
## Multiple R-squared:  0.8449, Adjusted R-squared:  0.7157 
## F-statistic: 6.538 on 5 and 6 DF,  p-value: 0.02034</code></pre>
</div>
<div id="run-as-a-random-effect" class="section level4">
<h4><code>Run</code> as a random effect</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lmer_mod &lt;-<span class="st"> </span>lmerTest<span class="op">::</span><span class="kw">lmer</span>(logAUC8 <span class="op">~</span><span class="st"> </span>Surgery <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Run), <span class="dt">data =</span> rcbd)
<span class="kw">summary</span>(lmer_mod)</code></pre></div>
<pre><code>## Linear mixed model fit by REML. t-tests use Satterthwaite&#39;s method [
## lmerModLmerTest]
## Formula: logAUC8 ~ Surgery + (1 | Run)
##    Data: rcbd
## 
## REML criterion at convergence: 37.2
## 
## Scaled residuals: 
##     Min      1Q  Median      3Q     Max 
## -1.8525 -0.2273  0.1772  0.4036  1.3309 
## 
## Random effects:
##  Groups   Name        Variance Std.Dev.
##  Run      (Intercept) 1.479    1.216   
##  Residual             1.447    1.203   
## Number of obs: 12, groups:  Run, 4
## 
## Fixed effects:
##             Estimate Std. Error     df t value Pr(&gt;|t|)    
## (Intercept)   7.5800     0.8552 5.9567   8.863 0.000119 ***
## SurgeryP      1.9750     0.8506 6.0000   2.322 0.059293 .  
## SurgeryS      3.8500     0.8506 6.0000   4.526 0.003991 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Correlation of Fixed Effects:
##          (Intr) SrgryP
## SurgeryP -0.497       
## SurgeryS -0.497  0.500</code></pre>
<div id="inference-about-the-random-effects" class="section level5">
<h5>Inference about the <em>Random effects</em></h5>
<p>We have two variance components</p>
<ul>
<li>Between Groups (Runs) <span class="math inline">\(\hat{\sigma^2}_{\text{Run}}\)</span> = 1.479</li>
<li>Within Runs (between observations) <span class="math inline">\(\hat{\sigma_2}\)</span> = 1.447</li>
</ul>
<p>Note that <code>aov()</code> presents the same information, but in a different way:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(<span class="kw">aov</span>(logAUC8 <span class="op">~</span><span class="st"> </span>Surgery <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(Run), <span class="dt">data =</span> rcbd))</code></pre></div>
<pre><code>## 
## Error: Run
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals  3  17.65   5.883               
## 
## Error: Within
##           Df Sum Sq Mean Sq F value Pr(&gt;F)  
## Surgery    2 29.652  14.826   10.25 0.0116 *
## Residuals  6  8.682   1.447                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<ul>
<li>Within Runs (Residuals) <span class="math inline">\(\hat{\sigma}_2\)</span> = 1.447 (<em>same as <code>lmer</code></em>)</li>
<li>Between Run variance = <span class="math inline">\(\hat{\sigma}^2\)</span> + <span class="math inline">\(3\:\hat{\sigma}^2_{\text{Run}}\)</span> so <span class="math inline">\(\hat{\sigma}^2_{\text{Run}} = \frac{5.883 - \hat{\sigma}^2 }{3} = \frac{5.883 - 1.447}{3} = 1.479\)</span></li>
</ul>
</div>
</div>
</div>
<div id="a-split-plot-design" class="section level3">
<h3>A Split-plot design</h3>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:left;">
Animal
</th>
<th style="text-align:left;">
Sample
</th>
<th style="text-align:right;">
logAUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
9.40
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
8.83
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
10.33
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
10.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
9.74
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
10.98
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
7.92
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
9.37
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
8.69
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
11.31
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
7.01
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
9.29
</td>
</tr>
</tbody>
</table>
<div id="animal-as-a-random-effect" class="section level4">
<h4><code>Animal</code> as a random effect</h4>
<p><strong>Using <code>aov()</code></strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sp_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease<span class="op">*</span>Organ <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(Animal), <span class="dt">data =</span> split_plot)
<span class="kw">summary</span>(sp_aov)</code></pre></div>
<pre><code>## 
## Error: Animal
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Disease    1  3.183   3.183   2.187  0.213
## Residuals  4  5.822   1.456               
## 
## Error: Within
##               Df Sum Sq Mean Sq F value Pr(&gt;F)  
## Organ          1  4.296   4.296  14.423 0.0191 *
## Disease:Organ  1  2.539   2.539   8.525 0.0433 *
## Residuals      4  1.191   0.298                 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Using <code>lmer()</code> (from <code>lmeTest</code> and <code>lmer4</code>)</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sp_lmer &lt;-<span class="st"> </span>lmerTest<span class="op">::</span><span class="kw">lmer</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease<span class="op">*</span>Organ <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Animal), 
                          <span class="dt">data =</span> split_plot) ## MUST SPECIFY WHICH PACKAGE
<span class="kw">anova</span>(sp_lmer,<span class="dt">type =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>## Type II Analysis of Variance Table with Satterthwaite&#39;s method
##               Sum Sq Mean Sq NumDF DenDF F value  Pr(&gt;F)  
## Disease       0.6513  0.6513     1     4  2.1866 0.21329  
## Organ         4.2960  4.2960     1     4 14.4227 0.01914 *
## Disease:Organ 2.5392  2.5392     1     4  8.5246 0.04326 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">sp_lmer4 &lt;-<span class="st"> </span>lme4<span class="op">::</span><span class="kw">lmer</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease<span class="op">*</span>Organ <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Animal), <span class="dt">data =</span> split_plot) ## MUST SPECIFY WHICH PACKAGE
predmeans &lt;-<span class="st"> </span>predictmeans<span class="op">::</span><span class="kw">predictmeans</span>(<span class="dt">model =</span> sp_lmer4 ,<span class="dt">modelterm =</span> <span class="st">&quot;Disease:Organ&quot;</span>)
predmeans<span class="op">$</span>mean_table</code></pre></div>
<pre><code>##    Disease   Organ Predicted means Standard error Df LL of 95% CI UL of 95% CI
## 1 Diabetic innerLV        7.873333      0.5405835  4     6.372433     9.374234
## 2 Diabetic outerLV        9.990000      0.5405835  4     8.489099    11.490901
## 3  Healthy innerLV        9.823333      0.5405835  4     8.322433    11.324234
## 4  Healthy outerLV       10.100000      0.5405835  4     8.599099    11.600901</code></pre>
</div>
</div>
<div id="a-repeated-measures-design-time-points-as-factors" class="section level3">
<h3>A repeated measures design (time points as factors)</h3>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">liver &lt;-<span class="st"> </span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/STATS-UOA/databunker/master/data/repeated_measures_liver.csv&quot;</span>)
## change time to factor
liver<span class="op">$</span>Time &lt;-<span class="st"> </span><span class="kw">as.factor</span>(liver<span class="op">$</span>Time) ## this is important
liver<span class="op">$</span>Treatment &lt;-<span class="st"> </span><span class="kw">as.factor</span>(liver<span class="op">$</span>Treatment)
liver</code></pre></div>
<pre><code>## # A tibble: 210 × 4
##    Animal   Treatment Time  Glucose
##    &lt;chr&gt;    &lt;fct&gt;     &lt;fct&gt;   &lt;dbl&gt;
##  1 Control1 Control   0        1.60
##  2 Control1 Control   5        1.28
##  3 Control1 Control   10       1.60
##  4 Control1 Control   15       1.58
##  5 Control1 Control   20       1.28
##  6 Control1 Control   25       1.44
##  7 Control1 Control   30       1.18
##  8 Control2 Control   0        0.84
##  9 Control2 Control   5        0.64
## 10 Control2 Control   10       0.7 
## # … with 200 more rows</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-110-1.png" width="672" /><img src="_main_files/figure-html/unnamed-chunk-110-2.png" width="672" /></p>
</div>
<div id="animal-as-a-random-effect-in-linear-regression" class="section level3">
<h3><code>Animal</code> as a random effect in linear regression</h3>
<p><img src="_main_files/figure-html/unnamed-chunk-111-1.png" width="672" /></p>
<p><strong>Using <code>aov()</code></strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">re_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(Glucose <span class="op">~</span><span class="st"> </span>Treatment<span class="op">*</span>Time <span class="op">+</span><span class="st"> </span><span class="kw">Error</span>(Animal),<span class="dt">data =</span> liver)
<span class="kw">summary</span>(re_aov)</code></pre></div>
<pre><code>## 
## Error: Animal
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Treatment  3   1.90  0.6335   1.407  0.263
## Residuals 26  11.71  0.4503               
## 
## Error: Within
##                 Df Sum Sq Mean Sq F value       Pr(&gt;F)    
## Time             6 0.7973 0.13289   8.732 0.0000000334 ***
## Treatment:Time  18 0.2539 0.01411   0.927        0.547    
## Residuals      156 2.3741 0.01522                         
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Using <code>lmer()</code> (from <code>lmerTest</code> and <code>lme4</code>)</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">re_lmer &lt;-<span class="st"> </span>lmerTest<span class="op">::</span><span class="kw">lmer</span>(Glucose <span class="op">~</span><span class="st"> </span>Treatment<span class="op">*</span>Time <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Animal), <span class="dt">data =</span> liver) ## MUST SPECIFY WHICH PACKAGE
<span class="kw">anova</span>(re_lmer,<span class="dt">type =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>## Type II Analysis of Variance Table with Satterthwaite&#39;s method
##                 Sum Sq  Mean Sq NumDF DenDF F value        Pr(&gt;F)    
## Treatment      0.06423 0.021409     3    26  1.4068        0.2632    
## Time           0.79731 0.132885     6   156  8.7318 0.00000003345 ***
## Treatment:Time 0.25390 0.014105    18   156  0.9269        0.5474    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">re_lmer4 &lt;-<span class="st"> </span>lme4<span class="op">::</span><span class="kw">lmer</span>(Glucose <span class="op">~</span><span class="st"> </span>Treatment<span class="op">*</span>Time <span class="op">+</span><span class="st"> </span>(<span class="dv">1</span><span class="op">|</span>Animal),<span class="dt">data =</span> liver) ## MUST SPECIFY WHICH PACKAGE
predmeans &lt;-<span class="st"> </span>predictmeans<span class="op">::</span><span class="kw">predictmeans</span>(<span class="dt">model =</span> re_lmer4 ,<span class="dt">modelterm =</span> <span class="st">&quot;Treatment:Time&quot;</span>)
predmeans<span class="op">$</span>mean_table</code></pre></div>
<pre><code>##    Treatment Time Predicted means Standard error  Df LL of 95% CI UL of 95% CI
## 1    Control    0       0.6493750     0.09834458 156    0.4551162    0.8436338
## 2    Control    5       0.5495000     0.09834458 156    0.3552412    0.7437588
## 3    Control   10       0.5821250     0.09834458 156    0.3878662    0.7763838
## 4    Control   15       0.5997500     0.09834458 156    0.4054912    0.7940088
## 5    Control   20       0.5048750     0.09834458 156    0.3106162    0.6991338
## 6    Control   25       0.5196250     0.09834458 156    0.3253662    0.7138838
## 7    Control   30       0.5047500     0.09834458 156    0.3104912    0.6990088
## 8        DCI    0       0.5443750     0.09834458 156    0.3501162    0.7386338
## 9        DCI    5       0.4601250     0.09834458 156    0.2658662    0.6543838
## 10       DCI   10       0.4703750     0.09834458 156    0.2761162    0.6646338
## 11       DCI   15       0.4171250     0.09834458 156    0.2228662    0.6113838
## 12       DCI   20       0.3668750     0.09834458 156    0.1726162    0.5611338
## 13       DCI   25       0.4280000     0.09834458 156    0.2337412    0.6222588
## 14       DCI   30       0.3625000     0.09834458 156    0.1682412    0.5567588
## 15   Insulin    0       0.8345714     0.10513478 156    0.6269000    1.0422428
## 16   Insulin    5       0.8474286     0.10513478 156    0.6397572    1.0551000
## 17   Insulin   10       0.7035714     0.10513478 156    0.4959000    0.9112428
## 18   Insulin   15       0.6561429     0.10513478 156    0.4484714    0.8638143
## 19   Insulin   20       0.6450000     0.10513478 156    0.4373286    0.8526714
## 20   Insulin   25       0.6044286     0.10513478 156    0.3967572    0.8121000
## 21   Insulin   30       0.5287143     0.10513478 156    0.3210429    0.7363857
## 22        MI    0       0.5595714     0.10513478 156    0.3519000    0.7672428
## 23        MI    5       0.4971429     0.10513478 156    0.2894714    0.7048143
## 24        MI   10       0.5110000     0.10513478 156    0.3033286    0.7186714
## 25        MI   15       0.4714286     0.10513478 156    0.2637572    0.6791000
## 26        MI   20       0.4741429     0.10513478 156    0.2664714    0.6818143
## 27        MI   25       0.4572857     0.10513478 156    0.2496143    0.6649571
## 28        MI   30       0.3720000     0.10513478 156    0.1643286    0.5796714</code></pre>

</div>
</div>
<!-- </div> -->
            </section>

          </div>
        </div>
      </div>
<a href="multiple-comparisons.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="module-4.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
