<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Modelling experimental data | Advanced Biological Data Analysis</title>
  <meta name="description" content="Modelling experimental data | Advanced Biological Data Analysis" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Modelling experimental data | Advanced Biological Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Modelling experimental data | Advanced Biological Data Analysis" />
  
  
  

<meta name="author" content="University of Auckland" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="some-basic-experimental-designs.html"/>
<link rel="next" href="multiple-comparisons.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Nau mai, haere mai. Welcome to BIOSCI 738</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html"><i class="fa fa-check"></i>Useful information to set you up for your semester</a><ul>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#course-outline"><i class="fa fa-check"></i>Course outline</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#learning-outcomes"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#course-summary"><i class="fa fa-check"></i>Course summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-1.html"><a href="module-1.html"><i class="fa fa-check"></i>Module 1</a><ul>
<li><a href="r-and-rstudio.html#r-and-rstudio"><code>R</code> and <code>RStudio</code></a><ul>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html"><i class="fa fa-check"></i>Installing R and RStudio</a></li>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#getting-started"><i class="fa fa-check"></i>Getting started</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html"><i class="fa fa-check"></i>Reproducible research</a><ul>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html#project-oriented-workflow-good-practice"><i class="fa fa-check"></i>Project-oriented workflow: good practice</a></li>
<li><a href="reproducible-research.html#version-control-with-git-and-github">Version control with <code>git</code> and GitHub</a></li>
</ul></li>
<li><a href="your-data-and-r.html#your-data-and-r">Your data and <code>R</code></a><ul>
<li><a href="your-data-and-r.html#reading-in-data-from-a-.csv-file">Reading in data from a <code>.csv</code> file</a></li>
<li class="chapter" data-level="" data-path="your-data-and-r.html"><a href="your-data-and-r.html"><i class="fa fa-check"></i>Explore your data</a></li>
<li><a href="your-data-and-r.html#the-pipe-operator">The pipe operator <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i>Data wrangling</a><ul>
<li><a href="data-wrangling.html#introuducing-the-palmer-penguins">Introuducing the <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081">Palmer penguins</a></a></li>
<li><a href="data-wrangling.html#common-dataframe-manipulations-in-the-tidyverse-using-dplyr-and-tidyr">Common dataframe manipulations in the <code>tidyverse</code>, using <code>dplyr</code> and <code>tidyr</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html"><i class="fa fa-check"></i>Data visualiation (data viz)</a><ul>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#exploratory-plots"><i class="fa fa-check"></i>Exploratory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#explanatory-plots"><i class="fa fa-check"></i>Explanatory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#ten-simple-rules-for-better-figures"><i class="fa fa-check"></i>Ten Simple Rules for Better Figures</a></li>
<li><a href="data-visualiation-data-viz.html#ggplot2"><code>ggplot2</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html"><i class="fa fa-check"></i>Māori Data Sovereignty principles</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-2.html"><a href="module-2.html"><i class="fa fa-check"></i>Module 2</a><ul>
<li class="chapter" data-level="" data-path="key-satistical-concepts.html"><a href="key-satistical-concepts.html"><i class="fa fa-check"></i>Key satistical concepts</a></li>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html"><i class="fa fa-check"></i>Bootstrap resampling</a><ul>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html#example-constructing-bootstrap-confidence-intervals"><i class="fa fa-check"></i>Example: constructing bootstrap confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html"><i class="fa fa-check"></i>Permutation and randomisation tests</a><ul>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html#a-permutation-test-jackal-mandible-lengths"><i class="fa fa-check"></i>A permutation test: Jackal mandible lengths</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resampling-procedures-the-differences.html"><a href="resampling-procedures-the-differences.html"><i class="fa fa-check"></i>Resampling procedures, the differences</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html"><i class="fa fa-check"></i>Hypothesis testing: key terms</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#p-values"><i class="fa fa-check"></i>😱 p-values 😱</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i>Type I and Type II errors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html"><i class="fa fa-check"></i>Parametric hypothesis tests</a><ul>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-sample-t-test"><i class="fa fa-check"></i>One-Sample t-test</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#differences-between-two-means"><i class="fa fa-check"></i>Differences between two means</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-way-analysis-of-variance-anova"><i class="fa fa-check"></i>One-Way Analysis of Variance (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i>Linear regression</a><ul>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#some-mathematical-notation"><i class="fa fa-check"></i>Some mathematical notation</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#modeling-bill-depth"><i class="fa fa-check"></i>Modeling Bill Depth</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#single-continuous-variable"><i class="fa fa-check"></i>Single continuous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#one-factor-and-a-continuous-variable"><i class="fa fa-check"></i>One factor and a continuous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li><a href="model-formula-syntax-in-r.html#model-formula-syntax-in-r">Model formula syntax in <code>R</code></a><ul>
<li class="chapter" data-level="" data-path="model-formula-syntax-in-r.html"><a href="model-formula-syntax-in-r.html"><i class="fa fa-check"></i>Other possible models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html"><i class="fa fa-check"></i>Model diagnostics for a linear model</a><ul>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#marginal-predictions"><i class="fa fa-check"></i>Marginal predictions</a></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#model-selection"><i class="fa fa-check"></i>Model selection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html"><i class="fa fa-check"></i>Inference for a linear model</a><ul>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#point-prediction"><i class="fa fa-check"></i>Point prediction</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#confidence-intervals-for-parameters"><i class="fa fa-check"></i>Confidence intervals for parameters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-3.html"><a href="module-3.html"><i class="fa fa-check"></i>Module 3</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html"><i class="fa fa-check"></i>Introduction to the design and analysis of experiments</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#key-phrases"><i class="fa fa-check"></i>Key phrases</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#the-three-key-principles"><i class="fa fa-check"></i>The three key principles:</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#replication"><i class="fa fa-check"></i>Replication</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#randomization"><i class="fa fa-check"></i>Randomization</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#blocking"><i class="fa fa-check"></i>Blocking</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#setting-up-an-experiment"><i class="fa fa-check"></i>Setting up an experiment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html"><i class="fa fa-check"></i>Some basic experimental designs</a><ul>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#completely-randomised-design-crd"><i class="fa fa-check"></i>Completely randomised design (CRD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#randomised-complete-block-design-rcbd"><i class="fa fa-check"></i>Randomised complete block design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#factorial-design"><i class="fa fa-check"></i>Factorial design</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html"><i class="fa fa-check"></i>Modelling experimental data</a><ul>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-completely-randomised-design-crd-as-a-linear-model"><i class="fa fa-check"></i>A completely randomised design (CRD) as a linear model</a></li>
<li><a href="modelling-experimental-data.html#analysis-of-a-crd-in-r">Analysis of a CRD in <code>R</code></a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-factorial-experiment-as-a-crd"><i class="fa fa-check"></i>A Factorial experiment (as a CRD)</a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#unqual-replications-unbalanced-design"><i class="fa fa-check"></i>Unqual replications (unbalanced design)</a></li>
<li><a href="modelling-experimental-data.html#sums-of-squares-ss">Sums of squares (<span class="math inline">\(SS\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i>Multiple comparisons</a><ul>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#adjustments-for-multiple-testing"><i class="fa fa-check"></i>Adjustments for multiple testing</a></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#classification-of-multiple-hypothesis-tests"><i class="fa fa-check"></i>Classification of multiple hypothesis tests</a></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#multiple-comparison-procedures"><i class="fa fa-check"></i>Multiple comparison procedures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html"><i class="fa fa-check"></i>Linear mixed-effect models (LMMs)</a><ul>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-randomised-controlled-block-design-rcbd"><i class="fa fa-check"></i>A Randomised Controlled Block Design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-split-plot-design"><i class="fa fa-check"></i>A Split-plot design</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-repeated-measures-design"><i class="fa fa-check"></i>A repeated measures design</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-4.html"><a href="module-4.html"><i class="fa fa-check"></i>Module 4</a><ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html"><i class="fa fa-check"></i>Least Squares Estimation</a><ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#some-basic-matrix-algebra"><i class="fa fa-check"></i>Some basic matrix algebra</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#linear-least-squares"><i class="fa fa-check"></i>Linear least squares</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#matrix-representation-of-a-crd"><i class="fa fa-check"></i>Matrix representation of a CRD</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#a-numeric-example"><i class="fa fa-check"></i>A numeric example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i>Maximum likelihood estimation</a><ul>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#differeniation-rules"><i class="fa fa-check"></i>Differeniation rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#logarithm-rules"><i class="fa fa-check"></i>Logarithm rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-binomial-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Binomial distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-crd"><i class="fa fa-check"></i>Maximum likelihood estimation for a CRD</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximising-the-log-likelihood"><i class="fa fa-check"></i>Maximising the log-likelihood</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-poisson-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Poisson distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-continuous-random-variable"><i class="fa fa-check"></i>Maximum likelihood estimation for a continuous random variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html"><i class="fa fa-check"></i>Introduction to Bayesian statistics</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#conditional-probability"><i class="fa fa-check"></i>Conditional probability</a></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#bayes-rule"><i class="fa fa-check"></i>Bayes' rule</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-5.html"><a href="module-5.html"><i class="fa fa-check"></i>Module 5</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-generalised-linear-models-glms.html"><a href="introduction-to-generalised-linear-models-glms.html"><i class="fa fa-check"></i>Introduction to generalised linear models (GLMs)</a></li>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i>Poisson regression</a><ul>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html#an-example-bird-abundance"><i class="fa fa-check"></i>An example: bird abundance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i>Logistic regression</a><ul>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html#an-example-lobsters"><i class="fa fa-check"></i>An example: lobsters</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a-summary-of-glms.html"><a href="a-summary-of-glms.html"><i class="fa fa-check"></i>A summary of GLMs</a></li>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html"><i class="fa fa-check"></i>Generalised linear mixed-effects models (GLMMMs)</a><ul>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html#fitting-a-glmm"><i class="fa fa-check"></i>Fitting a GLMM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-6.html"><a href="module-6.html"><i class="fa fa-check"></i>Module 6</a><ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i>Clustering</a><ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#divisive-partitioning-methods."><i class="fa fa-check"></i>Divisive (partitioning) methods.</a></li>
<li><a href="clustering.html#k-means-an-example-using-the-palmerpenguins-data">K-means: an example using the <code>palmerpenguins</code> data</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-agglomerative-clustering."><i class="fa fa-check"></i>Hierarchical agglomerative clustering.</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-clustering-an-example"><i class="fa fa-check"></i>Hierarchical clustering: an example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html"><i class="fa fa-check"></i>Principal Component Analysis (PCA)</a><ul>
<li><a href="principal-component-analysis-pca.html#examples-in-r">Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html"><i class="fa fa-check"></i>Multidimensional Scaling (MDS)</a><ul>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#metric-scaling"><i class="fa fa-check"></i>Metric Scaling</a></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#correspondence-analysis-ca"><i class="fa fa-check"></i>Correspondence Analysis (CA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="non-metric-multidimensional-scaling.html"><a href="non-metric-multidimensional-scaling.html"><i class="fa fa-check"></i>Non-metric Multidimensional Scaling</a><ul>
<li><a href="non-metric-multidimensional-scaling.html#examples-in-r-2">Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html"><i class="fa fa-check"></i>Linear Discriminant Analysis (LDA)</a><ul>
<li><a href="linear-discriminant-analysis-lda.html#example-in-r">Example in <code>R</code></a></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Biological Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelling-experimental-data" class="section level2">
<h2>Modelling experimental data</h2>
<div id="a-completely-randomised-design-crd-as-a-linear-model" class="section level3">
<h3>A completely randomised design (CRD) as a linear model</h3>
<p>As we've seen in the previous module that we can write a linear model with a single explanatory variable as</p>
<p><span class="math display">\[Y_i = \alpha + \beta_1x_i + \epsilon_i\]</span></p>
<p>When dealing with factor variables we use dummy variables and can write the above as</p>
<p><span class="math display">\[Y_{ik} = \alpha + \tau_k + \epsilon_{ik}\]</span> where <span class="math inline">\(\tau_k\)</span> is called an <em>effect</em> and represents the difference between the overall average, <span class="math inline">\(\alpha\)</span>, and the average at the <span class="math inline">\(k_{th}\)</span> treatment level. The errors <span class="math inline">\(\epsilon_{ik}\)</span> are again assumed to be normally distributed and independent due to the randomisation (i.e., <span class="math inline">\(\epsilon_{ik} \sim N(0, \sigma^2)\)</span>.</p>
<p>Or you might think of the model as</p>
<p><span class="math display">\[Y_{ik} = \mu_k + \epsilon_{ik}\]</span></p>
<p>where <span class="math inline">\(Y_{ik}\)</span> is the response (i.e., observed coffee opacity) for the <span class="math inline">\(i^{th}\)</span> experimental unit (i.e., coffee cup) subjected to the <span class="math inline">\(k^{th}\)</span> level of the treatment factor (i.e., coffee type). Here <span class="math inline">\(\mu_k\)</span> are the different (cell) means for each level of the treatment factor. See below for an illustration of this for three factor treatment levels (as in the coffee example above).</p>
<p><img src="_main_files/figure-html/unnamed-chunk-86-1.png" width="672" /></p>
</div>
<div id="analysis-of-a-crd-in-r" class="section level3">
<h3>Analysis of a CRD in <code>R</code></h3>
<p>In this section we again consider the data containing logAUC values for 12 rats subjected to three different treatments (<code>Surgery</code>), <code>C</code>, <code>P</code>, and <code>S</code>:</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Surgery
</th>
<th style="text-align:right;">
Rat
</th>
<th style="text-align:right;">
logAUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8.49
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
8.20
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9.08
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8.07
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10.24
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
7.72
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9.34
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8.50
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
11.31
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
12.69
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
11.37
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
10.82
</td>
</tr>
</tbody>
</table>
<p>To read the data directly into <code>R</code> you can use</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">readr<span class="op">::</span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/STATS-UOA/databunker/master/data/crd_rats_data.csv&quot;</span>)</code></pre></div>
<p>We could analyse these data <strong>using <code>aov()</code></strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rats_aov &lt;-<span class="st"> </span><span class="kw">aov</span>(logAUC <span class="op">~</span><span class="st"> </span>Surgery, <span class="dt">data =</span> rats)
<span class="kw">summary</span>(rats_aov)</code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## Surgery      2 22.026  11.013   16.36 0.00101 **
## Residuals    9  6.059   0.673                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Hypothesis: We test the Null hypothesis, <span class="math inline">\(H_0\)</span>, population (<code>Surgery</code>) means are the same on average verses the alternative hypothesis, <span class="math inline">\(H_1\)</span>, that <strong>at least one</strong> differs from the others!</p>
<p>Probability of getting an <strong>F-statistic</strong> at least as extreme as the one we observe (think of the area under the tails of the curve below) <strong>p-value</strong> Pr(&gt;F)= 0.001 tells us we have sufficient evidence to reject <span class="math inline">\(H_0\)</span> at the 1% level of significance</p>
<p>Alternatively, we could <strong>use <code>lm()</code></strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rats_lm &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Surgery, <span class="dt">data =</span> rats)
<span class="kw">summary</span>(rats_lm)<span class="op">$</span>coef</code></pre></div>
<pre><code>##             Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)   8.4600  0.4102531 20.6214144 6.930903e-09
## SurgeryP      0.4900  0.5801856  0.8445574 4.202408e-01
## SurgeryS      3.0875  0.5801856  5.3215734 4.799872e-04</code></pre>
<p>So, what does this tell us about which pairs of means are different?</p>
<p>To carry out a pair-wise comparisons of means we can use two-sample t-tests, calculating our <strong>observed</strong> t-value where <span class="math inline">\(\text{t-value} = \frac{\text{Sample Difference}_{ij} - \text{Difference assuming } H_0 \text{ is true}_{ij}}{\text{SE of } \text{Sample Difference}_{ij}}\)</span>. Here, <span class="math inline">\(\text{Sample Difference}_{ij}\)</span> = Difference between pair of sample means. We can then compute the p-value for observed t-value.</p>
<p>The output above has already done this for us:</p>
<p>(Intercept) = <span class="math inline">\(\text{mean}_C\)</span> = 8.46</p>
<p>SE of (Intercept) = SE of <span class="math inline">\(\text{mean}_C\)</span> = SEM = 0.4102531</p>
<p><span class="math inline">\(\text{Surgery}_P\)</span> = <span class="math inline">\(\text{mean}_P\)</span> – <span class="math inline">\(\text{mean}_C\)</span> = 0.49</p>
<p>SE of <span class="math inline">\(\text{Surgery}_P\)</span> = SE of (<span class="math inline">\(\text{mean}_P\)</span> - <span class="math inline">\(\text{mean}_C\)</span> ) = SED = 0.5801856</p>
<p><img src="_main_files/figure-html/unnamed-chunk-89-1.png" width="672" /></p>
<p><strong>Hypotheses being tested</strong></p>
<p>The <code>t</code> value and <code>Pr (&gt;|t|)</code> are the t-statistic and p-value for testing the null hypotheses listed below 1. Mean abundance is zero for <code>C</code> population 2. No difference between the population means of <code>P</code> and <code>C</code> 3. No difference between the population means of <code>S</code> and <code>C</code></p>
<p>We're interested in 2 and 3, but not necessarily 1!</p>
<p><strong>F-test:</strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(rats_lm)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##           Df  Sum Sq Mean Sq F value   Pr(&gt;F)   
## Surgery    2 22.0263 11.0132  16.359 0.001006 **
## Residuals  9  6.0591  0.6732                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>The same as <code>aov()</code></strong> in fact <code>aov()</code> is calling <code>lm()</code> in the background.</p>
<div id="diagnostic-plots" class="section level4">
<h4>Diagnostic plots</h4>
<p>Carrying out any linear regression recall that we have some <strong>key assumptions</strong></p>
<ul>
<li><strong>Independence</strong></li>
<li>There is a <strong>linear relationship</strong> between the response and the explanatory variables</li>
<li>The residuals have <strong>constant variance</strong></li>
<li>The <strong>residuals</strong> are normally distributed</li>
</ul>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gglm<span class="op">::</span><span class="kw">gglm</span>(rats_lm) <span class="co"># Plot the four main diagnostic plots</span></code></pre></div>
<p><img src="_main_files/figure-html/qqnorm-1.png" width="672" /></p>
<p>What do you think? Look back at module 2.</p>
</div>
</div>
<div id="a-factorial-experiment-as-a-crd" class="section level3">
<h3>A Factorial experiment (as a CRD)</h3>
<p align="center">
<img src="https://magoosh.com/statistics/files/2018/04/297r7s.jpg" style="width:30.0%" />
</p>
<div id="equal-replications-balanced-design" class="section level4">
<h4>Equal replications (balanced design)</h4>
<p><strong>Data</strong> Global metabolic profiling and comparison of relative abundances of proteins (<code>logAUC</code>) in the inner and outer left ventricle (<code>innerLV</code> and <code>outerLV</code>) wall of diabetic and healthy male Wistar rats. To read the data directly into <code>R</code> you can use</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">readr<span class="op">::</span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/STATS-UOA/databunker/master/data/factorial_expt.csv&quot;</span>)</code></pre></div>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:left;">
Diabetic
</th>
<th style="text-align:left;">
Healthy
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
n = 3
</td>
<td style="text-align:left;">
n = 3
</td>
</tr>
<tr>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
n = 3
</td>
<td style="text-align:left;">
n = 3
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
Animal
</th>
<th style="text-align:right;">
Sample
</th>
<th style="text-align:right;">
logAUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.40
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
8.83
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10.33
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
10.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.74
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
10.98
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.92
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
9.37
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8.69
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
11.31
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.01
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
9.29
</td>
</tr>
</tbody>
</table>
<p><strong>Fitting models with interactions using <code>lm()</code></strong></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## change to factors (saves errors later on)
factorial<span class="op">$</span>Disease &lt;-<span class="st"> </span><span class="kw">as.factor</span>(factorial<span class="op">$</span>Disease)
factorial<span class="op">$</span>Organ &lt;-<span class="st"> </span><span class="kw">as.factor</span>(factorial<span class="op">$</span>Organ)
fac_lm &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease<span class="op">*</span>Organ, <span class="dt">data =</span> factorial)
<span class="kw">summary</span>(fac_lm)<span class="op">$</span>coefficients</code></pre></div>
<pre><code>##                              Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)                  7.873333  0.5405835 14.564508 4.841215e-07
## DiseaseHealthy               1.950000  0.7645006  2.550685 3.413826e-02
## OrganouterLV                 2.116667  0.7645006  2.768692 2.434579e-02
## DiseaseHealthy:OrganouterLV -1.840000  1.0811671 -1.701865 1.271934e-01</code></pre>
<p>So, the full model is</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{\widehat{logAUC}} &amp;= 7.87 + 1.95(\operatorname{Disease}_{\operatorname{Healthy}}) + 2.12(\operatorname{Organ}_{\operatorname{outerLV}}) - 1.84(\operatorname{Disease}_{\operatorname{Healthy}} \times \operatorname{Organ}_{\operatorname{outerLV}})
\end{aligned}
\]</span></p>
<p>The three <strong>gobal</strong> null hypotheses being tested are</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \hat{\mu}_{\text{Diabetic}} = \hat{\mu}_{\text{Healthy}}\)</span></li>
<li><span class="math inline">\(H_0: \hat{\mu}_{\text{innerLV}} = \hat{\mu}_{\text{outerLV}}\)</span></li>
<li><span class="math inline">\(H_0: \hat{\mu}_{\text{Diabetic,innerLV}} = \hat{\mu}_{\text{Diabetic,outerLV}} = \hat{\mu}_{\text{Healthy,innerLV}} = \hat{\mu}_{\text{Healthy,outerLV}}\)</span></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">anova</span>(fac_lm)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##               Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Disease        1 3.1827  3.1827  3.6304 0.09320 .
## Organ          1 4.2960  4.2960  4.9003 0.05775 .
## Disease:Organ  1 2.5392  2.5392  2.8963 0.12719  
## Residuals      8 7.0135  0.8767                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>What conclusions do you draw?</p>
<p><strong>Note</strong> with a balanced design ordering of term doesn't matter. For example,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fac_lm &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease<span class="op">*</span>Organ, <span class="dt">data =</span> factorial)
<span class="kw">anova</span>(fac_lm)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##               Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Disease        1 3.1827  3.1827  3.6304 0.09320 .
## Organ          1 4.2960  4.2960  4.9003 0.05775 .
## Disease:Organ  1 2.5392  2.5392  2.8963 0.12719  
## Residuals      8 7.0135  0.8767                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fac_lm_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Organ<span class="op">*</span>Disease, <span class="dt">data =</span> factorial)
<span class="kw">anova</span>(fac_lm_<span class="dv">2</span>)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##               Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Organ          1 4.2960  4.2960  4.9003 0.05775 .
## Disease        1 3.1827  3.1827  3.6304 0.09320 .
## Organ:Disease  1 2.5392  2.5392  2.8963 0.12719  
## Residuals      8 7.0135  0.8767                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="unqual-replications-unbalanced-design" class="section level3">
<h3>Unqual replications (unbalanced design)</h3>
<p>Here, we consider a subset of the data above.</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:left;">
Diabetic
</th>
<th style="text-align:left;">
Healthy
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:left;">
n = 3
</td>
<td style="text-align:left;">
n = 1
</td>
</tr>
<tr>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:left;">
n = 2
</td>
<td style="text-align:left;">
n = 2
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
Animal
</th>
<th style="text-align:right;">
Sample
</th>
<th style="text-align:right;">
logAUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
10.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
9.74
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
10.98
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.92
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
9.37
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8.69
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
7.01
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
9.29
</td>
</tr>
</tbody>
</table>
<p><strong>Fitting models with interactions using <code>lm()</code></strong></p>
<p><strong>Note</strong>: order matters. For example,</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fac_lm &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease<span class="op">*</span>Organ, <span class="dt">data =</span> unbalanced_nafree)
<span class="kw">anova</span>(fac_lm)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##               Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Disease        1 7.1102  7.1102 18.4955 0.01264 *
## Organ          1 3.1149  3.1149  8.1027 0.04656 *
## Disease:Organ  1 0.0913  0.0913  0.2376 0.65145  
## Residuals      4 1.5377  0.3844                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fac_lm_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Organ<span class="op">*</span>Disease, <span class="dt">data =</span> unbalanced_nafree)
<span class="kw">anova</span>(fac_lm_<span class="dv">2</span>)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##               Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Organ          1 5.7291  5.7291 14.9029 0.01814 *
## Disease        1 4.4960  4.4960 11.6953 0.02678 *
## Organ:Disease  1 0.0913  0.0913  0.2376 0.65145  
## Residuals      4 1.5377  0.3844                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The three <strong>global</strong> null hypotheses being tested are (essentially) the same</p>
<ol style="list-style-type: decimal">
<li><span class="math inline">\(H_0: \hat{\mu}_{\text{Diabetic}} = \hat{\mu}_{\text{Healthy}}\)</span></li>
<li><span class="math inline">\(H_0: \hat{\mu}_{\text{innerLV}} = \hat{\mu}_{\text{outerLV}}\)</span></li>
<li><span class="math inline">\(H_0: \hat{\mu}_{\text{Diabetic,innerLV}} = \hat{\mu}_{\text{Diabetic,outerLV}} = \hat{\mu}_{\text{Healthy,innerLV}} = \hat{\mu}_{\text{Healthy,outerLV}}\)</span></li>
</ol>
<p>However, now the <strong>order the terms affects</strong> the estimation. Look carefully at the <code>anova()</code> outputs above; what to you notice about the sums of squares (<code>Sum Sq</code>) values?</p>
<p>For a <strong>balanced</strong> two-factor experiment (e.g., in the previous section) partitioning of the sums of squares (<span class="math inline">\(SS\)</span>) is additive:</p>
<p><span class="math display">\[SS_\text{Treatment} = SS_\text{Disease} + SS_\text{Organ} + SS_\text{Disease:Organ}.\]</span></p>
<p>The order in which the main effects are added to the model does not matter. <strong>However</strong>, for an <strong>unbalanced design</strong> this is not the case as the sums of squares are calculated <strong>sequentially</strong>. Note that sequentially calculated <span class="math inline">\(SS\)</span> are known as Type I <span class="math inline">\(SS\)</span>.</p>
</div>
<div id="sums-of-squares-ss" class="section level3">
<h3>Sums of squares (<span class="math inline">\(SS\)</span>)</h3>
<div id="sequential-type-i-ss" class="section level4">
<h4>Sequential (Type I <span class="math inline">\(SS\)</span>)</h4>
<p>As a term enters the model its <span class="math inline">\(SS\)</span> is calculated, which is then subtracted from the total <span class="math inline">\(SS\)</span>. This then reduces the available <span class="math inline">\(SS\)</span> for the next term entering the model. When treatment combinations in a factorial experiment are unequally replicated, their effects are not mutually independent, so that the order in which terms enter the model matters.</p>
<p>Considering the data above if we include <code>Disease</code> as a main effect first (i.e., <code>Disease*Organ</code>) then the <span class="math inline">\(SS_\text{Disease}\)</span> is calculated first <strong>ignoring</strong> the <code>Organ</code> main effect. Here, some <code>Organ</code> information is confounded with <code>Disease</code> information (i.e., variation due to <code>Organ</code> confounded by the variation due to <code>Disease</code>). Then <span class="math inline">\(SS_\text{Organ}\)</span> are calculated having been adjusted for the <code>Diease</code> main effect. This now only contains <code>Organ</code> information (i.e., variation due to <code>Organ</code> effect) since all the <code>Disease</code> information was eliminated in previous step. Finally, <span class="math inline">\(SS_\text{Disease:Organ}\)</span> are calculated adjusted for both <span class="math inline">\(SS_\text{Disease}\)</span> and <span class="math inline">\(SS_\text{Organ}\)</span>. Here, there is no information left relating to <code>Disease</code> or <code>Organ</code> main effects.</p>
<p>What does this look like?</p>
<p>For <code>Disease*Organ</code> we calculate <span class="math inline">\(SS_\text{Disease}\)</span> ignoring any <code>Organ</code> effect (if you are unsure what each line of code is doing I suggest you run it line by line to see what's being done at each step).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">unbalanced_nafree <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">grand_mean =</span> <span class="kw">mean</span>(logAUC)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">group_by</span>(Disease) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">n</span>(),
         <span class="dt">treatment_mean =</span> <span class="kw">mean</span>(logAUC),
         <span class="dt">grand_mean =</span> <span class="kw">mean</span>(grand_mean)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ss_disease =</span> n <span class="op">*</span><span class="st"> </span>(treatment_mean <span class="op">-</span><span class="st"> </span>grand_mean)<span class="op">^</span><span class="dv">2</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">pull</span>(ss_disease) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">sum</span>()</code></pre></div>
<pre><code>## [1] 7.110201</code></pre>
<p>This matches, as we'd expect, <span class="math inline">\(SS_\text{Disease}\)</span> calculated from the <code>Disease*Organ</code> model above.</p>
<p>But, that about the sequential <span class="math inline">\(SS\)</span>, a simple way to think about this is in terms of sequential models:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Null model.
fit.null &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span><span class="dv">1</span>,  <span class="dt">data =</span> unbalanced_nafree)
## Only Factor Disease.
fit.a &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease,  <span class="dt">data =</span> unbalanced_nafree)
## Factors Disease and Organ.
fit.ab &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease <span class="op">+</span><span class="st"> </span>Organ,  <span class="dt">data =</span> unbalanced_nafree)
## Factors Disease and Organ with interaction.
fit.abi &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Disease<span class="op">*</span>Organ,  <span class="dt">data =</span> unbalanced_nafree)
## ANOVA table, as above
<span class="kw">anova</span>(fit.abi)</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##               Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Disease        1 7.1102  7.1102 18.4955 0.01264 *
## Organ          1 3.1149  3.1149  8.1027 0.04656 *
## Disease:Organ  1 0.0913  0.0913  0.2376 0.65145  
## Residuals      4 1.5377  0.3844                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## First line.
<span class="kw">sum</span>(<span class="kw">residuals</span>(fit.null)<span class="op">^</span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(<span class="kw">residuals</span>(fit.a)<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 7.110201</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Second line.
<span class="kw">sum</span>(<span class="kw">residuals</span>(fit.a)<span class="op">^</span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(<span class="kw">residuals</span>(fit.ab)<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 3.114926</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Third line.
<span class="kw">sum</span>(<span class="kw">residuals</span>(fit.ab)<span class="op">^</span><span class="dv">2</span>) <span class="op">-</span><span class="st"> </span><span class="kw">sum</span>(<span class="kw">residuals</span>(fit.abi)<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 0.09134405</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Final line.
<span class="kw">sum</span>(<span class="kw">residuals</span>(fit.abi)<span class="op">^</span><span class="dv">2</span>)</code></pre></div>
<pre><code>## [1] 1.537717</code></pre>
</div>
<div id="type-ii-ss" class="section level4">
<h4>Type II <span class="math inline">\(SS\)</span></h4>
<p>Rather than calculating <span class="math inline">\(SS\)</span> sequentially we can calculate the <span class="math inline">\(SS\)</span> for a given effect adjusting for all other effects listed in the model. This means that the <span class="math inline">\(SS_\text{A}\)</span> and <span class="math inline">\(SS_\text{B}\)</span> main effects will both be adjusted for each other (since neither contains the other), but will not be adjusted for <span class="math inline">\(SS_\text{A:B}\)</span> (since it contains both A and B). <span class="math inline">\(SS_\text{A:B}\)</span> will be adjusted for both main effects.</p>
<p>In our example above <span class="math inline">\(SS_\text{Disease}\)</span> and <span class="math inline">\(SS_\text{Organ}\)</span> main effects will both be adjusted for each other, but will not be adjusted for <span class="math inline">\(SS_\text{A:B}\)</span> and <span class="math inline">\(SS_\text{Disease:Organ}\)</span> will be adjusted for both main effects.</p>
<p>We can calculate the Type II <span class="math inline">\(SS\)</span> table in <code>R</code> buy either</p>
<ol style="list-style-type: decimal">
<li>Extracting the main effect rows that have been adjusted for the other model terms from two Type I <span class="math inline">\(SS\)</span> tables (each one having the terms specified in a different order):</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Type II Organ SS
<span class="kw">anova</span>(fac_lm)[<span class="dv">2</span>, ]</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##       Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Organ  1 3.1149  3.1149  8.1027 0.04656 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Type II Disease SS
<span class="kw">anova</span>(fac_lm_<span class="dv">2</span>)[<span class="dv">2</span>, ]</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##         Df Sum Sq Mean Sq F value  Pr(&gt;F)  
## Disease  1  4.496   4.496  11.695 0.02678 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## Type II Organ:Disease/Disease:Organ
<span class="kw">anova</span>(fac_lm_<span class="dv">2</span>)[<span class="dv">3</span>, ]</code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Response: logAUC
##               Df   Sum Sq  Mean Sq F value Pr(&gt;F)
## Organ:Disease  1 0.091344 0.091344  0.2376 0.6514</code></pre>
<p>or,</p>
<ol start="2" style="list-style-type: decimal">
<li>Using an inbuilt <code>R</code> function (does not matter which order the model has the terms specified):</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">car<span class="op">::</span><span class="kw">Anova</span>(fac_lm, <span class="dt">type =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: logAUC
##               Sum Sq Df F value  Pr(&gt;F)  
## Disease       4.4960  1 11.6953 0.02678 *
## Organ         3.1149  1  8.1027 0.04656 *
## Disease:Organ 0.0913  1  0.2376 0.65145  
## Residuals     1.5377  4                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><strong>Note:</strong> Type III <span class="math inline">\(SS\)</span> and beyond are not covered in this course but I would recommend reading <a href="https://besjournals.onlinelibrary.wiley.com/doi/10.1111/j.1365-2656.2009.01634.x">this recent paper</a> for an intuitive overview.</p>
</div>
<div id="marginal-means" class="section level4">
<h4>Marginal means</h4>
<p><strong>Balanced design</strong></p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-103">Table 1: </span>logAUC data from a balanced design
</caption>
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
logAUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
9.40
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
8.83
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
10.33
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
9.74
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.98
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7.92
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
9.37
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
8.69
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
11.31
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7.01
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
9.29
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Grand mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9.447
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-103">Table 1: </span>Cell means
</caption>
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
log AUC mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7.873
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
9.990
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
9.823
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.100
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-103">Table 1: </span>Marginal (organ) mean
</caption>
<thead>
<tr>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
log AUC mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
8.848
</td>
</tr>
<tr>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.045
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-103">Table 1: </span>Marginal (disease) mean
</caption>
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:right;">
log AUC mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:right;">
8.932
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:right;">
9.962
</td>
</tr>
</tbody>
</table>
<p><strong>Unbalanced design</strong> (Unequal replication due to missing data)</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-104">Table 2: </span>logAUC data from an unbalanced design
</caption>
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
logAUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.49
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
9.74
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.98
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7.92
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
9.37
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
8.69
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
NA
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7.01
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
9.29
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;">
Grand mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
9.186
</td>
</tr>
</tbody>
</table>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-106">Table 3: </span>Cell means
</caption>
<thead>
<tr>
<th style="text-align:left;">
Disease
</th>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
log AUC mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
7.873
</td>
</tr>
<tr>
<td style="text-align:left;">
Diabetic
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
9.330
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
9.740
</td>
</tr>
<tr>
<td style="text-align:left;">
Healthy
</td>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.735
</td>
</tr>
</tbody>
</table>
<p>Everything is as we'd expect up until now, but what about the marginal means? The, perhaps, most obvious way would be to do the following (i.e., ignore subgroups, hence give all observations equal weight)?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">unbalanced_nafree <span class="op">%&gt;%</span>
<span class="st">   </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">c</span>(Disease, logAUC)) <span class="op">%&gt;%</span>
<span class="st">   </span><span class="kw">group_by</span>(Disease) <span class="op">%&gt;%</span>
<span class="st">   </span><span class="kw">summarise</span>(<span class="dt">Mean =</span> <span class="kw">mean</span>(logAUC))</code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   Disease   Mean
##   &lt;fct&gt;    &lt;dbl&gt;
## 1 Diabetic  8.46
## 2 Healthy  10.4</code></pre>
<p>However, as a result of this the means are <strong>biased</strong> towards groups with greater replication! To avoid this we give the subgroups (<code>Organ</code>) cell means equal weight (this is sometimes called the <em>least squares</em> mean):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">unbalanced_nafree <span class="op">%&gt;%</span>
<span class="st">   </span>dplyr<span class="op">::</span><span class="kw">select</span>(<span class="kw">c</span>(Disease, Organ, logAUC)) <span class="op">%&gt;%</span>
<span class="st">   </span><span class="kw">group_by</span>(Organ, Disease) <span class="op">%&gt;%</span>
<span class="st">     </span><span class="kw">mutate</span>(<span class="dt">n =</span> <span class="kw">n</span>()) <span class="op">%&gt;%</span><span class="st"> </span>## count observations in each group
<span class="st">    </span>## then calculate weighted mean based on the no. observations
<span class="st">   </span><span class="kw">summarise</span>(<span class="dt">weighted_mean =</span> <span class="kw">weighted.mean</span>(logAUC, <span class="dt">w =</span> <span class="dv">1</span><span class="op">/</span>n)) <span class="op">%&gt;%</span>
<span class="st">     </span><span class="kw">group_by</span>(Disease) <span class="op">%&gt;%</span><span class="st"> </span>## calculate mean of weighted means
<span class="st">     </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(weighted_mean))</code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   Disease   mean
##   &lt;fct&gt;    &lt;dbl&gt;
## 1 Diabetic  8.60
## 2 Healthy  10.2</code></pre>
<p>Now see if you can do the same across <code>Organ</code> to get</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-109">Table 4: </span>Marginal (organ) means
</caption>
<thead>
<tr>
<th style="text-align:left;">
Organ
</th>
<th style="text-align:right;">
mean
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
innerLV
</td>
<td style="text-align:right;">
8.807
</td>
</tr>
<tr>
<td style="text-align:left;">
outerLV
</td>
<td style="text-align:right;">
10.032
</td>
</tr>
</tbody>
</table>
<p><strong>What does all of this tell us?</strong> When calculating marginal means for unbalanced designs we need to be careful! Luckily there are inbuilt functions in <code>R</code> that do this correctly for us! See the next section for an example using the <code>predictmeans</code> function from the <code>predictmeans</code> package.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="some-basic-experimental-designs.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="multiple-comparisons.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
