<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Multiple comparisons | Advanced Biological Data Analysis</title>
  <meta name="description" content="Multiple comparisons | Advanced Biological Data Analysis" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Multiple comparisons | Advanced Biological Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Multiple comparisons | Advanced Biological Data Analysis" />
  
  
  

<meta name="author" content="University of Auckland" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modelling-experimental-data.html"/>
<link rel="next" href="linear-mixed-effect-models-lmms.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Nau mai, haere mai. Welcome to BIOSCI 738</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html"><i class="fa fa-check"></i>Useful information to set you up for your semester</a><ul>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#course-outline"><i class="fa fa-check"></i>Course outline</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#learning-outcomes"><i class="fa fa-check"></i>Learning Outcomes</a></li>
<li class="chapter" data-level="" data-path="useful-information-to-set-you-up-for-your-semester.html"><a href="useful-information-to-set-you-up-for-your-semester.html#course-summary"><i class="fa fa-check"></i>Course summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-1.html"><a href="module-1.html"><i class="fa fa-check"></i>Module 1</a><ul>
<li><a href="r-and-rstudio.html#r-and-rstudio"><code>R</code> and <code>RStudio</code></a><ul>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html"><i class="fa fa-check"></i>Installing R and RStudio</a></li>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#getting-started"><i class="fa fa-check"></i>Getting started</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html"><i class="fa fa-check"></i>Reproducible research</a><ul>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html#project-oriented-workflow-good-practice"><i class="fa fa-check"></i>Project-oriented workflow: good practice</a></li>
<li><a href="reproducible-research.html#version-control-with-git-and-github">Version control with <code>git</code> and GitHub</a></li>
</ul></li>
<li><a href="your-data-and-r.html#your-data-and-r">Your data and <code>R</code></a><ul>
<li><a href="your-data-and-r.html#reading-in-data-from-a-.csv-file">Reading in data from a <code>.csv</code> file</a></li>
<li class="chapter" data-level="" data-path="your-data-and-r.html"><a href="your-data-and-r.html"><i class="fa fa-check"></i>Explore your data</a></li>
<li><a href="your-data-and-r.html#the-pipe-operator">The pipe operator <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i>Data wrangling</a><ul>
<li><a href="data-wrangling.html#introuducing-the-palmer-penguins">Introuducing the <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0090081">Palmer penguins</a></a></li>
<li><a href="data-wrangling.html#common-dataframe-manipulations-in-the-tidyverse-using-dplyr-and-tidyr">Common dataframe manipulations in the <code>tidyverse</code>, using <code>dplyr</code> and <code>tidyr</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html"><i class="fa fa-check"></i>Data visualiation (data viz)</a><ul>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#exploratory-plots"><i class="fa fa-check"></i>Exploratory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#explanatory-plots"><i class="fa fa-check"></i>Explanatory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#ten-simple-rules-for-better-figures"><i class="fa fa-check"></i>Ten Simple Rules for Better Figures</a></li>
<li><a href="data-visualiation-data-viz.html#ggplot2"><code>ggplot2</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html"><i class="fa fa-check"></i>Māori Data Sovereignty principles</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-2.html"><a href="module-2.html"><i class="fa fa-check"></i>Module 2</a><ul>
<li class="chapter" data-level="" data-path="key-satistical-concepts.html"><a href="key-satistical-concepts.html"><i class="fa fa-check"></i>Key satistical concepts</a></li>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html"><i class="fa fa-check"></i>Bootstrap resampling</a><ul>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html#example-constructing-bootstrap-confidence-intervals"><i class="fa fa-check"></i>Example: constructing bootstrap confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html"><i class="fa fa-check"></i>Permutation and randomisation tests</a><ul>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html#a-permutation-test-jackal-mandible-lengths"><i class="fa fa-check"></i>A permutation test: Jackal mandible lengths</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resampling-procedures-the-differences.html"><a href="resampling-procedures-the-differences.html"><i class="fa fa-check"></i>Resampling procedures, the differences</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html"><i class="fa fa-check"></i>Hypothesis testing: key terms</a><ul>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#p-values"><i class="fa fa-check"></i>😱 p-values 😱</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i>Type I and Type II errors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html"><i class="fa fa-check"></i>Parametric hypothesis tests</a><ul>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-sample-t-test"><i class="fa fa-check"></i>One-Sample t-test</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#differences-between-two-means"><i class="fa fa-check"></i>Differences between two means</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-way-analysis-of-variance-anova"><i class="fa fa-check"></i>One-Way Analysis of Variance (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i>Linear regression</a><ul>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#some-mathematical-notation"><i class="fa fa-check"></i>Some mathematical notation</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#modeling-bill-depth"><i class="fa fa-check"></i>Modeling Bill Depth</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#single-continuous-variable"><i class="fa fa-check"></i>Single continuous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#one-factor-and-a-continous-variable"><i class="fa fa-check"></i>One factor and a continous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li><a href="model-formula-syntax-in-r.html#model-formula-syntax-in-r">Model formula syntax in <code>R</code></a><ul>
<li class="chapter" data-level="" data-path="model-formula-syntax-in-r.html"><a href="model-formula-syntax-in-r.html"><i class="fa fa-check"></i>Other possible models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html"><i class="fa fa-check"></i>Model diagnostics for a linear model</a><ul>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#marginal-predictions"><i class="fa fa-check"></i>Marginal predictions</a></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#model-selection"><i class="fa fa-check"></i>Model selection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html"><i class="fa fa-check"></i>Inference for a linear model</a><ul>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#point-prediction"><i class="fa fa-check"></i>Point prediction</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#confidence-intervals-for-parameters"><i class="fa fa-check"></i>Confidence intervals for parameters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-3.html"><a href="module-3.html"><i class="fa fa-check"></i>Module 3</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html"><i class="fa fa-check"></i>Introduction to the design and analysis of experiments</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#key-phrases"><i class="fa fa-check"></i>Key phrases</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#the-three-key-principles"><i class="fa fa-check"></i>The three key principles:</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#replication"><i class="fa fa-check"></i>Replication</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#randomization"><i class="fa fa-check"></i>Randomization</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#blocking"><i class="fa fa-check"></i>Blocking</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#setting-up-an-experiment"><i class="fa fa-check"></i>Setting up an experiment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html"><i class="fa fa-check"></i>Some basic experimental designs</a><ul>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#completely-randomised-design-crd"><i class="fa fa-check"></i>Completely randomised design (CRD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#randomised-complete-block-design-rcbd"><i class="fa fa-check"></i>Randomised complete block design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#factorial-design"><i class="fa fa-check"></i>Factorial design</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html"><i class="fa fa-check"></i>Modelling experimental data</a><ul>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-completely-randomised-design-crd-as-a-linear-model"><i class="fa fa-check"></i>A completely randomised design (CRD) as a linear model</a></li>
<li><a href="modelling-experimental-data.html#analysis-of-a-crd-in-r">Analysis of a CRD in <code>R</code></a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-factorial-experiment-as-a-crd"><i class="fa fa-check"></i>A Factorial experiment (as a CRD)</a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#unqual-replications-unbalanced-design"><i class="fa fa-check"></i>Unqual replications (unbalanced design)</a></li>
<li><a href="modelling-experimental-data.html#sums-of-squares-ss">Sums of squares (<span class="math inline">\(SS\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i>Multiple comparisons</a><ul>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#adjustments-for-multiple-testing"><i class="fa fa-check"></i>Adjustments for multiple testing</a></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#classification-of-multiple-hypothesis-tests"><i class="fa fa-check"></i>Classification of multiple hypothesis tests</a></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#multiple-comparison-procedures"><i class="fa fa-check"></i>Multiple comparison procedures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html"><i class="fa fa-check"></i>Linear mixed-effect models (LMMs)</a><ul>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-randomised-controlled-block-design-rcbd"><i class="fa fa-check"></i>A Randomised Controlled Block Design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-split-plot-design"><i class="fa fa-check"></i>A Split-plot design</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-repeated-measures-design"><i class="fa fa-check"></i>A repeated measures design</a></li>
<li><a href="linear-mixed-effect-models-lmms.html#animal-as-a-random-effect-1"><code>Animal</code> as a random effect</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-4.html"><a href="module-4.html"><i class="fa fa-check"></i>Module 4</a><ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html"><i class="fa fa-check"></i>Least Squares Estimation</a><ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#some-basic-matrix-algebra"><i class="fa fa-check"></i>Some basic matrix algebra</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#linear-least-squares"><i class="fa fa-check"></i>Linear least squares</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#matrix-representation-of-a-crd"><i class="fa fa-check"></i>Matrix representation of a CRD</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#a-numeric-example"><i class="fa fa-check"></i>A numeric example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html"><i class="fa fa-check"></i>Maximum likelkihood estimation</a><ul>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#differeniation-rules"><i class="fa fa-check"></i>Differeniation rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#logarithn-rules"><i class="fa fa-check"></i>Logarithn rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-binomial-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Binomial distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-crd"><i class="fa fa-check"></i>Maximum likelihood estimation for a CRD</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximising-the-log-likelihood"><i class="fa fa-check"></i>Maximising the log-likelihood</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-poisson-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Poisson distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelkihood-estimation.html"><a href="maximum-likelkihood-estimation.html#maximum-likelihood-estimation-for-a-continuous-random-variable"><i class="fa fa-check"></i>Maximum likelihood estimation for a continuous random variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html"><i class="fa fa-check"></i>Introduction to Bayesian statistics</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#conditional-probability"><i class="fa fa-check"></i>Conditional probability</a></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#bayes-rule"><i class="fa fa-check"></i>Bayes' rule</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-5.html"><a href="module-5.html"><i class="fa fa-check"></i>Module 5</a><ul>
<li class="chapter" data-level="" data-path="introduction-to-generalised-linear-models-glms.html"><a href="introduction-to-generalised-linear-models-glms.html"><i class="fa fa-check"></i>Introduction to generalised linear models (GLMs)</a></li>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i>Poisson regression</a><ul>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html#an-example-bird-abundance"><i class="fa fa-check"></i>An example: bird abundance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i>Logistic regression</a><ul>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html#an-example-lobsters"><i class="fa fa-check"></i>An example: lobsters</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a-summary-of-glms.html"><a href="a-summary-of-glms.html"><i class="fa fa-check"></i>A summary of GLMs</a></li>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html"><i class="fa fa-check"></i>Generalised linear mixed-effects models (GLMMMs)</a><ul>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html#fitting-a-glmm"><i class="fa fa-check"></i>Fitting a GLMM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-6.html"><a href="module-6.html"><i class="fa fa-check"></i>Module 6</a><ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i>Clustering</a><ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#divisive-partitioning-methods."><i class="fa fa-check"></i>Divisive (partitioning) methods.</a></li>
<li><a href="clustering.html#k-means-an-example-using-the-palmerpenguins-data">K-means: an example using the <code>palmerpenguins</code> data</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-agglomerative-clustering."><i class="fa fa-check"></i>Hierarchical agglomerative clustering.</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-clustering-an-example"><i class="fa fa-check"></i>Hierarchical clustering: an example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html"><i class="fa fa-check"></i>Principal Component Analysis (PCA)</a><ul>
<li><a href="principal-component-analysis-pca.html#examples-in-r">Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html"><i class="fa fa-check"></i>Multidimensional Scaling (MDS)</a><ul>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#metric-scaling"><i class="fa fa-check"></i>Metric Scaling</a></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#correspondence-analysis-ca"><i class="fa fa-check"></i>Correspondence Analysis (CA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="non-metric-multidimensional-scaling.html"><a href="non-metric-multidimensional-scaling.html"><i class="fa fa-check"></i>Non-metric Multidimensional Scaling</a><ul>
<li><a href="non-metric-multidimensional-scaling.html#examples-in-r-2">Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html"><i class="fa fa-check"></i>Linear Discriminant Analysis (LDA)</a><ul>
<li><a href="linear-discriminant-analysis-lda.html#example-in-r">Example in <code>R</code></a></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Biological Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="multiple-comparisons" class="section level2">
<h2>Multiple comparisons</h2>
<p>Recall that <strong>each</strong> time we carry out a hypothesis test the probability we get a false positive result (type I error) is given by <span class="math inline">\(\alpha\)</span> (the <em>level of significance</em> we choose).</p>
<p>When we have <strong>multiple comparisons</strong> to make we should then control the <strong>Type I</strong> error rate across the entire <em>family</em> of tests under consideration, i.e., control the Family-Wise Error Rate (FWER); this ensures that the risk of making at least one <strong>Type I</strong> error among the family of comparisons in the experiment is <span class="math inline">\(\alpha\)</span>.</p>
<table>
<thead>
<tr class="header">
<th>State of Nature</th>
<th>Don't reject <span class="math inline">\(H_0\)</span></th>
<th>reject <span class="math inline">\(H_0\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(H_0\)</span> is true</td>
<td>✅</td>
<td>Type I error</td>
</tr>
<tr class="even">
<td><span class="math inline">\(H_0\)</span> is false</td>
<td>Type II error</td>
<td>✅</td>
</tr>
</tbody>
</table>
<p>The <strong>familywise error rate (FWER)</strong> is the risk of making at least one <strong>Type I</strong> error among the family of comparisons in the experiment. Now let's consider carrying out <span class="math inline">\(m\)</span> independent t-tests and let for any single test, let Pr(commit a Type 1 error) <span class="math inline">\(= \alpha_c\)</span> be the <strong>per comparison error rate (PCER)</strong>. So for a single test the probability a correct decision is made is <span class="math inline">\(1 - \alpha_c\)</span>. Therefore for <span class="math inline">\(m\)</span> <strong>independent</strong> t-tests the probability of committing no Type I errors is <span class="math inline">\((1 - \alpha_c)^m\)</span> and the probability of committing at least one Type I error is <span class="math inline">\(1 -(1 - \alpha_c)^m = \alpha_F\)</span> which is the upper limit of the FWER.</p>
<p>The <strong>False Discovery Rate (FDR)</strong> controls the expected (mean) proportion of false discoveries among the <span class="math inline">\(R\)</span> (out of <span class="math inline">\(m\)</span>) hypotheses declared significant.</p>
<p>Consider testing <span class="math inline">\(m\)</span> null hypotheses with corresponding p-values <span class="math inline">\(P_1, P_2,...,P_m\)</span>; we then order then so that <span class="math inline">\(P_{(1)} &lt; P_{(2)} &lt;...&lt;P_{(m)}\)</span> (where <span class="math inline">\(P_{(i)}\)</span> is the <span class="math inline">\(i^{th}\)</span> largest <span class="math inline">\(i=1,...,m\)</span>). The <span class="math inline">\(i^{th}\)</span> ordered p-value is calculated as <span class="math inline">\(\frac{i}{m}q^*\)</span> and the <span class="math inline">\(i^{th}\)</span> null hypothesis is rejected if <span class="math inline">\(P_i \leq \frac{i}{m}q^*\)</span></p>
<p><img src="_main_files/figure-html/alp-1.png" width="960" style="display: block; margin: auto;" /></p>
<div id="adjustments-for-multiple-testing" class="section level3">
<h3>Adjustments for multiple testing</h3>
<p>Calculating 95% confidence intervals for pairwise comparisons is similar to the procedure discussed in module 2:</p>
<p><span class="math display">\[\text{95% CI} = \text{estimate} \pm (\text{scale factor} \times \text{standard error}_\text{of estimate}).\]</span> For the 95% CI for pairwise comparisons of means this becomes</p>
<p><span class="math display">\[\text{95% CI} = \text{difference} \pm (\text{scale factor} \times \text{SED}),\]</span> where SED is the standard error of the difference (which depends on group replication). The choice of scale factor depends on what adjustments we might want to make. Below we cover three common adjustments. Specifically where (scale factor × SED) is the 1) Fisher correction LSD, 2) Bonferroni correction LSD, and 3) Tukey's HSD.</p>
<div id="fishers-least-significant-difference-lsd" class="section level4">
<h4>Fisher’s Least Significant Difference (LSD)</h4>
<p>To calculate the LSD the <span class="math inline">\(t\)</span>-distribution is used, specifically the <span class="math display">\[t_{\alpha = \frac{\alpha_c}{2}, \text{df} = N - m}\]</span> distribution, where <span class="math inline">\(N\)</span> is the number of observations and <span class="math inline">\(m\)</span> is the number of treatment groups. To obtain the critical value for $_c = 0.05 $, <span class="math inline">\(N = 12\)</span> and <span class="math inline">\(m = 3\)</span> the following code can be used in <code>R</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="dt">p =</span> <span class="fl">0.05</span><span class="op">/</span><span class="dv">2</span>,<span class="dt">df =</span> <span class="dv">12</span> <span class="op">-</span><span class="st"> </span><span class="dv">3</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 2.262157</code></pre>
<p>Fisher's LSD is then <span class="math display">\[t_{\alpha = \frac{\alpha_c}{2}, \text{df} = N - m} \times \text{SED}.\]</span></p>
<p>Here we carry out post-hoc tests only if the ANOVA F-test is <em>significant</em>. If so declare significant <span class="math inline">\(100\alpha\%\)</span> any pairwise difference &gt; LSD. This does <strong>not</strong> control the FWER.</p>
</div>
<div id="bonferroni-correction" class="section level4">
<h4>Bonferroni correction</h4>
<p>To calculate Bonferroni correction the <span class="math inline">\(t\)</span>-distribution is used, specifically the <span class="math display">\[t_{\alpha = \frac{\alpha_c}{2 \times k}, \text{df} = N - m}\]</span> distribution, where <span class="math inline">\(N\)</span> is the number of observations, <span class="math inline">\(m\)</span> is the number of treatment groups, and <span class="math inline">\(k = {m \choose 2}\)</span> is the number of pairwise comparisons being made.</p>
<p>To obtain the critical value for $_c = 0.05 $, <span class="math inline">\(N = 12\)</span> and <span class="math inline">\(m = 3\)</span> the following code can be used in <code>R</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qt</span>(<span class="dt">p =</span> <span class="fl">0.05</span><span class="op">/</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">choose</span>(<span class="dv">3</span>,<span class="dv">2</span>)),<span class="dt">df =</span> <span class="dv">12</span> <span class="op">-</span><span class="st"> </span><span class="dv">3</span>, <span class="dt">lower.tail =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>## [1] 2.933324</code></pre>
<p>Bonferroni's LSD is then <span class="math display">\[t_{\alpha = \frac{\alpha_c}{2 \times k}, \text{df} = N - m} \times \text{SED}.\]</span></p>
<p>Here we reject the <span class="math inline">\(H_0\)</span> for which the p-value, <em>p-val</em>, is <em>p-val</em> <span class="math inline">\(&lt; \alpha_c = \frac{\alpha_f}{n_c}\)</span> where <span class="math inline">\(\alpha_f\)</span> is the FWER and <span class="math inline">\(n_c\)</span> is the number of pairwise comparisons. However, this makes <strong>no</strong> assumptions about independence between tests.</p>
</div>
<div id="tukeys-honest-significant-difference-hsd" class="section level4">
<h4>Tukey’s Honest Significant Difference (HSD)</h4>
<p>This compares the mean of every treatment with the mean of every other treatment and uses a <em>studentised range</em> distribution compared with a <span class="math inline">\(t\)</span>-distribution for Fisher's LSD and the Bonferroni correction. Therefore to calculate the HSD the <em>studentised range</em> distribution is used, specifically the <span class="math display">\[q_{ 1- \alpha_c, m, \text{df} = N - m}\]</span> distribution, where <span class="math inline">\(N\)</span> is the number of observations, <span class="math inline">\(m\)</span> is the number of treatment groups, and <span class="math inline">\(q_{\alpha,m,\text{df}}\)</span> quantile of the studendised distribution.</p>
<p>To obtain the critical value for $_c = 0.05 $, <span class="math inline">\(N = 12\)</span> and <span class="math inline">\(m = 3\)</span> the following code can be used in <code>R</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">qtukey</span>(<span class="dt">p =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.05</span>, <span class="dt">nmeans =</span> <span class="dv">3</span>, <span class="dt">df =</span> <span class="dv">12</span> <span class="op">-</span><span class="st"> </span><span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] -2.948492</code></pre>
<p>Tukey's HSD is given by <span class="math display">\[\frac{q_{ 1 - \alpha_c, m, \text{df} = N - m}}{\sqrt{2}} \times \sqrt{\frac{2\hat{\sigma}^2}{n}}.\]</span> Here <span class="math inline">\(\hat{\sigma}^2\)</span> is the Residual Mean Square Error and <span class="math inline">\(n\)</span> is the assumed equal number of replicates in each group.</p>
</div>
</div>
<div id="classification-of-multiple-hypothesis-tests" class="section level3">
<h3>Classification of multiple hypothesis tests</h3>
<p>Suppose we have a number <span class="math inline">\(m\)</span> of null hypotheses, <span class="math inline">\(H_1, H_2, ..., H_m\)</span>. Using the traditional parlance we reject the null hypothesis if the test is declared significant and have no evidence to reject the null hypothesis if the test is &quot;not significant&quot;. Now, summing each type of outcome over all <span class="math inline">\(H_i (i = 1.,..,m)\)</span> yields the following random variables:</p>
<table>
<thead>
<tr class="header">
<th></th>
<th>Null hypothesis is true (H0)</th>
<th>Alternative hypothesis is true (HA)</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Test is declared significant</td>
<td>V</td>
<td>S</td>
<td>R</td>
</tr>
<tr class="even">
<td>Test is declared non-significant</td>
<td>U</td>
<td>T</td>
<td>m - R</td>
</tr>
<tr class="odd">
<td>Total</td>
<td><span class="math inline">\(m_{0}\)</span></td>
<td><span class="math inline">\(m - m_0\)</span></td>
<td>m</td>
</tr>
</tbody>
</table>
<ul>
<li><span class="math inline">\(m\)</span> is the total number hypotheses tested</li>
<li><span class="math inline">\(m_{0}\)</span> is the number of true null hypotheses, an unknown parameter</li>
<li><span class="math inline">\(m - m_0\)</span> is the number of true alternative hypotheses</li>
<li><span class="math inline">\(V\)</span> is the number of false positives (<strong>Type I error</strong>) (also called <em>false discoveries</em>)</li>
<li><span class="math inline">\(S\)</span> is the number of true positives (also called <em>true discoveries</em>)</li>
<li><span class="math inline">\(T\)</span> is the number of false negatives (<strong>Type II error</strong>)</li>
<li><span class="math inline">\(U\)</span> is the number of true negatives</li>
<li><span class="math inline">\(R=V+S\)</span> is the number of rejected null hypotheses (also called <em>discoveries</em>, either true or false)</li>
</ul>
</div>
<div id="multiple-comparison-procedures" class="section level3">
<h3>Multiple comparison procedures</h3>
<p>Recall the CRD <code>rats</code> data</p>
<table class=" lightable-classic" style="font-family: Cambria; width: auto !important; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Surgery
</th>
<th style="text-align:right;">
Rat
</th>
<th style="text-align:right;">
logAUC
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
8.49
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
8.20
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9.08
</td>
</tr>
<tr>
<td style="text-align:left;">
C
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8.07
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10.24
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
7.72
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9.34
</td>
</tr>
<tr>
<td style="text-align:left;">
P
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8.50
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
11.31
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
12.69
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
11.37
</td>
</tr>
<tr>
<td style="text-align:left;">
S
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
10.82
</td>
</tr>
</tbody>
</table>
<p>You can read this data directly into <code>R</code> using</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rats &lt;-<span class="st"> </span>readr<span class="op">::</span><span class="kw">read_csv</span>(<span class="st">&quot;https://raw.githubusercontent.com/STATS-UOA/databunker/master/data/crd_rats_data.csv&quot;</span>)</code></pre></div>
<p>To use <code>predictmeans</code> later on we have to ensure that the relevant variables are coded as factors:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rats &lt;-<span class="st"> </span>rats <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Surgery =</span> <span class="kw">as.factor</span>(Surgery))</code></pre></div>
<p>We can fit a linear model using <code>lm()</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">rats_lm &lt;-<span class="st"> </span><span class="kw">lm</span>(logAUC <span class="op">~</span><span class="st"> </span>Surgery, <span class="dt">data =</span> rats)
<span class="kw">coef</span>(rats_lm)</code></pre></div>
<pre><code>## (Intercept)    SurgeryP    SurgeryS 
##      8.4600      0.4900      3.0875</code></pre>
<p>Our fitted model is therefore</p>
<p><span class="math display">\[
\begin{aligned}
\operatorname{\widehat{logAUC}} &amp;= 8.46 + 0.49(\operatorname{Surgery}_{\operatorname{P}}) + 3.09(\operatorname{Surgery}_{\operatorname{S}})
\end{aligned}
\]</span></p>
<p><strong>Using</strong> <code>predictmeans</code></p>
<p>By default Fisher's comparisons are made.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pm &lt;-<span class="st"> </span>predictmeans<span class="op">::</span><span class="kw">predictmeans</span>(rats_lm , <span class="dt">modelterm =</span> <span class="st">&quot;Surgery&quot;</span>, 
                                     <span class="dt">pairwise =</span> <span class="ot">TRUE</span>, <span class="dt">plot =</span> <span class="ot">FALSE</span>)
<span class="kw">str</span>(pm)</code></pre></div>
<pre><code>## List of 10
##  $ Predicted Means              : &#39;xtabs&#39; num [1:3(1d)] 8.46 8.95 11.55
##   ..- attr(*, &quot;dimnames&quot;)=List of 1
##   .. ..$ Surgery: chr [1:3] &quot;C&quot; &quot;P&quot; &quot;S&quot;
##   ..- attr(*, &quot;call&quot;)= language xtabs(formula = pm ~ ., data = mt[, c(&quot;pm&quot;, vars)], drop.unused.levels = TRUE)
##  $ Standard Error of Means      : Named num 0.41
##   ..- attr(*, &quot;names&quot;)= chr &quot;All means have the same Stder&quot;
##  $ Standard Error of Differences: Named num [1:3] 0.58 0.58 0.58
##   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Max.SED&quot; &quot;Min.SED&quot; &quot;Aveg.SED&quot;
##  $ LSD                          : Named num [1:3] 1.31 1.31 1.31
##   ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Max.LSD&quot; &quot;Min.LSD&quot; &quot;Aveg.LSD&quot;
##   ..- attr(*, &quot;Significant level&quot;)= num 0.05
##   ..- attr(*, &quot;Degree of freedom&quot;)= num 9
##  $ Pairwise LSDs                : num [1:3, 1:3] 0 1.31 1.31 -0.49 0 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:3] &quot;C&quot; &quot;P&quot; &quot;S&quot;
##   .. ..$ : chr [1:3] &quot;C&quot; &quot;P&quot; &quot;S&quot;
##   ..- attr(*, &quot;Significant level&quot;)= num 0.05
##   ..- attr(*, &quot;Degree of freedom&quot;)= int 9
##   ..- attr(*, &quot;Note&quot;)= chr &quot;LSDs matrix has mean differences (row-col) above the diagonal, LSDs (adjusted by &#39;none&#39; method) below the diagonal&quot;
##  $ Pairwise p-value             : num [1:3, 1:3] 0 0.4202 0.0005 -0.8446 0 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   .. ..$ : chr [1:3] &quot;C&quot; &quot;P&quot; &quot;S&quot;
##   .. ..$ : chr [1:3] &quot;C&quot; &quot;P&quot; &quot;S&quot;
##   ..- attr(*, &quot;Degree of freedom&quot;)= int 9
##   ..- attr(*, &quot;Note&quot;)= chr &quot;The matrix has t-value above the diagonal, p-value (adjusted by &#39;none&#39; method) below the diagonal&quot;
##   ..- attr(*, &quot;Letter-based representation of pairwise comparisons at significant level &#39;0.05&#39;&quot;)=&#39;data.frame&#39;:   3 obs. of  3 variables:
##   .. ..$ Treatment: chr [1:3] &quot;S&quot; &quot;P&quot; &quot;C&quot;
##   .. ..$ Mean     : num [1:3] 11.55 8.95 8.46
##   .. ..$ Group    : chr [1:3] &quot;A &quot; &quot; B&quot; &quot; B&quot;
##  $ predictmeansPlot             : NULL
##  $ predictmeansBarPlot          : NULL
##  $ mean_table                   :&#39;data.frame&#39;:   3 obs. of  7 variables:
##   ..$ Surgery        : Factor w/ 3 levels &quot;C&quot;,&quot;P&quot;,&quot;S&quot;: 1 2 3
##   ..$ Predicted means: num [1:3] 8.46 8.95 11.55
##   ..$ Standard error : num [1:3] 0.41 0.41 0.41
##   ..$ Df             : int [1:3] 9 9 9
##   ..$ LL of 95% CI   : num [1:3] 7.53 8.02 10.62
##   ..$ UL of 95% CI   : num [1:3] 9.39 9.88 12.48
##   ..$ LetterGrp      : chr [1:3] &quot;A &quot; &quot;A &quot; &quot; B&quot;
##  $ p_valueMatrix                : NULL
##  - attr(*, &quot;class&quot;)= chr &quot;pdmlist&quot;</code></pre>
<p>Let's look at some of the <code>pm</code> elements more closely:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pm<span class="op">$</span>mean_table</code></pre></div>
<pre><code>##   Surgery Predicted means Standard error Df LL of 95% CI UL of 95% CI LetterGrp
## 1       C          8.4600      0.4102531  9     7.531943     9.388057        A 
## 2       P          8.9500      0.4102531  9     8.021943     9.878057        A 
## 3       S         11.5475      0.4102531  9    10.619443    12.475557         B</code></pre>
<p>This gives us the estimated group means and associated 95% CIs. Why are the standard errors all equal?</p>
<p>But, what we'd like is the pairwise comparisons between groups. Information pertaining to this is also returned:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(pm<span class="op">$</span><span class="st">`</span><span class="dt">Pairwise p-value</span><span class="st">`</span>)</code></pre></div>
<pre><code>##        C       P       S
## C 0.0000 -0.8446 -5.3216
## P 0.4202  0.0000 -4.4770
## S 0.0005  0.0015  0.0000
## attr(,&quot;Degree of freedom&quot;)
## [1] 9
## attr(,&quot;Note&quot;)
## [1] &quot;The matrix has t-value above the diagonal, p-value (adjusted by &#39;none&#39; method) below the diagonal&quot;
## attr(,&quot;Letter-based representation of pairwise comparisons at significant level &#39;0.05&#39;&quot;)
##   Treatment    Mean Group
## 1         S 11.5475    A 
## 2         P  8.9500     B
## 3         C  8.4600     B</code></pre>
<p>This gives us the pairwise comparison statistic (the <span class="math inline">\(t\)</span>-statistic in this case) on the upper diagonal and the associated p-value's on the lower diagonal.</p>
<p>What about the 95%CI for the comparisons? Luckily <code>predictmeans</code> also returns the pairwise LSD values (Fisher's by default with <span class="math inline">\(\alpha_c = 0.05\)</span>):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pm<span class="op">$</span><span class="st">`</span><span class="dt">Pairwise LSDs</span><span class="st">`</span></code></pre></div>
<pre><code>##         C        P       S
## C 0.00000 -0.49000 -3.0875
## P 1.31247  0.00000 -2.5975
## S 1.31247  1.31247  0.0000
## attr(,&quot;Significant level&quot;)
## [1] 0.05
## attr(,&quot;Degree of freedom&quot;)
## [1] 9
## attr(,&quot;Note&quot;)
## [1] &quot;LSDs matrix has mean differences (row-col) above the diagonal, LSDs (adjusted by &#39;none&#39; method) below the diagonal&quot;</code></pre>
<p>Here, the upper diagonal matrix has the pairwise differences and the lower has the LSD values.</p>
<div id="fishers-lsd" class="section level4">
<h4>Fisher’s LSD</h4>
<p>So, we have all the information to construct the Fisher LSD 95% CIs! You could extract all the information and construct a pairwise comparison table manually, or use a pre-written function (aren't I nice to provide one!):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">url &lt;-<span class="st"> &quot;https://gist.github.com/cmjt/72f3941533a6bdad0701928cc2924b90&quot;</span>
devtools<span class="op">::</span><span class="kw">source_gist</span>(url, <span class="dt">quiet =</span> <span class="ot">TRUE</span>)
<span class="kw">comparisons</span>(pm)</code></pre></div>
<pre><code>##   Comparison Difference  SED   LSD    lwr    upr      t      p
## 1        C-P     -0.490 0.58 1.312 -1.802  0.822 -0.845 0.4202
## 2        C-S     -3.087 0.58 1.312 -4.400 -1.775 -5.322 0.0005
## 3        P-S     -2.598 0.58 1.312 -3.910 -1.285 -4.477 0.0015</code></pre>
</div>
<div id="bonferroni-correction-1" class="section level4">
<h4>Bonferroni correction</h4>
<p>To use the Bonferroni correction we must now calculate and specify the adjusted <span class="math inline">\(\alpha_b = \frac{\alpha_b}{n_c}\)</span>, in our case this is <span class="math inline">\(\frac{0.05}{{3 \choose 2}}\)</span>. We also specify <code>adj = &quot;bonferroni&quot;</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">alpha.adj &lt;-<span class="st"> </span><span class="fl">0.05</span><span class="op">/</span><span class="kw">choose</span>(<span class="dv">3</span>,<span class="dv">2</span>)
bonferroni &lt;-<span class="st">  </span>predictmeans<span class="op">::</span><span class="kw">predictmeans</span>(rats_lm , 
                                          <span class="dt">modelterm =</span> <span class="st">&quot;Surgery&quot;</span>, <span class="dt">adj =</span> <span class="st">&quot;bonferroni&quot;</span>,
                                          <span class="dt">level =</span> alpha.adj,
                                          <span class="dt">pairwise =</span> <span class="ot">TRUE</span>, <span class="dt">plot =</span> <span class="ot">FALSE</span>)
<span class="kw">comparisons</span>(bonferroni)</code></pre></div>
<pre><code>##   Comparison Difference  SED   LSD    lwr    upr      t      p
## 1        C-P     -0.490 0.58 2.101 -2.591  1.611 -0.845 1.0000
## 2        C-S     -3.087 0.58 2.101 -5.189 -0.986 -5.322 0.0014
## 3        P-S     -2.598 0.58 2.101 -4.699 -0.496 -4.477 0.0046</code></pre>
</div>
<div id="tukeys-honest-significant-difference-hsd-1" class="section level4">
<h4>Tukey’s Honest Significant Difference (HSD)</h4>
<p>Things are a bit more cumbersome when it comes to Tukey's HSD. We can specify <code>adj = &quot;tukey&quot;</code> in <code>predictmeans</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tukey &lt;-<span class="st">  </span>predictmeans<span class="op">::</span><span class="kw">predictmeans</span>(rats_lm , 
                                          <span class="dt">modelterm =</span> <span class="st">&quot;Surgery&quot;</span>, <span class="dt">adj =</span> <span class="st">&quot;tukey&quot;</span>,
                                          <span class="dt">level =</span> alpha.adj,
                                          <span class="dt">pairwise =</span> <span class="ot">TRUE</span>, <span class="dt">plot =</span> <span class="ot">FALSE</span>)
<span class="kw">names</span>(tukey)</code></pre></div>
<pre><code>## [1] &quot;Predicted Means&quot;               &quot;Standard Error of Means&quot;      
## [3] &quot;Standard Error of Differences&quot; &quot;LSD&quot;                          
## [5] &quot;Pairwise p-value&quot;              &quot;predictmeansPlot&quot;             
## [7] &quot;predictmeansBarPlot&quot;           &quot;mean_table&quot;                   
## [9] &quot;p_valueMatrix&quot;</code></pre>
<p>However, the HSD values are not returned, so we cannot calculate out pairwise CIs. <code>R</code> has an inbuilt function <code>TukeyHSD</code> that does this for us, but as we can see below the HSD values are not returned.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">TukeyHSD</span>(<span class="kw">aov</span>(logAUC<span class="op">~</span>Surgery, <span class="dt">data =</span> rats))</code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = logAUC ~ Surgery, data = rats)
## 
## $Surgery
##       diff        lwr      upr     p adj
## P-C 0.4900 -1.1298813 2.109881 0.6863267
## S-C 3.0875  1.4676187 4.707381 0.0012479
## S-P 2.5975  0.9776187 4.217381 0.0039400</code></pre>
<p>From above we saw that Tukey's HSD was given by</p>
<p><span class="math display">\[\frac{q_{1-\alpha_c, m, \text{df} = N - m}}{\sqrt{2}} \times \sqrt{\frac{2\hat{\sigma}^2}{n}}.\]</span></p>
<p>We can calculate <span class="math inline">\(q_{1 - \alpha_c, m, \text{df} = N - m}\)</span> for our data using</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">qtukey</span>(<span class="dt">p =</span> <span class="dv">1</span><span class="op">-</span><span class="st"> </span><span class="fl">0.05</span>, <span class="dt">nmeans =</span> <span class="dv">3</span>, <span class="dt">df =</span> <span class="dv">12</span> <span class="op">-</span><span class="st"> </span><span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] 3.948492</code></pre>
<p>Assuming equal replicates (<span class="math inline">\(n = 4\)</span>, with <span class="math inline">\(\hat{\sigma}^2\)</span> as above) we calculate the SED as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sqrt</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">anova</span>(rats_lm)[<span class="dv">2</span>,<span class="dv">3</span>] <span class="op">/</span><span class="st"> </span><span class="dv">4</span>)</code></pre></div>
<pre><code>## [1] 0.5801856</code></pre>
<p>Therefore, Tukey's HSD is <span class="math inline">\(\frac{3.9484922}{\sqrt{2}}\times 0.5801856 = 1.6198813.\)</span></p>
<p>To calculate the CIs we use <span class="math inline">\(\text{difference} \pm \text{HSD}\)</span>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">HSD &lt;-<span class="st"> </span>(<span class="kw">qtukey</span>(<span class="dt">p =</span> <span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="fl">0.05</span>, <span class="dt">nmeans =</span> <span class="dv">3</span>, <span class="dt">df =</span> <span class="dv">12</span> <span class="op">-</span><span class="st"> </span><span class="dv">3</span>)<span class="op">/</span><span class="kw">sqrt</span>(<span class="dv">2</span>))<span class="op">*</span><span class="kw">sqrt</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span><span class="kw">anova</span>(rats_lm)[<span class="dv">2</span>,<span class="dv">3</span>] <span class="op">/</span><span class="st"> </span><span class="dv">4</span>)
all_diffs &lt;-<span class="st"> </span><span class="kw">outer</span>(tukey<span class="op">$</span><span class="st">`</span><span class="dt">Predicted Means</span><span class="st">`</span>, tukey<span class="op">$</span><span class="st">`</span><span class="dt">Predicted Means</span><span class="st">`</span>, <span class="st">&quot;-&quot;</span>)
comparison_table &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">differences =</span> all_diffs[<span class="kw">lower.tri</span>(all_diffs)]) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">upper =</span> differences <span class="op">+</span><span class="st"> </span>HSD, <span class="dt">lower =</span> differences <span class="op">-</span><span class="st"> </span>HSD, <span class="dt">HSD =</span> HSD)
         
comparison_table</code></pre></div>
<pre><code>##   differences    upper      lower      HSD
## 1      0.4900 2.109881 -1.1298813 1.619881
## 2      3.0875 4.707381  1.4676187 1.619881
## 3      2.5975 4.217381  0.9776187 1.619881</code></pre>
<p>This matches the output from <code>TukeyHSD()</code> above!</p>
<p>What about the values returned by <code>predictmeans()</code>?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(tukey<span class="op">$</span><span class="st">`</span><span class="dt">Pairwise p-value</span><span class="st">`</span>)</code></pre></div>
<pre><code>##        C       P       S
## C 0.0000 -0.8446 -5.3216
## P 0.6863  0.0000 -4.4770
## S 0.0012  0.0039  0.0000
## attr(,&quot;Degree of freedom&quot;)
## [1] 9
## attr(,&quot;Note&quot;)
## [1] &quot;The matrix has t-value above the diagonal, p-value (adjusted by &#39;tukey&#39; method) below the diagonal&quot;
## attr(,&quot;Letter-based representation of pairwise comparisons at significant level &#39;0.0166666666666667&#39;&quot;)
##   Treatment    Mean Group
## 1         S 11.5475    A 
## 2         P  8.9500     B
## 3         C  8.4600     B</code></pre>
<p>There is an easier way to see the same pairwise contrasts using the <code>emmeans</code> function from the package of the same name and the <code>pairs</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">em &lt;-<span class="st"> </span>emmeans<span class="op">::</span><span class="kw">emmeans</span>(rats_lm, <span class="dt">specs =</span>  <span class="st">&quot;Surgery&quot;</span>)
<span class="kw">pairs</span>(em, <span class="dt">adjust =</span> <span class="st">&quot;tukey&quot;</span>)</code></pre></div>
<pre><code>##  contrast estimate   SE df t.ratio p.value
##  C - P       -0.49 0.58  9  -0.845  0.6863
##  C - S       -3.09 0.58  9  -5.322  0.0012
##  P - S       -2.60 0.58  9  -4.477  0.0039
## 
## P value adjustment: tukey method for comparing a family of 3 estimates</code></pre>
<p>This, gives us the same information as <code>predictmeans</code> but in an easier to read format (still no CIs though, we still have to calculate those ourselves!)</p>
<p>However, the <code>emmeans</code>package facilitates some nice plotting of the pairwise comparisons:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(em, <span class="dt">comparisons =</span> <span class="ot">TRUE</span>) <span class="op">+</span><span class="st"> </span><span class="kw">theme_bw</span>()</code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-131-1.png" width="672" /></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelling-experimental-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="linear-mixed-effect-models-lmms.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
