<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Poisson regression | Advanced Biological Data Analysis</title>
  <meta name="description" content="Poisson regression | Advanced Biological Data Analysis" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="Poisson regression | Advanced Biological Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Poisson regression | Advanced Biological Data Analysis" />
  
  
  

<meta name="author" content="University of Auckland" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introduction-to-generalised-linear-models-glms.html"/>
<link rel="next" href="logistic-regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Nau mai, haere mai. Welcome to BIOSCI 738</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i>Syllabus</a>
<ul>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-community"><i class="fa fa-check"></i>Course Community</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#synopsis"><i class="fa fa-check"></i>Synopsis</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#prerequisites"><i class="fa fa-check"></i>Prerequisites</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-overview"><i class="fa fa-check"></i>Course overview</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#assessment-summary"><i class="fa fa-check"></i>Assessment summary</a></li>
<li class="chapter" data-level="" data-path="syllabus.html"><a href="syllabus.html#course-policies"><i class="fa fa-check"></i>Course policies</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-1.html"><a href="module-1.html"><i class="fa fa-check"></i>Module 1</a>
<ul>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html"><i class="fa fa-check"></i><code>R</code> and <code>RStudio</code></a>
<ul>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#installing-r-and-rstudio"><i class="fa fa-check"></i>Installing R and RStudio</a></li>
<li class="chapter" data-level="" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#getting-started"><i class="fa fa-check"></i>Getting started</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html"><i class="fa fa-check"></i>Reproducible research</a>
<ul>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html#project-oriented-workflow-good-practice"><i class="fa fa-check"></i>Project-oriented workflow: good practice</a></li>
<li class="chapter" data-level="" data-path="reproducible-research.html"><a href="reproducible-research.html#version-control-with-git-and-github"><i class="fa fa-check"></i>Version control with <code>git</code> and GitHub</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="your-data-and-r.html"><a href="your-data-and-r.html"><i class="fa fa-check"></i>Your data and <code>R</code></a>
<ul>
<li class="chapter" data-level="" data-path="your-data-and-r.html"><a href="your-data-and-r.html#reading-in-data-from-a-.csv-file"><i class="fa fa-check"></i>Reading in data from a <code>.csv</code> file</a></li>
<li class="chapter" data-level="" data-path="your-data-and-r.html"><a href="your-data-and-r.html#explore-your-data"><i class="fa fa-check"></i>Explore your data</a></li>
<li class="chapter" data-level="" data-path="your-data-and-r.html"><a href="your-data-and-r.html#the-pipe-operator"><i class="fa fa-check"></i>The pipe operator <code>%&gt;%</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html"><i class="fa fa-check"></i>Data wrangling</a>
<ul>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#introuducing-the-palmer-penguins"><i class="fa fa-check"></i>Introuducing the <span>Palmer penguins</span></a></li>
<li class="chapter" data-level="" data-path="data-wrangling.html"><a href="data-wrangling.html#common-dataframe-manipulations-in-the-tidyverse-using-dplyr-and-tidyr"><i class="fa fa-check"></i>Common dataframe manipulations in the <code>tidyverse</code>, using <code>dplyr</code> and <code>tidyr</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html"><i class="fa fa-check"></i>Data visualiation (data viz)</a>
<ul>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#exploratory-plots"><i class="fa fa-check"></i>Exploratory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#explanatory-plots"><i class="fa fa-check"></i>Explanatory plots</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#ten-simple-rules-for-better-figures"><i class="fa fa-check"></i>Ten Simple Rules for Better Figures</a></li>
<li class="chapter" data-level="" data-path="data-visualiation-data-viz.html"><a href="data-visualiation-data-viz.html#ggplot2"><i class="fa fa-check"></i><code>ggplot2</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="māori-data-sovereignty-principles.html"><a href="māori-data-sovereignty-principles.html"><i class="fa fa-check"></i>Māori Data Sovereignty principles</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-2.html"><a href="module-2.html"><i class="fa fa-check"></i>Module 2</a>
<ul>
<li class="chapter" data-level="" data-path="key-satistical-concepts.html"><a href="key-satistical-concepts.html"><i class="fa fa-check"></i>Key satistical concepts</a></li>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html"><i class="fa fa-check"></i>Bootstrap resampling</a>
<ul>
<li class="chapter" data-level="" data-path="bootstrap-resampling.html"><a href="bootstrap-resampling.html#example-constructing-bootstrap-confidence-intervals"><i class="fa fa-check"></i>Example: constructing bootstrap confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html"><i class="fa fa-check"></i>Permutation and randomisation tests</a>
<ul>
<li class="chapter" data-level="" data-path="permutation-and-randomisation-tests.html"><a href="permutation-and-randomisation-tests.html#a-permutation-test-jackal-mandible-lengths"><i class="fa fa-check"></i>A permutation test: Jackal mandible lengths</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="resampling-procedures-the-differences.html"><a href="resampling-procedures-the-differences.html"><i class="fa fa-check"></i>Resampling procedures, the differences</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html"><i class="fa fa-check"></i>Hypothesis testing: key terms</a>
<ul>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#p-values"><i class="fa fa-check"></i>😱 p-values 😱</a></li>
<li class="chapter" data-level="" data-path="hypothesis-testing-key-terms.html"><a href="hypothesis-testing-key-terms.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i>Type I and Type II errors</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html"><i class="fa fa-check"></i>Parametric hypothesis tests</a>
<ul>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-sample-t-test"><i class="fa fa-check"></i>One-Sample t-test</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#differences-between-two-means"><i class="fa fa-check"></i>Differences between two means</a></li>
<li class="chapter" data-level="" data-path="parametric-hypothesis-tests.html"><a href="parametric-hypothesis-tests.html#one-way-analysis-of-variance-anova"><i class="fa fa-check"></i>One-Way Analysis of Variance (ANOVA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html"><i class="fa fa-check"></i>Linear regression</a>
<ul>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#some-mathematical-notation"><i class="fa fa-check"></i>Some mathematical notation</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#modeling-bill-depth"><i class="fa fa-check"></i>Modeling Bill Depth</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#single-continuous-variable"><i class="fa fa-check"></i>Single continuous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#a-single-factor-variable"><i class="fa fa-check"></i>A single factor variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#one-factor-and-a-continuous-variable"><i class="fa fa-check"></i>One factor and a continuous variable</a></li>
<li class="chapter" data-level="" data-path="linear-regression.html"><a href="linear-regression.html#interactions"><i class="fa fa-check"></i>Interactions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="model-formula-syntax-in-r.html"><a href="model-formula-syntax-in-r.html"><i class="fa fa-check"></i>Model formula syntax in <code>R</code></a>
<ul>
<li class="chapter" data-level="" data-path="model-formula-syntax-in-r.html"><a href="model-formula-syntax-in-r.html#other-possible-models"><i class="fa fa-check"></i>Other possible models</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html"><i class="fa fa-check"></i>Model diagnostics for a linear model</a>
<ul>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#marginal-predictions"><i class="fa fa-check"></i>Marginal predictions</a></li>
<li class="chapter" data-level="" data-path="model-diagnostics-for-a-linear-model.html"><a href="model-diagnostics-for-a-linear-model.html#model-selection"><i class="fa fa-check"></i>Model selection</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html"><i class="fa fa-check"></i>Inference for a linear model</a>
<ul>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#point-prediction"><i class="fa fa-check"></i>Point prediction</a></li>
<li class="chapter" data-level="" data-path="inference-for-a-linear-model.html"><a href="inference-for-a-linear-model.html#confidence-intervals-for-parameters"><i class="fa fa-check"></i>Confidence intervals for parameters</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-3.html"><a href="module-3.html"><i class="fa fa-check"></i>Module 3</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html"><i class="fa fa-check"></i>Introduction to the design and analysis of experiments</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#key-phrases"><i class="fa fa-check"></i>Key phrases</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#the-three-key-principles"><i class="fa fa-check"></i>The three key principles:</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#replication"><i class="fa fa-check"></i>Replication</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#randomization"><i class="fa fa-check"></i>Randomization</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#blocking"><i class="fa fa-check"></i>Blocking</a></li>
<li class="chapter" data-level="" data-path="introduction-to-the-design-and-analysis-of-experiments.html"><a href="introduction-to-the-design-and-analysis-of-experiments.html#setting-up-an-experiment"><i class="fa fa-check"></i>Setting up an experiment</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html"><i class="fa fa-check"></i>Some basic experimental designs</a>
<ul>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#completely-randomised-design-crd"><i class="fa fa-check"></i>Completely randomised design (CRD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#randomised-complete-block-design-rcbd"><i class="fa fa-check"></i>Randomised complete block design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="some-basic-experimental-designs.html"><a href="some-basic-experimental-designs.html#factorial-design"><i class="fa fa-check"></i>Factorial design</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html"><i class="fa fa-check"></i>Modelling experimental data</a>
<ul>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-completely-randomised-design-crd-as-a-linear-model"><i class="fa fa-check"></i>A completely randomised design (CRD) as a linear model</a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#analysis-of-a-crd-in-r"><i class="fa fa-check"></i>Analysis of a CRD in <code>R</code></a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#a-factorial-experiment-as-a-crd"><i class="fa fa-check"></i>A Factorial experiment (as a CRD)</a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#unqual-replications-unbalanced-design"><i class="fa fa-check"></i>Unqual replications (unbalanced design)</a></li>
<li class="chapter" data-level="" data-path="modelling-experimental-data.html"><a href="modelling-experimental-data.html#sums-of-squares-ss"><i class="fa fa-check"></i>Sums of squares (<span class="math inline">\(SS\)</span>)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html"><i class="fa fa-check"></i>Multiple comparisons</a>
<ul>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#adjustments-for-multiple-testing"><i class="fa fa-check"></i>Adjustments for multiple testing</a></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#classification-of-multiple-hypothesis-tests"><i class="fa fa-check"></i>Classification of multiple hypothesis tests</a></li>
<li class="chapter" data-level="" data-path="multiple-comparisons.html"><a href="multiple-comparisons.html#multiple-comparison-procedures"><i class="fa fa-check"></i>Multiple comparison procedures</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html"><i class="fa fa-check"></i>Linear mixed-effect models (LMMs)</a>
<ul>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-randomised-controlled-block-design-rcbd"><i class="fa fa-check"></i>A Randomised Controlled Block Design (RCBD)</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-split-plot-design"><i class="fa fa-check"></i>A Split-plot design</a></li>
<li class="chapter" data-level="" data-path="linear-mixed-effect-models-lmms.html"><a href="linear-mixed-effect-models-lmms.html#a-repeated-measures-design"><i class="fa fa-check"></i>A repeated measures design</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-4.html"><a href="module-4.html"><i class="fa fa-check"></i>Module 4</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-generalised-linear-models-glms.html"><a href="introduction-to-generalised-linear-models-glms.html"><i class="fa fa-check"></i>Introduction to generalised linear models (GLMs)</a></li>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html"><i class="fa fa-check"></i>Poisson regression</a>
<ul>
<li class="chapter" data-level="" data-path="poisson-regression.html"><a href="poisson-regression.html#an-example-bird-abundance"><i class="fa fa-check"></i>An example: bird abundance</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html"><i class="fa fa-check"></i>Logistic regression</a>
<ul>
<li class="chapter" data-level="" data-path="logistic-regression.html"><a href="logistic-regression.html#an-example-lobsters"><i class="fa fa-check"></i>An example: lobsters</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="a-summary-of-glms.html"><a href="a-summary-of-glms.html"><i class="fa fa-check"></i>A summary of GLMs</a></li>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html"><i class="fa fa-check"></i>Generalised linear mixed-effects models (GLMMMs)</a>
<ul>
<li class="chapter" data-level="" data-path="generalised-linear-mixed-effects-models-glmmms.html"><a href="generalised-linear-mixed-effects-models-glmmms.html#fitting-a-glmm"><i class="fa fa-check"></i>Fitting a GLMM</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-5.html"><a href="module-5.html"><i class="fa fa-check"></i>Module 5</a>
<ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html"><i class="fa fa-check"></i>Clustering</a>
<ul>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#divisive-partitioning-methods."><i class="fa fa-check"></i>Divisive (partitioning) methods.</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#k-means-an-example-using-the-palmerpenguins-data"><i class="fa fa-check"></i>K-means: an example using the <code>palmerpenguins</code> data</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-agglomerative-clustering."><i class="fa fa-check"></i>Hierarchical agglomerative clustering.</a></li>
<li class="chapter" data-level="" data-path="clustering.html"><a href="clustering.html#hierarchical-clustering-an-example"><i class="fa fa-check"></i>Hierarchical clustering: an example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html"><i class="fa fa-check"></i>Principal Component Analysis (PCA)</a>
<ul>
<li class="chapter" data-level="" data-path="principal-component-analysis-pca.html"><a href="principal-component-analysis-pca.html#examples-in-r"><i class="fa fa-check"></i>Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html"><i class="fa fa-check"></i>Multidimensional Scaling (MDS)</a>
<ul>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#metric-scaling"><i class="fa fa-check"></i>Metric Scaling</a></li>
<li class="chapter" data-level="" data-path="multidimensional-scaling-mds.html"><a href="multidimensional-scaling-mds.html#correspondence-analysis-ca"><i class="fa fa-check"></i>Correspondence Analysis (CA)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="non-metric-multidimensional-scaling.html"><a href="non-metric-multidimensional-scaling.html"><i class="fa fa-check"></i>Non-metric Multidimensional Scaling</a>
<ul>
<li class="chapter" data-level="" data-path="non-metric-multidimensional-scaling.html"><a href="non-metric-multidimensional-scaling.html#examples-in-r-2"><i class="fa fa-check"></i>Examples in <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html"><i class="fa fa-check"></i>Linear Discriminant Analysis (LDA)</a>
<ul>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html#example-in-r"><i class="fa fa-check"></i>Example in <code>R</code></a></li>
<li class="chapter" data-level="" data-path="linear-discriminant-analysis-lda.html"><a href="linear-discriminant-analysis-lda.html#prediction"><i class="fa fa-check"></i>Prediction</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="module-6.html"><a href="module-6.html"><i class="fa fa-check"></i>Module 6</a>
<ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html"><i class="fa fa-check"></i>Least Squares Estimation</a>
<ul>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#some-basic-matrix-algebra"><i class="fa fa-check"></i>Some basic matrix algebra</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#linear-least-squares"><i class="fa fa-check"></i>Linear least squares</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#matrix-representation-of-a-crd"><i class="fa fa-check"></i>Matrix representation of a CRD</a></li>
<li class="chapter" data-level="" data-path="least-squares-estimation.html"><a href="least-squares-estimation.html#a-numeric-example"><i class="fa fa-check"></i>A numeric example</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html"><i class="fa fa-check"></i>Maximum likelihood estimation</a>
<ul>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#differeniation-rules"><i class="fa fa-check"></i>Differeniation rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#logarithm-rules"><i class="fa fa-check"></i>Logarithm rules</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-binomial-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Binomial distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-crd"><i class="fa fa-check"></i>Maximum likelihood estimation for a CRD</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximising-the-log-likelihood"><i class="fa fa-check"></i>Maximising the log-likelihood</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-poisson-distribution"><i class="fa fa-check"></i>Maximum likelihood estimation for a Poisson distribution</a></li>
<li class="chapter" data-level="" data-path="maximum-likelihood-estimation.html"><a href="maximum-likelihood-estimation.html#maximum-likelihood-estimation-for-a-continuous-random-variable"><i class="fa fa-check"></i>Maximum likelihood estimation for a continuous random variable</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html"><i class="fa fa-check"></i>Introduction to Bayesian statistics</a>
<ul>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#conditional-probability"><i class="fa fa-check"></i>Conditional probability</a></li>
<li class="chapter" data-level="" data-path="introduction-to-bayesian-statistics.html"><a href="introduction-to-bayesian-statistics.html#bayes-rule"><i class="fa fa-check"></i>Bayes’ rule</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Biological Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="poisson-regression" class="section level2 hasAnchor">
<h2>Poisson regression<a href="poisson-regression.html#poisson-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We saw the Poisson distribution in module 4. There, we talked about it in terms of rates. Additionally, it is commonly used as a distribution for counts.</p>
<p>In summary, the Poisson distribution is a discrete distribution (of positive values only) and has <span class="math inline">\(\text{Var}(Y_i) = \mu_i\)</span> (i.e., we expect the variance to increase with the mean).</p>
<p>If we were to assume (as previously) that <span class="math inline">\(\mu_i = \alpha + \beta_1 x_i\)</span> then we would be allowing <span class="math inline">\(\mu &lt; 0\)</span>, which is not supported by the Poisson distribution. So, we use a link function to map between <span class="math inline">\(\mu_i\)</span> and the real number line:</p>
<p><span class="math display">\[\text{log}(\mu_i) = \alpha + \beta_1 x_i.\]</span></p>
<p>So, <span class="math inline">\(\mu_i \geq 0\)</span> and <span class="math inline">\(-\infty &lt; \text{log}(\mu_i) &lt; \infty\)</span>; however negative the linear predictor <span class="math inline">\(\alpha + \beta_1 x_i\)</span> gets <span class="math inline">\(\mu_i\)</span> will always be positive.</p>
<p>Equivalently,
<span class="math display">\[ \mu_i = \text{exp}(\alpha + \beta_1 x_i)\]</span></p>
<p>and</p>
<p><span class="math display">\[Y_i \sim \text{Poisson}(\mu_i)\]</span></p>
<div id="interpreting-coefficients" class="section level4 hasAnchor">
<h4>Interpreting coefficients<a href="poisson-regression.html#interpreting-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Recall, for a linear regression model <span class="math inline">\(\mu = \alpha + \beta_1x\)</span>, when <span class="math inline">\(x=0\)</span> <span class="math inline">\(y = \alpha\)</span> and for every one-unit increase in <span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span> increases by amount <span class="math inline">\(\beta_1\)</span>.</p>
<p>For a Poisson regression model we have <span class="math inline">\(\text{log}(\mu) = \alpha + \beta_1 x.\)</span></p>
<p>We can interpret this in the same way! That is, when <span class="math inline">\(x\)</span> is zero, the log of the expected value of the response equals <span class="math inline">\(\alpha\)</span> and for every one-unit increase in <span class="math inline">\(x\)</span>, the log of the expected value of the response increases by amount <span class="math inline">\(\beta_1\)</span>. But interpreting the effect of <span class="math inline">\(x\)</span> on the log of the expected value is not straightforward.</p>
<p>Now, we have</p>
<p><span class="math display">\[\mu = \text{e}^{ \alpha + \beta_1 x} = \text{e}^{ \alpha}(\text{e}^{\beta_1})^{ x}.\]</span>
This implies that</p>
<ul>
<li>when <span class="math inline">\(x = 0\)</span> <span class="math inline">\(\mu = \text{e}^{ \alpha}(\text{e}^{\beta_1})^{0} = \text{e}^{ \alpha}\times 1 = \text{e}^{ \alpha},\)</span></li>
<li>when <span class="math inline">\(x = 1\)</span> <span class="math inline">\(\mu = \text{e}^{ \alpha}(\text{e}^{\beta_1})^{1} = \text{e}^{ \alpha}\text{e}^{\beta_1} = \text{e}^{ \alpha + \beta_1},\)</span></li>
<li>when <span class="math inline">\(x = 2\)</span> <span class="math inline">\(\mu = \text{e}^{ \alpha}(\text{e}^{\beta_1})^{2} = \text{e}^{ \alpha}\text{e}^{\beta_1} \text{e}^{\beta_1} = \text{e}^{ \alpha + \beta_1 + \beta_1},\)</span></li>
<li>when <span class="math inline">\(x = 3\)</span> <span class="math inline">\(\mu = \text{e}^{ \alpha}(\text{e}^{\beta_1})^{3} = \text{e}^{ \alpha}\text{e}^{\beta_1} \text{e}^{\beta_1}\text{e}^{\beta_1} = \text{e}^{ \alpha + \beta_1 + \beta_1 + \beta_1},\)</span> and</li>
<li>so on …</li>
</ul>
<p>Therefore, for every n-unit increase in x, the expected value of the response is <strong>multiplied</strong> by <span class="math inline">\(\text{e}^{n\beta_1}.\)</span></p>
</div>
<div id="goodness-of-fit" class="section level4 hasAnchor">
<h4>Goodness-of-fit<a href="poisson-regression.html#goodness-of-fit" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Typically, we use Poisson regression to</p>
<ol style="list-style-type: decimal">
<li>ensure the expected value is <span class="math inline">\(&gt;0\)</span>,</li>
<li>account for non-constant variance, and</li>
<li>assume a discrete distribution for a discrete response.</li>
</ol>
<p>But, how do we assess if our choice was appropriate? <em>Use the <strong>deviance</strong>!</em></p>
<p>For a fitted Poisson regression the deviance, <span class="math inline">\(D\)</span>, is</p>
<p><span class="math display">\[D = 2 \sum^{n}_{i=1} \{ Y_{i} \log(Y_{i}/\mu_{i}) - (Y_{i}-\mu_{i}) \}\]</span></p>
<p>where if <span class="math inline">\(Y_i=0\)</span>, the <span class="math inline">\(Y_{i} \log(Y_{i}/\mu_{i})\)</span> term is taken to be zero, and <span class="math inline">\(\mu_{i} = \exp(\hat{\beta}_{0} + \hat{\beta}_{1}X_{1} + ... + \hat{\beta}_{p} X_{p})\)</span> is the predicted mean for observation <span class="math inline">\(i\)</span> based on the estimated model parameters.</p>
<p>The deviance is a measure of how well the model fits the data. That is, if the model fits well, the observed values <span class="math inline">\(Y_{i}\)</span> will be close to their predicted means <span class="math inline">\(\mu_{i}\)</span>, causing both of the terms in <span class="math inline">\(D\)</span> to be small, and so the deviance to be small. The flip side of this is that a large deviance indicates a bad fitting model.</p>
<p>Formally, we can test the null hypothesis that the model is correct by calculating a p-value using
<span class="math display">\[ p = \Pr(\chi^2_{n - k} &gt; D).\]</span></p>
<p><strong>Conditions of the chi-squared approximation</strong></p>
<p>The distribution of the deviance under the null hypothesis is approximately chi-squared if the response of each observation is well approximated by a normal distribution. This holds for Poisson random variables with <span class="math inline">\(\mu_i &gt; 5\)</span>.</p>
<p>However, if our chi-squared approximation assumptions are not met we should find another way. See the example below for a simulation based approach.</p>
</div>
<div id="an-example-bird-abundance" class="section level3 hasAnchor">
<h3>An example: bird abundance<a href="poisson-regression.html#an-example-bird-abundance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A recent publication <a href="https://onlinelibrary.wiley.com/doi/10.1111/ddi.13445">Partitioning beta diversity to untangle mechanisms underlying the assembly of bird communities in Mediterranean olive groves</a> investigates bird abundance data for a number of olive farms. Each farm is catalogued according to the level of landscape complexity (high; intermediate; low) and the type of management of the ground cover (extensive or intensive).</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="poisson-regression.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb289-2"><a href="poisson-regression.html#cb289-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">&quot;https://raw.githubusercontent.com/STATS-UOA/databunker/master/data/bird_abundance.csv&quot;</span>)</span>
<span id="cb289-3"><a href="poisson-regression.html#cb289-3" aria-hidden="true" tabindex="-1"></a>birds <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb289-4"><a href="poisson-regression.html#cb289-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="fu">c</span>(<span class="st">&quot;OliveFarm&quot;</span>,<span class="st">&quot;Management&quot;</span>,<span class="st">&quot;Turdus_merula&quot;</span>,<span class="st">&quot;Phylloscopus_collybita&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb289-5"><a href="poisson-regression.html#cb289-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(., <span class="fu">c</span>(<span class="sc">-</span>OliveFarm, <span class="sc">-</span>Management), <span class="at">names_to =</span> <span class="st">&quot;Species&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;Count&quot;</span>) </span>
<span id="cb289-6"><a href="poisson-regression.html#cb289-6" aria-hidden="true" tabindex="-1"></a>birds</span></code></pre></div>
<pre><code>## # A tibble: 80 × 4
##    OliveFarm   Management Species                Count
##    &lt;chr&gt;       &lt;chr&gt;      &lt;chr&gt;                  &lt;dbl&gt;
##  1 MORALEDAEXP intensive  Turdus_merula             21
##  2 MORALEDAEXP intensive  Phylloscopus_collybita    14
##  3 MORALEDACON extensive  Turdus_merula             29
##  4 MORALEDACON extensive  Phylloscopus_collybita    21
##  5 OJUELOSEXP  intensive  Turdus_merula              5
##  6 OJUELOSEXP  intensive  Phylloscopus_collybita    31
##  7 OJUELOSCON  extensive  Turdus_merula             12
##  8 OJUELOSCON  extensive  Phylloscopus_collybita    52
##  9 LUNAEXP     extensive  Turdus_merula            103
## 10 LUNAEXP     extensive  Phylloscopus_collybita    10
## # … with 70 more rows</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-168-1.png" width="672" /></p>
<p>Fitting a poisson model we specify <code>family = "poisson"</code> in a call to <code>glm()</code>. Note that the default link function for <code>family = "poisson"</code> is the log link; we could also use the equivalent syntax <code>poisson(link = log)</code> to specify this model. Or, we could change the link function to something else (e.g., <code>poisson(link = identity)</code>) that makes sense.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="poisson-regression.html#cb291-1" aria-hidden="true" tabindex="-1"></a>glm_bird <span class="ot">&lt;-</span> <span class="fu">glm</span>(Count <span class="sc">~</span> Species, <span class="at">data =</span> birds, <span class="at">family =</span> <span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb291-2"><a href="poisson-regression.html#cb291-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glm_bird)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = Count ~ Species, family = &quot;poisson&quot;, data = birds)
## 
## Deviance Residuals: 
##    Min      1Q  Median      3Q     Max  
## -9.994  -3.851  -1.348   2.868  10.828  
## 
## Coefficients:
##                      Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)           3.06105    0.03422   89.45   &lt;2e-16 ***
## SpeciesTurdus_merula  0.94537    0.04032   23.45   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for poisson family taken to be 1)
## 
##     Null deviance: 2234.6  on 79  degrees of freedom
## Residual deviance: 1621.9  on 78  degrees of freedom
## AIC: 2030.1
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The fitted model is therefore</p>
<p><span class="math display">\[
\log ({ \widehat{E( \operatorname{Count} )} })  = 3.061 + 0.945(\operatorname{Species}_{\operatorname{Turdus\_merula}})
\]</span></p>
<div id="interpreting-the-coefficients" class="section level4 hasAnchor">
<h4>Interpreting the coefficients<a href="poisson-regression.html#interpreting-the-coefficients" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Interpreting the coefficients above we estimate that the <strong>log</strong> of the expected number of <em>Phylloscopus collybita</em> is 3.06 and the <strong>log</strong> of the expected number of <em>Turdus merula</em> is 4.01.</p>
<p>But what about the expected number?</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="poisson-regression.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(glm_bird))</span></code></pre></div>
<pre><code>##          (Intercept) SpeciesTurdus_merula 
##             21.35000              2.57377</code></pre>
<p>Therefore, we estimate that the expected average number of <em>Phylloscopus collybita</em> is 21.35 and the expected average number of <em>Turdus merula</em> is 54.95.</p>
<p>Using confidence intervals:</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="poisson-regression.html#cb295-1" aria-hidden="true" tabindex="-1"></a>confint <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint</span>(glm_bird)[<span class="dv">1</span>,])</span>
<span id="cb295-2"><a href="poisson-regression.html#cb295-2" aria-hidden="true" tabindex="-1"></a>confint</span></code></pre></div>
<pre><code>##    2.5 %   97.5 % 
## 19.94989 22.81408</code></pre>
<p>Therefore, we estimate that the expected average number of <em>Phylloscopus collybita</em> is between 19.95 and 22.81.</p>
<p>For a <strong>multiplicative interpretation</strong> of the effect use <span class="math inline">\(\text{exp}(\beta_1)\)</span></p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="poisson-regression.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(glm_bird)[<span class="dv">2</span>])</span></code></pre></div>
<pre><code>## SpeciesTurdus_merula 
##              2.57377</code></pre>
<p>Therefore, we estimate that the expected number of <em>Turdus merula</em> is 2.57 <span class="math inline">\(\times\)</span> greater than <em>Phylloscopus collybita</em>.</p>
<p>For a <strong>percentage-change interpretation</strong> use <span class="math inline">\(100 \times \left (\text{exp}(\beta_1)−1 \right )\)</span>:</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="poisson-regression.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(glm_bird)[<span class="dv">2</span>]) <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## SpeciesTurdus_merula 
##              157.377</code></pre>
<p>Therefore, we estimate that expected number of <em>Turdus merula</em> is 157.38% greater than <em>Phylloscopus collybita</em>.</p>
<p>Using 95% <strong>confidence intervals</strong>:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="poisson-regression.html#cb301-1" aria-hidden="true" tabindex="-1"></a>confint <span class="ot">&lt;-</span> <span class="dv">100</span><span class="sc">*</span>(<span class="fu">exp</span>(<span class="fu">confint</span>(glm_bird)[<span class="dv">2</span>, ]) <span class="sc">-</span> <span class="dv">1</span>)</span>
<span id="cb301-2"><a href="poisson-regression.html#cb301-2" aria-hidden="true" tabindex="-1"></a>confint</span></code></pre></div>
<pre><code>##    2.5 %   97.5 % 
## 137.9259 178.6742</code></pre>
<p>So, we estimate that expected number of <em>Turdus merula</em> is between 137.93% and 178.67% greater than <em>Phylloscopus collybita</em>.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
</div>
<div id="model-diagnostics" class="section level4 hasAnchor">
<h4>Model diagnostics<a href="poisson-regression.html#model-diagnostics" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div id="residuals" class="section level5 hasAnchor">
<h5>Residuals<a href="poisson-regression.html#residuals" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Recall from module 2, where we looked at residual plots to check our assumptions for a linear model. In a similar way we can use residuals to check how appropriate our GLM is (i.e., to help diagnose the overall goodness-of-fit and to see if our model assumptions are met). Often, Pearson and deviance residuals are used in model diagnostics for generalized linear models. Below, all three are calculated for our Poisson model above.</p>
<p><strong>Response residuals</strong> are the <em>conventional</em> residual on the response level. That is, the fitted residuals are transformed by taking the inverse of the link function. Think back to linear models where the link function was set as the identity.</p>
<p><strong>Deviance residuals</strong> represent the contributions of individual samples to the deviance, <em>D</em> (see above).</p>
<p><strong>Pearson residuals</strong> are calculated by normalizing the raw residuals (i.e., expected - estimate) by the square root of the estimate.</p>
<p>Luckily, we can calculate all three directly in <code>R</code> as follows.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="poisson-regression.html#cb303-1" aria-hidden="true" tabindex="-1"></a><span class="do">## response residuals</span></span>
<span id="cb303-2"><a href="poisson-regression.html#cb303-2" aria-hidden="true" tabindex="-1"></a>resids_response <span class="ot">&lt;-</span> <span class="fu">residuals</span>(glm_bird, <span class="at">type =</span> <span class="st">&quot;response&quot;</span>)</span>
<span id="cb303-3"><a href="poisson-regression.html#cb303-3" aria-hidden="true" tabindex="-1"></a><span class="do">## deviance residuals</span></span>
<span id="cb303-4"><a href="poisson-regression.html#cb303-4" aria-hidden="true" tabindex="-1"></a>resids_deviance <span class="ot">&lt;-</span> <span class="fu">residuals</span>(glm_bird, <span class="at">type =</span> <span class="st">&quot;deviance&quot;</span>)</span>
<span id="cb303-5"><a href="poisson-regression.html#cb303-5" aria-hidden="true" tabindex="-1"></a><span class="do">## pearson residuals</span></span>
<span id="cb303-6"><a href="poisson-regression.html#cb303-6" aria-hidden="true" tabindex="-1"></a>resids_pearson <span class="ot">&lt;-</span> <span class="fu">residuals</span>(glm_bird, <span class="at">type =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<p>Plotting all three types we can asses how appropriate our chosen model is.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-178-1.png" width="672" /></p>
<p>So, what do you see? Look back at the assumptions of a Poisson model. What do you conclude from the plots above?</p>
</div>
<div id="deviance-using-the-chi-squared-approach" class="section level5 hasAnchor">
<h5>Deviance (using the chi-squared approach)<a href="poisson-regression.html#deviance-using-the-chi-squared-approach" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<p>Luckily no manual calculations are required, our <code>glm()</code> call returns the values we need directly:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb304-1"><a href="poisson-regression.html#cb304-1" aria-hidden="true" tabindex="-1"></a><span class="do">## extract the residual deviance</span></span>
<span id="cb304-2"><a href="poisson-regression.html#cb304-2" aria-hidden="true" tabindex="-1"></a>D <span class="ot">&lt;-</span> glm_bird<span class="sc">$</span>deviance</span>
<span id="cb304-3"><a href="poisson-regression.html#cb304-3" aria-hidden="true" tabindex="-1"></a>D</span></code></pre></div>
<pre><code>## [1] 1621.948</code></pre>
<div class="sourceCode" id="cb306"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb306-1"><a href="poisson-regression.html#cb306-1" aria-hidden="true" tabindex="-1"></a><span class="do">## extract the residual degrees of freedom (n-k)</span></span>
<span id="cb306-2"><a href="poisson-regression.html#cb306-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> glm_bird<span class="sc">$</span>df.residual</span>
<span id="cb306-3"><a href="poisson-regression.html#cb306-3" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div>
<pre><code>## [1] 78</code></pre>
<p>Therefore, to test the relevant null hypothesis (that the model is correct) we use</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="poisson-regression.html#cb308-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(D, df)</span></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>We have strong evidence to reject the null hypothesis; suggesting a lack of fit! <strong>BUT</strong> are our chi-squared approximation assumptions met? If not, we might take a <strong>simulation based approach</strong>. This is, however, beyond the scope of this course.</p>
</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introduction-to-generalised-linear-models-glms.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="logistic-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
